"""modified novels db model to include permissions

Revision ID: 01744484f72f
Revises: 416fb845959c
Create Date: 2025-12-23 23:39:05.554004+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01744484f72f'
down_revision = '416fb845959c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_contributors',
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('contributor_role', sa.Enum('owner', 'viewer', 'editor', name='role', native_enum=False, length=10), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('contributor_id'),
    sa.UniqueConstraint('novel_id', 'user_id', name='uq_novel_user')
    )
    op.add_column('novels', sa.Column('novel_visibility', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('novels', sa.Column('novel_type', sa.Enum('original', 'translation', 'other', name='noveltype', native_enum=False, length=16), nullable=False, server_default='original'))
    op.add_column('novels', sa.Column('novel_parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_novel_parent', 'novels', 'novels', ['novel_parent_id'], ['novel_id'])
    op.create_check_constraint('chk_novel_visibility', 'novels', 'novel_visibility IN (0, 1, 2, 3)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_novel_parent', 'novels', type_='foreignkey')
    op.drop_column('novels', 'novel_parent_id')
    op.drop_column('novels', 'novel_type')
    op.drop_column('novels', 'novel_visibility')
    op.drop_table('novel_contributors')
    # ### end Alembic commands ###
