"""removed translations service

Revision ID: 1fbdd31e9fe5
Revises: 01744484f72f
Create Date: 2025-12-24 02:23:58.787737+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fbdd31e9fe5'
down_revision = '01744484f72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translated_chapters')
    op.drop_table('translations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translations',
    sa.Column('translation_id', sa.INTEGER(), server_default=sa.text("nextval('translations_translation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('novel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], name='translations_language_id_fkey'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='translations_novel_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='translations_user_id_fkey'),
    sa.PrimaryKeyConstraint('translation_id', name='translations_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('translated_chapters',
    sa.Column('translated_chapter_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('translated_chapter_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('translated_chapter_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('translation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['raw_chapter_id'], ['raw_chapters.raw_chapter_id'], name=op.f('translated_chapters_raw_chapter_id_fkey')),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.translation_id'], name=op.f('translated_chapters_translation_id_fkey')),
    sa.PrimaryKeyConstraint('translated_chapter_id', name=op.f('translated_chapters_pkey')),
    sa.UniqueConstraint('translation_id', 'raw_chapter_id', name=op.f('tl_chapter_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
