"""some typing issues in some of the database models (autolabels and label_datas i think)

Revision ID: 416fb845959c
Revises: a5d20765c07d
Create Date: 2025-12-17 05:37:31.493921+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416fb845959c'
down_revision = 'a5d20765c07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_one_label_with_start_per_label_data'), 'labels', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_one_label_with_start_per_label_data'), 'labels', ['label_start', 'label_data_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
