"""modified labels db models

Revision ID: b5c2299f7d1c
Revises: e4537d18d35c
Create Date: 2025-12-30 21:49:19.335958+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c2299f7d1c'
down_revision = 'e4537d18d35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_group_contributors',
    sa.Column('label_contributor_role', sa.Enum('owner', 'viewer', 'editor', name='labelrole', native_enum=False, length=10), nullable=False),
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('label_group_id', 'user_id')
    )
    op.drop_constraint(op.f('one_label_group_with_name_per_user_novel'), 'label_groups', type_='unique')
    op.drop_constraint(op.f('label_groups_user_id_fkey'), 'label_groups', type_='foreignkey')
    op.drop_column('label_groups', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_groups', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('label_groups_user_id_fkey'), 'label_groups', 'users', ['user_id'], ['user_id'])
    op.create_unique_constraint(op.f('one_label_group_with_name_per_user_novel'), 'label_groups', ['label_group_name', 'user_id', 'novel_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('label_group_contributors')
    # ### end Alembic commands ###
