/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a label add operation. Inherits all attributes from LabelOpBase.
 *
 * Attributes:
 *     op: The string literal 'add'.
 *     dirty: Boolean whether to mark the label as dirty.
 *     entity_group: String representing what entity group this label belongs to. If none, then set a default value.
 *     score: Float score between 0.0 and 1.0 representing how likely this label is to be an entity.
 */
export interface AddLabelOp {
  dirty?: boolean;
  /** @minimum 0 */
  endPos: number;
  entityGroup?: string | null;
  op: 'add';
  /**
     * @minimum 0
     * @maximum 1
     */
  score?: number;
  /** @minimum 0 */
  startPos: number;
  /** @maxLength 128 */
  word: string;
}
