/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AddLabelOpOp = typeof AddLabelOpOp[keyof typeof AddLabelOpOp];


export const AddLabelOpOp = {
  add: 'add',
} as const;
