/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AutoLabelMeta } from './autoLabelMeta';

export interface AutoLabelMetaWithCid {
  autoLabelMeta: AutoLabelMeta;
  chapterId: string;
}
