/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Status for an autolabel in database. One of 'failed', 'pending', 'processing', 'done'
 */
export type AutoLabelProgress = typeof AutoLabelProgress[keyof typeof AutoLabelProgress];


export const AutoLabelProgress = {
  failed: 'failed',
  pending: 'pending',
  processing: 'processing',
  done: 'done',
} as const;
