/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CluenerParams } from './cluenerParams';
import type { DoNothingParams } from './doNothingParams';

/**
 * Pydantic schema for an autolabel run (batch).
 *
 * A run groups autolabels created together in a single request.
 *
 * Attributes:
 *     run_id: UUID identifier for this run.
 *     triggered_by: UUID of user who triggered the run, or None.
 *     model_name: Name of the NER model used.
 *     model_params: Parameters for the NER model.
 *     created_at: When the run was created.
 */
export interface AutoLabelRunInput {
  createdAt: string;
  modelName: string;
  modelParams: CluenerParams | DoNothingParams;
  novelId: string;
  runId: string;
  triggeredBy: string;
}
