/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AutoLabelProgress } from './autoLabelProgress';
import type { LabelBase } from './labelBase';

/**
 * Pydantic schema for a single auto-labeled data entry with its label data.
 *
 * Attributes:
 *     auto_label_id: UUID identifier for this AutoLabel.
 *     auto_label_data: List of labels produced by the NER model, or None if not yet complete.
 *     auto_label_status: Labeling progress for this autolabel.
 *     auto_label_message: Details on status (e.g. failure reason).
 *     auto_label_last_job_id: Job id of last request to autogenerate.
 *     chapter_content_id: UUID of chapter content this AutoLabel is for.
 *     run_id: UUID of the AutoLabelRun this autolabel belongs to.
 */
export interface AutoLabel {
  autoLabelData?: LabelBase[] | null;
  autoLabelId: string;
  autoLabelLastJobId?: string | null;
  autoLabelMessage?: string | null;
  autoLabelStatus: AutoLabelProgress;
  chapterContentId: string;
  runId: string;
}
