/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BoolDataType = typeof BoolDataType[keyof typeof BoolDataType];


export const BoolDataType = {
  bool: 'bool',
} as const;
