/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BoolFieldType = typeof BoolFieldType[keyof typeof BoolFieldType];


export const BoolFieldType = {
  bool: 'bool',
} as const;
