/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BoolDataType } from './boolDataType';
import type { BooleanValue } from './booleanValue';

export interface BoolData {
  kind?: 'value';
  type: BoolDataType;
  value: BooleanValue;
}
