/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CacheEntryStatus = typeof CacheEntryStatus[keyof typeof CacheEntryStatus];


export const CacheEntryStatus = {
  pending: 'pending',
  success: 'success',
  failure: 'failure',
} as const;
