/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Chapter } from './chapter';
import type { ChapterContent } from './chapterContent';

/**
 * Pydantic schema for aggregating a ChapterContent and a Chapter together.
 *
 * Attributes:
 *     metadata: The metadata of the chapter, such as title and whether it's primary.
 *     content: The text content of the chapter.
 */
export interface ChapterData {
  content: ChapterContent;
  metadata: Chapter;
}
