/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for the text content of a chapter.
 *
 * Attributes:
 *     chapter_content_text: The full text content of the chapter.
 *     chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.
 *     chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.
 */
export interface ChapterContent {
  chapterContentId: string;
  chapterContentText: string;
  chapterContentVersion: number;
}
