/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Metadata for a ChapterContent.
 *
 * Attributes:
 *     chapter_content_version: The version number of the text content, used for optimistic concurrency control when updating text.
 *     chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.
 */
export interface ChapterContentMeta {
  chapterContentId: string;
  chapterContentVersion: number;
}
