/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for chapter metadata. Represents a single "chapter" entry, which groups all its revisions.
 *
 * Attributes:
 *     chapter_id: UUID primary key identifier.
 *     chapter_num: The chapter number.
 *     novel_id: UUID foreign key to the novel this chapter belongs to.
 */
export interface Chapter {
  chapterId: string;
  chapterIsPublic: boolean;
  chapterNum: number;
  chapterTitle: string;
  novelId: string;
}
