/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChapterUpload {
  chapterContentText: string;
  chapterIsPublic?: boolean;
  chapterNum: number;
  chapterTitle?: string | null;
}
