/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CluenerParamsSeparators } from './cluenerParamsSeparators';

/**
 * Pydantic schema for a Cluener model.
 *
 * Attributes:
 *     chunk_size: Integer between 1 and 512. Determines max size of chunks passed to NER model. Has default value 500.
 *     separators: Dictionary of the form `char : SepPriority`. The predict algorithm will prioritize chunks ending in higher priority separators. Has default value (read the code to see what it is.)
 *     force_chunk: If no separators found in some interval, force the chunker to chunk mid-sentence. Has default value False.
 *
 * Notes:
 *     To validate this model without injecting default values, call `CluenerModelParams.model_validate(..., context={'skip_default_values' : True})`.
 */
export interface CluenerParams {
  /**
     * @maximum 512
     * @exclusiveMinimum 0
     */
  chunkSize?: number;
  forceChunk?: boolean;
  modelName?: 'cluener';
  separators?: CluenerParamsSeparators;
}
