/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SepPriority } from './sepPriority';

export type CluenerParamsSeparators = {[key: string]: SepPriority};
