/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CombineChapterStageCreateAction } from './combineChapterStageCreateAction';
import type { CombineChapterStageCreateConfig } from './combineChapterStageCreateConfig';

export interface CombineChapterStageCreate {
  action: CombineChapterStageCreateAction;
  config?: CombineChapterStageCreateConfig;
}
