/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CombineChapterStageCreateAction = typeof CombineChapterStageCreateAction[keyof typeof CombineChapterStageCreateAction];


export const CombineChapterStageCreateAction = {
  combine_chapter: 'combine_chapter',
} as const;
