/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AutoLabelMetaWithCid } from './autoLabelMetaWithCid';
import type { AutoLabelRun } from './autoLabelRun';

/**
 * Pydantic schema for the response after creating autolabels.
 *
 * Attributes:
 *     run: The autolabel run that was created.
 *     autolabels: The list of autolabel entries created in this run.
 */
export interface CreateAutoLabelsResponse {
  autolabels: AutoLabelMetaWithCid[];
  run: AutoLabelRun;
}
