/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserType } from './userType';

/**
 * Pydantic schema to validate data required to create a user.
 *
 * Attributes:
 *     user_name: Username of user being created.
 *     user_password: Unhashed password of user being create.
 *     user_type: UserType type of user to be created.
 * Notes:
 */
export interface CreateUser {
  userName: string;
  userPassword: string;
  userType: UserType;
}
