/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NovelType } from './novelType';
import type { Visibility } from './visibility';

/**
 * Pydantic schema to validate forms for creating a novel.
 *
 * Attributes:
 *     novel_title: Novel title to create.
 *     novel_description: Description of novel we are creating.
 *     novel_author: Author of novel we are creating.
 *     novel_visibility: Visibility level of novel we are creating.
 *     novel_type: Type of novel we are creating.
 *     language_code: String code key to language of novel we are creating.
 *     source_work_id: Optional source work to attach to. If None, a new source work is auto-created.
 */
export interface CreateNovel {
  languageCode: string;
  novelAuthor?: string | null;
  novelDescription?: string | null;
  novelTitle: string;
  novelType: NovelType;
  novelVisibility: Visibility;
  sourceWorkId?: string | null;
}
