/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema to validate forms for creating a source work.
 *
 * Attributes:
 *     source_work_title: Title of the source work to create.
 *     source_work_description: Optional description.
 */
export interface CreateSourceWork {
  sourceWorkDescription?: string | null;
  sourceWorkTitle: string;
}
