/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreateLabelDataByAutoLabelModelName = typeof CreateLabelDataByAutoLabelModelName[keyof typeof CreateLabelDataByAutoLabelModelName];


export const CreateLabelDataByAutoLabelModelName = {
  cluener: 'cluener',
  do_nothing: 'do_nothing',
} as const;
