/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for validating create requests for label data.
 *
 * Attributes:
 *     chapter_content_id: UUID of chapter content being labelled.
 */
export interface CreateLabelData {
  chapterContentId: string;
}
