/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryType } from './memoryType';
import type { Scope } from './scope';

export interface CreateGlossaryMemory {
  chapterContentId: string;
  chapterId: string;
  /** @minLength 1 */
  memoryContent: string;
  memoryType: MemoryType;
  scope?: Scope | null;
  /** @minItems 1 */
  termIds: string[];
}
