/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Return message for CreateLabelDataByAutoLabel.
 *
 * Attributes:
 *     success: List of tuples of (chapter_id, chapter_content_id) for successful inserts.
 *     errors: List of tuples of (chapter_id, chapter_content_id, error message) for failed inserts.
 */
export interface CreateLabelDataByAutoLabelStatus {
  /**
     * @items.minItems 3
     * @items.maxItems 3
     */
  errors: [string, string, string][];
  /**
     * @items.minItems 2
     * @items.maxItems 2
     */
  success: [string, string][];
}
