/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema to validate data for creating a new chapter. The novel_id is expected to be passed via the URL path.
 *
 * Attributes:
 *     chapter_num: The chapter number to create.
 *     chapter_title: Title of the chapter. Defaults to empty string.
 *     chapter_is_public: Whether the chapter is publicly visible. Defaults to False.
 */
export interface CreateChapter {
  chapterIsPublic?: boolean;
  chapterNum: number;
  chapterTitle?: string;
}
