/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AutoLabelMeta } from './autoLabelMeta';
import type { AutoLabelRunOutput } from './autoLabelRunOutput';

/**
 * Pydantic schema for the response after creating autolabels.
 *
 * Attributes:
 *     run: The autolabel run that was created.
 *     autolabels: The list of autolabel entries created in this run.
 */
export interface CreateAutoLabelsResponse {
  autolabels: AutoLabelMeta[];
  run: AutoLabelRunOutput;
}
