/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for validating forms for creating a label group.
 *
 * Attributes:
 *     label_group_name: Name of label group to create.
 *     novel_id: UUID of novel this label group belongs to.
 */
export interface CreateLabelGroup {
  /** @maxLength 31 */
  labelGroupName: string;
  novelId: string;
}
