/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CluenerParams } from './cluenerParams';
import type { DoNothingParams } from './doNothingParams';

/**
 * Pydantic schema for creating a new autolabel run.
 *
 * Attributes:
 *     novel_id: UUID of novel to create auto labels for.
 *     params: Parameters for the NER model. Discriminated by model_name attribute.
 *     chapter_ids: Optional. Restrict to specific chapter UUIDs.
 *     start: Optional. Restrict to chapters with number >= start.
 *     end: Optional. Restrict to chapters with number < end.
 *     is_public: Optional. Restrict to chapters with this specific public flag.
 */
export interface CreateAutoLabels {
  chapterIds?: string[] | null;
  end?: number | null;
  isPublic?: boolean | null;
  novelId: string;
  params: CluenerParams | DoNothingParams;
  start?: number | null;
}
