/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BoolData } from './boolData';
import type { FloatData } from './floatData';
import type { IntDataOutput } from './intDataOutput';
import type { LabelRefData } from './labelRefData';
import type { StringData } from './stringData';
import type { TextSpanData } from './textSpanData';

export type DataType = StringData | IntDataOutput | FloatData | BoolData | TextSpanData | LabelRefData;
