/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DataObjFields } from './dataObjFields';

export interface DataObj {
  fields?: DataObjFields;
  kind?: 'object';
}
