/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type DeleteUserStatusStatus = typeof DeleteUserStatusStatus[keyof typeof DeleteUserStatusStatus];


export const DeleteUserStatusStatus = {
  success: 'success',
  fail: 'fail',
  verify: 'verify',
} as const;
