/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a label delete operation. Inherits all attributes from LabelOpBase.
 *
 * Attributes:
 *     op: The string literal 'delete'.
 */
export interface DeleteLabelOp {
  /** @minimum 0 */
  endPos: number;
  op: 'delete';
  /** @minimum 0 */
  startPos: number;
  /** @maxLength 128 */
  word: string;
}
