/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Generic error payload for HTTPException responses that only return a detail string.
 *
 * Attributes:
 *     detail: Human-readable description of the error.
 */
export interface DetailHTTPErrorResponse {
  detail: string;
}
