/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a DoNothing model.
 *
 * Attributes:
 *     model_name: Literal "do_nothing".
 */
export const DoNothingParamsValue = {
  modelName: 'do_nothing',
} as const;
export type DoNothingParams = typeof DoNothingParamsValue;
