/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChapterContent } from './chapterContent';
import type { EagerEntry } from './eagerEntry';
import type { LabelGroup } from './labelGroup';
import type { LazyEntry } from './lazyEntry';

/**
 * Pydantic schema for the data needed to edit a chapter.
 *
 * Attributes:
 *     chapter_content: ChapterContent being edited.
 *     no_label_data: List of LabelGroup objects that have no label data associated with them.
 */
export interface EditChapterData {
  chapterContent: ChapterContent;
  eagerLabelData: EagerEntry[];
  lazyLabelData: LazyEntry[];
  noLabelData: LabelGroup[];
}
