/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * @minLength 1
 * @maxLength 128
 * @pattern .*\S.*
 */
export type FieldName = string;
