/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type FloatFieldType = typeof FloatFieldType[keyof typeof FloatFieldType];


export const FloatFieldType = {
  float: 'float',
} as const;
