/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { FloatFieldType } from './floatFieldType';

export interface FloatField {
  mutable?: boolean;
  obj?: false;
  type: FloatFieldType;
}
