/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type FloatDataType = typeof FloatDataType[keyof typeof FloatDataType];


export const FloatDataType = {
  float: 'float',
} as const;
