/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { FunctionDefinitionResponseFunctionDefinition } from './functionDefinitionResponseFunctionDefinition';

export interface FunctionDefinitionResponse {
  createdAt: string;
  functionDefinition: FunctionDefinitionResponseFunctionDefinition;
  functionDefinitionId: string;
  functionName: string;
  namespace: string;
  updatedAt: string;
}
