/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewStatus } from './reviewStatus';

/**
 * A glossary term together with its associated-memory count in the requested scope.
 */
export interface GlossaryTermSummary {
  /** @minimum 0 */
  associatedMemoryCount: number;
  /** Human-review state of the term. Pending terms are unverified; approved terms are verified. */
  reviewStatus: ReviewStatus;
  /** Term exactly as it appears in the novel's source text. */
  term: string;
  /** Stable identifier for the glossary term. */
  termId: string;
}
