/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryTerm } from './glossaryTerm';
import type { Memory } from './memory';

/**
 * A memory together with the glossary terms it describes.
 */
export interface GlossaryMemory {
  /** The memory that describes the glossary terms. */
  memory: Memory;
  /** Glossary terms described by this memory; one memory may apply to multiple related terms. */
  terms: GlossaryTerm[];
}
