/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BoolData } from './boolData';
import type { IntDataOutput } from './intDataOutput';
import type { StringData } from './stringData';

export type GroupDataOutput = StringData | IntDataOutput | BoolData;
