/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupingResponse } from './groupingResponse';

export interface GroupOperationAccepted {
  grouping: GroupingResponse;
  jobId: string;
}
