/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GroupingResponseOutputType = typeof GroupingResponseOutputType[keyof typeof GroupingResponseOutputType];


export const GroupingResponseOutputType = {
  string: 'string',
  int: 'int',
  bool: 'bool',
} as const;
