/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupDataInput } from './groupDataInput';

export interface GroupFilter {
  groupingId: string;
  /** @maxItems 100 */
  values: GroupDataInput[];
}
