/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupDataOutput } from './groupDataOutput';

export type InstanceQueryResultGroupValues = {[key: string]: GroupDataOutput};
