/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { DataObj } from './dataObj';

export interface InstanceResponse {
  instanceId: string;
  value: DataObj;
  workflowId: string;
}
