/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Frame } from './frame';

export interface InstanceQuery {
  /** Cursor for pagination. If provided, must be a valid instance id. The query will return results after this cursor according to the sort keys. */
  cursor?: string | null;
  frame: Frame;
  /**
     * @minimum 1
     * @maximum 100
     */
  limit?: number;
}
