/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { InstanceOptionsOptions } from './instanceOptionsOptions';

export interface InstanceOptions {
  instances: unknown[];
  options: InstanceOptionsOptions;
}
