/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupData } from './groupData';

export type InstanceQueryResultGroupValues = {[key: string]: GroupData};
