/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IntDataInputType } from './intDataInputType';
import type { IntegerValueInput } from './integerValueInput';

export interface IntDataInput {
  kind?: 'value';
  type: IntDataInputType;
  value: IntegerValueInput;
}
