/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type IntDataOutputType = typeof IntDataOutputType[keyof typeof IntDataOutputType];


export const IntDataOutputType = {
  int: 'int',
} as const;
