/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type IntDataType = typeof IntDataType[keyof typeof IntDataType];


export const IntDataType = {
  int: 'int',
} as const;
