/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IntDataType } from './intDataType';
import type { IntegerValue } from './integerValue';

export interface IntData {
  kind?: 'value';
  type: IntDataType;
  value: IntegerValue;
}
