/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IntDataOutputType } from './intDataOutputType';
import type { SrcFiltersDataTypesIntegerValue1 } from './srcFiltersDataTypesIntegerValue1';

export interface IntDataOutput {
  kind?: 'value';
  type: IntDataOutputType;
  value: SrcFiltersDataTypesIntegerValue1;
}
