/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type IntDataInputType = typeof IntDataInputType[keyof typeof IntDataInputType];


export const IntDataInputType = {
  int: 'int',
} as const;
