/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IntDataType } from './intDataType';
import type { SrcFiltersDataTypesIntegerValue1 } from './srcFiltersDataTypesIntegerValue1';

export interface IntData {
  obj?: false;
  type: IntDataType;
  value: SrcFiltersDataTypesIntegerValue1;
}
