/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { IntFieldType } from './intFieldType';

export interface IntField {
  kind?: 'field';
  mutable?: boolean;
  type: IntFieldType;
}
