/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { JobParamsToolsets } from './jobParamsToolsets';
import type { ModelNameOutput } from './modelNameOutput';

export interface JobParams {
  modelName: ModelNameOutput;
  toolsets: JobParamsToolsets;
}
