/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModelName } from './modelName';
import type { PluginName } from './pluginName';

export interface JobParams {
  modelName: ModelName;
  plugins: PluginName[];
}
