/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { JobParamsToolsets } from './jobParamsToolsets';
import type { ModelName } from './modelName';

export interface JobParams {
  modelName: ModelName;
  toolsets: JobParamsToolsets;
}
