/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a list of labels in some text.
 *
 * Attributes:
 *     label_data_id: UUID identifier for this LabelData.
 *     label_group_id: UUID of label group this LabelData belongs to.
 *     chapter_content_id: UUID of chapter content this LabelData is labelling.
 */
export interface LabelData {
  chapterContentId: string;
  labelDataId: string;
  labelGroupId: string;
}
