/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type LabelRole = typeof LabelRole[keyof typeof LabelRole];


export const LabelRole = {
  owner: 'owner',
  viewer: 'viewer',
  editor: 'editor',
} as const;
