/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AddLabelOp } from './addLabelOp';
import type { DeleteLabelOp } from './deleteLabelOp';
import type { UpdateLabelOp } from './updateLabelOp';

export type LabelOp = AddLabelOp | DeleteLabelOp | UpdateLabelOp;
