/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a label group.
 *
 * Attributes:
 *     label_group_id: UUID identifier for this label group.
 *     label_group_name: Name of this label group.
 *     novel_id: UUID of novel this label group belongs to.
 */
export interface LabelGroup {
  labelGroupId: string;
  /** @maxLength 31 */
  labelGroupName: string;
  novelId: string;
}
