/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LabelGroup } from './labelGroup';
import type { LabelRole } from './labelRole';

/**
 * Pydantic schema for a label group with a user's role in that label group.
 *
 * Attributes:
 *     label_group: LabelGroup object.
 *     role: Role of the user in this label group.
 */
export interface LabelGroupWithRole {
  labelGroup: LabelGroup;
  role: LabelRole;
}
