/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LabelRef } from './labelRef';
import type { LabelRefDataType } from './labelRefDataType';

export interface LabelRefData {
  kind?: 'value';
  type: LabelRefDataType;
  value: LabelRef;
}
