/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type LabelRefDataType = typeof LabelRefDataType[keyof typeof LabelRefDataType];


export const LabelRefDataType = {
  labelRef: 'labelRef',
} as const;
