/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type LabelRefFieldType = typeof LabelRefFieldType[keyof typeof LabelRefFieldType];


export const LabelRefFieldType = {
  labelRef: 'labelRef',
} as const;
