/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LabelRole } from './labelRole';

/**
 * Pydantic schema for a label contributor, which can be either a user or an autolabel model.
 *
 * Attributes:
 *     label_contributor_role: Role of the contributor, either a user or an autolabel model.
 *     label_group_id: UUID of label group this contributor belongs to.
 *     user_id: UUID of user
 */
export interface LabelContributor {
  labelContributorRole: LabelRole;
  labelGroupId: string;
  userId: string;
}
