/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for language.
 *
 * Attributes:
 *     language_code: String code key to language.
 *     language_name: String name of language.
 */
export interface Language {
  languageCode: string;
  languageName: string;
}
