/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LabelData } from './labelData';
import type { LabelGroup } from './labelGroup';

export interface LazyEntry {
  labelData: LabelData;
  labelGroup: LabelGroup;
}
