/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BoolData } from './boolData';
import type { FloatData } from './floatData';
import type { IntDataInput } from './intDataInput';
import type { StringData } from './stringData';

export type MDataType = StringData | IntDataInput | FloatData | BoolData;
