/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BoolData } from './boolData';
import type { FloatData } from './floatData';
import type { IntData } from './intData';
import type { StringData } from './stringData';

export type MDataType = StringData | IntData | FloatData | BoolData;
