/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * The type of a memory.
 *
 * FACT: Memory about a specific fact or piece of information.
 * EVENT: Memory about a specific event or occurrence.
 * DEFINITION: Long-term memory about a specific definition or concept.
 * RELATION: Long-term memory about a relationship between glossary terms.
 */
export type MemoryType = typeof MemoryType[keyof typeof MemoryType];


export const MemoryType = {
  fact: 'fact',
  event: 'event',
  def: 'def',
  rel: 'rel',
} as const;
