/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Creator } from './creator';
import type { MemoryType } from './memoryType';
import type { PluginName } from './pluginName';
import type { ReviewStatus } from './reviewStatus';

/**
 * Memory schema
 */
export interface Memory {
  /** Type of entity that created the memory: a human, an AI agent, or a workflow. */
  creatorType: Creator;
  /** The contextual information that should inform glossary maintenance and novel continuity. */
  memoryContent: string;
  /** Exclusive ending chapter number stored by the database, or null when the memory does not expire. */
  memoryEndNum: number | null;
  /** Stable identifier to use when superseding, expiring, or otherwise referring to this memory. */
  memoryId: string;
  /** Human-review state of the memory. Pending memories are unverified; approved memories are verified. */
  memoryReviewStatus: ReviewStatus;
  /** First chapter number for which this memory is applicable; larger values indicate newer information. */
  memoryStartNum: number;
  /** Kind of information stored: a fact, event, definition, or relation. */
  memoryType: MemoryType;
  /** Name of the plugin that owns the memory. */
  pluginName: PluginName;
  /** Identifier of the memory that this memory supersedes, or null when this memory is not a superseding memory. */
  supersedesMemoryId: string | null;
}
