/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface MemoryChapterTaskCounts {
  /** @minimum 0 */
  completed: number;
  /** @minimum 0 */
  failed: number;
  /** @minimum 0 */
  pending: number;
  /** @minimum 0 */
  processing: number;
}
