/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ModelName } from './modelName';

export interface MemoryAgentModelOption {
  description: string;
  label: string;
  name: ModelName;
}
