/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryJobSummary } from './memoryJobSummary';

export interface MemoryJobSummarySnapshot {
  serverTime: string;
  summary: MemoryJobSummary;
}
