/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Memory } from './memory';

export interface MemoryPage {
  /** @minimum 0 */
  count: number;
  rows: Memory[];
}
