/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { JobParams } from './jobParams';

export interface MemoryJob {
  claimExpiresAt: string | null;
  createdAt: string;
  jobParams: JobParams;
  memoryGroupId: string;
  memoryJobId: string;
  updatedAt: string;
}
