/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ModelNameOutput = typeof ModelNameOutput[keyof typeof ModelNameOutput];


export const ModelNameOutput = {
  'deepseek:deepseek-v4-flash-none': 'deepseek:deepseek-v4-flash-none',
  'deepseek:deepseek-v4-flash-low': 'deepseek:deepseek-v4-flash-low',
} as const;
