/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type NewBoolFieldRequestType = typeof NewBoolFieldRequestType[keyof typeof NewBoolFieldRequestType];


export const NewBoolFieldRequestType = {
  bool: 'bool',
} as const;
