/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type NewFloatFieldRequestType = typeof NewFloatFieldRequestType[keyof typeof NewFloatFieldRequestType];


export const NewFloatFieldRequestType = {
  float: 'float',
} as const;
