/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewBoolFieldRequest } from './newBoolFieldRequest';
import type { NewFloatFieldRequest } from './newFloatFieldRequest';
import type { NewIntFieldRequest } from './newIntFieldRequest';
import type { NewStringFieldRequest } from './newStringFieldRequest';

export type NewFieldRequest = NewStringFieldRequest | NewIntFieldRequest | NewFloatFieldRequest | NewBoolFieldRequest;
