/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type NewIntFieldRequestType = typeof NewIntFieldRequestType[keyof typeof NewIntFieldRequestType];


export const NewIntFieldRequestType = {
  int: 'int',
} as const;
