/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewStringFieldRequestType } from './newStringFieldRequestType';

export interface NewStringFieldRequest {
  defaultValue?: string;
  type: NewStringFieldRequestType;
}
