/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type NewStringFieldRequestType = typeof NewStringFieldRequestType[keyof typeof NewStringFieldRequestType];


export const NewStringFieldRequestType = {
  string: 'string',
} as const;
