/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

/**
 * Pydantic schema for a novel contributor.
 *
 * Attributes:
 *     user_id: UUID of the user.
 *     novel_id: UUID of the novel.
 *     contributor_role: Role of the user in the novel.
 */
export interface NovelContributor {
  contributorRole: Role;
  novelId: string;
  userId: string;
}
