/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type NovelType = typeof NovelType[keyof typeof NovelType];


export const NovelType = {
  original: 'original',
  translation: 'translation',
  other: 'other',
} as const;
