/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Novel } from './novel';
import type { NovelContributor } from './novelContributor';

/**
 * Pydantic schema for novel and its associated users.
 *
 * Attributes:
 *     novel: The novel metadata.
 *     users: A list of users associated with this novel.
 */
export interface NovelAndUsers {
  novel: Novel;
  users: NovelContributor[];
}
