/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OperationStatusStatus } from './operationStatusStatus';

/**
 * Pydantic model to signal return status of operation.
 *
 * Attributes:
 *     status: One of "success", "fail".
 *     detail: Details on operation.
 *
 * Notes:
 *     Unless under exceptional circumstances, should not return fail and just raise an exception.
 */
export interface OperationStatus {
  detail?: string | null;
  status: OperationStatusStatus;
}
