/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type OperationStatusStatus = typeof OperationStatusStatus[keyof typeof OperationStatusStatus];


export const OperationStatusStatus = {
  success: 'success',
  fail: 'fail',
} as const;
