/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OpResult } from './opResult';

/**
 * Pydantic schema for a list of label operation results.
 *
 * Attributes:
 *     results: A list of UUIDs corresponding to the results of each label operation.
 */
export interface OpsResult {
  results: OpResult[];
}
