/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryChapterTask } from './memoryChapterTask';

export interface PageMemoryChapterTask {
  /** @minimum 0 */
  count: number;
  rows: MemoryChapterTask[];
}
