/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryTerm } from './glossaryTerm';

export interface PageGlossaryTerm {
  /** @minimum 0 */
  count: number;
  rows: GlossaryTerm[];
}
