/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryTermSummary } from './glossaryTermSummary';

export interface PageGlossaryTermSummary {
  /** @minimum 0 */
  count: number;
  rows: GlossaryTermSummary[];
}
