/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GlossaryMemory } from './glossaryMemory';

export interface PageGlossaryMemory {
  /** @minimum 0 */
  count: number;
  rows: GlossaryMemory[];
}
