/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type PluginName = typeof PluginName[keyof typeof PluginName];


export const PluginName = {
  glossary: 'glossary',
  continuity: 'continuity',
} as const;
