/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type PruneMemoriesStageCreateAction = typeof PruneMemoriesStageCreateAction[keyof typeof PruneMemoriesStageCreateAction];


export const PruneMemoriesStageCreateAction = {
  prune_memories: 'prune_memories',
} as const;
