/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { PruneMemoriesConfig } from './pruneMemoriesConfig';
import type { PruneMemoriesStageCreateAction } from './pruneMemoriesStageCreateAction';

export interface PruneMemoriesStageCreate {
  action: PruneMemoriesStageCreateAction;
  config: PruneMemoriesConfig;
}
