/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryType } from './memoryType';
import type { PluginName } from './pluginName';
import type { SrcTranslationsTypesModelName } from './srcTranslationsTypesModelName';

export interface PruneMemoriesConfig {
  excludeCurrentChapter?: boolean;
  instructions?: string;
  maxOutputTokens?: number | null;
  memoryGroupId?: string | null;
  memoryTypes?: MemoryType[] | null;
  model: SrcTranslationsTypesModelName;
  pluginNames?: PluginName[] | null;
  temperature?: number | null;
}
