/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NewFieldRequest } from './newFieldRequest';

export type PythonAnnotationRequestNewFields = {[key: string]: NewFieldRequest};
