/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PythonLabelSourceRequest {
  /** Label group whose current labels will seed the workflow. */
  labelGroupId: string;
  outputName?: string | null;
}
