/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface PythonMapRequest {
  /** Saved object-to-object function to execute. */
  functionDefinitionId: string;
  outputName?: string | null;
  /** Completed workflow whose instances will be mapped. */
  sourceWorkflowId: string;
}
