/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { WorkflowStatus } from './workflowStatus';
import type { WorkflowUseCase } from './workflowUseCase';

export type ReadWorkflowsFiltersWorkflowsGetParams = {
novelId?: string | null;
labelGroupId?: string | null;
useCase?: WorkflowUseCase | null;
status?: WorkflowStatus | null;
search?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string | null;
};
