/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewStatus } from './reviewStatus';

export type ReadGlossaryTermsMemoryGroupsMemoryGroupIdGlossaryTermsGetParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
chapterId?: string | null;
search?: string | null;
reviewStatuses?: ReviewStatus[] | null;
};
