/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaInfo } from './schemaInfo';

export type ReadFilterSchemasFiltersSchemasGet200 = {[key: string]: SchemaInfo};
