/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadChaptersByNovelChaptersGetParams = {
novelId: string;
start?: number | null;
end?: number | null;
};
