/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MemoryType } from './memoryType';
import type { PluginName } from './pluginName';

export type ReadMemoriesAtChapterMemoryGroupsMemoryGroupIdChaptersChapterIdMemoriesGetParams = {
/**
 * @minimum 0
 */
skip?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
createdExactlyAtChapter?: boolean;
pluginNames?: PluginName[] | null;
memoryTypes?: MemoryType[] | null;
};
