/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadEditChapterDataEditChapterDataChapterIdGetParams = {
/**
 * List of label group IDs for which to fetch eager label data
 */
eager: string[];
subjectId?: string | null;
};
