/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadFunctionsFiltersFunctionsGetParams = {
search?: string | null;
namespace?: string | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string | null;
};
