/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadLabelDatasByGroupChaptersLabelDatasGetParams = {
labelGroupId: string;
start?: number | null;
end?: number | null;
};
