/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { GroupingStatus } from './groupingStatus';

export type ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetParams = {
status?: GroupingStatus | null;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
cursor?: string | null;
};
