/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Structured detail payload used by request-key wrapped 409 responses.
 *
 * Attributes:
 *     detail: Human-readable description of the error.
 *     cache_conflict: Whether the failure was caused by a request-key cache conflict.
 */
export interface RequestConflictDetail {
  cacheConflict: boolean;
  detail: string;
}
