/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SchemaFieldObj = typeof SchemaFieldObj[keyof typeof SchemaFieldObj];


export const SchemaFieldObj = {
  False: 'False',
} as const;
