/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaFields } from './schemaFields';
import type { SchemaKind } from './schemaKind';

export interface Schema {
  fields?: SchemaFields;
  kind: SchemaKind;
}
