/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaFields } from './schemaFields';

export interface Schema {
  fields?: SchemaFields;
  obj: false;
}
