/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SchemaField } from './schemaField';

export type SchemaFields = {[key: string]: SchemaField};
