/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SObj } from './sObj';

/**
 * The input and output schemas of a function.
 */
export interface Signature {
  args?: SObj[];
  output: SObj;
}
