/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Schema } from './schema';
import type { SchemaField } from './schemaField';

export type SObj = Schema | SchemaField;
