/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { FieldName } from './fieldName';
import type { SortDirection } from './sortDirection';

export interface SortKey {
  direction: SortDirection;
  fieldName: FieldName;
}
