/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SortDirection = typeof SortDirection[keyof typeof SortDirection];


export const SortDirection = {
  asc: 'asc',
  desc: 'desc',
} as const;
