/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Novel } from './novel';
import type { SourceWork } from './sourceWork';

/**
 * Pydantic schema to represent a source work and all its associated novels.
 *
 * Attributes:
 *     source_work: The source work metadata.
 *     novels: A list of novels associated with this source work.
 */
export interface SourceWorkDataOutput {
  novels: Novel[];
  sourceWork: SourceWork;
}
