/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SrcTranslationsTypesModelName = typeof SrcTranslationsTypesModelName[keyof typeof SrcTranslationsTypesModelName];


export const SrcTranslationsTypesModelName = {
  'qwen-plus': 'qwen-plus',
  'qwen-flash': 'qwen-flash',
} as const;
