/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StringFieldType } from './stringFieldType';

export interface StringField {
  kind?: 'field';
  mutable?: boolean;
  type: StringFieldType;
}
