/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StringDataType } from './stringDataType';
import type { StringValue } from './stringValue';

export interface StringData {
  obj?: false;
  type: StringDataType;
  value: StringValue;
}
