/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StringDataType } from './stringDataType';
import type { StringValue } from './stringValue';

export interface StringData {
  kind?: 'value';
  type: StringDataType;
  value: StringValue;
}
