/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StringFieldType = typeof StringFieldType[keyof typeof StringFieldType];


export const StringFieldType = {
  string: 'string',
} as const;
