/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TermKind = typeof TermKind[keyof typeof TermKind];


export const TermKind = {
  person: 'person',
  place: 'place',
  organization: 'organization',
  technique: 'technique',
  item: 'item',
  concept: 'concept',
  title: 'title',
  species: 'species',
  other: 'other',
} as const;
