/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { NonNegativeIntegerValue } from './nonNegativeIntegerValue';

export interface TextSpan {
  chapterContentId: string;
  chapterId: string;
  end: NonNegativeIntegerValue;
  start: NonNegativeIntegerValue;
}
