/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TextOpOp = typeof TextOpOp[keyof typeof TextOpOp];


export const TextOpOp = {
  insert: 'insert',
  delete: 'delete',
} as const;
