/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SrcFiltersDataTypesIntegerValue2 } from './srcFiltersDataTypesIntegerValue2';

export interface TextSpan {
  chapterContentId: string;
  chapterId: string;
  end: SrcFiltersDataTypesIntegerValue2;
  start: SrcFiltersDataTypesIntegerValue2;
}
