/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TextSpan } from './textSpan';
import type { TextSpanDataType } from './textSpanDataType';

export interface TextSpanData {
  obj?: false;
  type: TextSpanDataType;
  value: TextSpan;
}
