/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TextSpanFieldType = typeof TextSpanFieldType[keyof typeof TextSpanFieldType];


export const TextSpanFieldType = {
  textSpan: 'textSpan',
} as const;
