/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TextSpan } from './textSpan';
import type { TextSpanDataType } from './textSpanDataType';

export interface TextSpanData {
  kind?: 'value';
  type: TextSpanDataType;
  value: TextSpan;
}
