/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TextOpOp } from './textOpOp';

/**
 * Pydantic schema to update text content of a chapter.
 *
 * Attributes:
 *     op: The text operation, either "insert" or "delete".
 *     start: The starting index in the text content where the operation should be applied.
 *     text: The text to insert (for insert operations) or the text to delete (for delete operations).
 */
export interface TextOp {
  op: TextOpOp;
  start: number;
  text: string;
}
