/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TextSpanFieldType } from './textSpanFieldType';

export interface TextSpanField {
  kind?: 'field';
  mutable?: false;
  type: TextSpanFieldType;
}
