/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TextSpanDataType = typeof TextSpanDataType[keyof typeof TextSpanDataType];


export const TextSpanDataType = {
  textSpan: 'textSpan',
} as const;
