/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a JWT
 *
 * Attributes:
 *     access_token: Payload.
 *     token_type: Type of token.
 */
export interface Token {
  access_token: string;
  token_type: string;
}
