/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ToolsetName = typeof ToolsetName[keyof typeof ToolsetName];


export const ToolsetName = {
  glossary_terms: 'glossary_terms',
  glossary_definitions_read: 'glossary_definitions_read',
  glossary_definitions_write: 'glossary_definitions_write',
  glossary_relations_read: 'glossary_relations_read',
  glossary_relations_write: 'glossary_relations_write',
  glossary_facts_read: 'glossary_facts_read',
  glossary_facts_write: 'glossary_facts_write',
  glossary_gender_read: 'glossary_gender_read',
  glossary_gender_write: 'glossary_gender_write',
  glossary_gender_advanced_facts_read: 'glossary_gender_advanced_facts_read',
  glossary_gender_advanced_facts_write: 'glossary_gender_advanced_facts_write',
  glossary_events_read: 'glossary_events_read',
  glossary_events_write: 'glossary_events_write',
  glossary_gender_advanced_events_read: 'glossary_gender_advanced_events_read',
  glossary_gender_advanced_events_write: 'glossary_gender_advanced_events_write',
  glossary_gender_transformation: 'glossary_gender_transformation',
  glossary_cultivation: 'glossary_cultivation',
  glossary_system: 'glossary_system',
  glossary_artifacts: 'glossary_artifacts',
} as const;
