/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ToolsetName = typeof ToolsetName[keyof typeof ToolsetName];


export const ToolsetName = {
  glossary_terms: 'glossary_terms',
  glossary_definitions: 'glossary_definitions',
  glossary_relations: 'glossary_relations',
  glossary_facts: 'glossary_facts',
  glossary_events: 'glossary_events',
  glossary_gender: 'glossary_gender',
  glossary_gender_transformation: 'glossary_gender_transformation',
  glossary_cultivation: 'glossary_cultivation',
  glossary_system: 'glossary_system',
  glossary_artifacts: 'glossary_artifacts',
} as const;
