/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ToolsetKind = typeof ToolsetKind[keyof typeof ToolsetKind];


export const ToolsetKind = {
  memory: 'memory',
  guidance: 'guidance',
} as const;
