/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationBatchRead } from './translationBatchRead';
import type { TranslationJobReadConfig } from './translationJobReadConfig';
import type { TranslationStageRead } from './translationStageRead';
import type { TranslationTaskRead } from './translationTaskRead';

export interface TranslationJobRead {
  batches: TranslationBatchRead[];
  config: TranslationJobReadConfig;
  jobId: string;
  novelId: string;
  stages: TranslationStageRead[];
  tasks: TranslationTaskRead[];
}
