/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface TranslationJobConfig {
  /** @exclusiveMinimum 0 */
  batchSize: number;
  endChapterNum?: number | null;
  startChapterNum?: number | null;
}
