/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationTaskStatus } from './translationTaskStatus';

export interface TranslationTaskRead {
  batchId: string;
  claimExpiresAt: string | null;
  error: string | null;
  failedAt: string | null;
  inputFileId: string | null;
  outputFileId: string | null;
  stageId: string;
  status: TranslationTaskStatus;
  taskId: string;
}
