/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TranslateWithMemoriesStageCreateAction = typeof TranslateWithMemoriesStageCreateAction[keyof typeof TranslateWithMemoriesStageCreateAction];


export const TranslateWithMemoriesStageCreateAction = {
  translate_with_memories: 'translate_with_memories',
} as const;
