/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslationStageReadConfig } from './translationStageReadConfig';

export interface TranslationStageRead {
  action: string;
  config: TranslationStageReadConfig;
  stageId: string;
  stageNum: number;
}
