/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CombineChapterStageCreate } from './combineChapterStageCreate';
import type { PruneMemoriesStageCreate } from './pruneMemoriesStageCreate';
import type { TranslateStageCreate } from './translateStageCreate';
import type { TranslateWithMemoriesStageCreate } from './translateWithMemoriesStageCreate';

export type TranslationStageCreate = PruneMemoriesStageCreate | CombineChapterStageCreate | TranslateWithMemoriesStageCreate | TranslateStageCreate;
