/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TranslateConfig } from './translateConfig';
import type { TranslateStageCreateAction } from './translateStageCreateAction';

export interface TranslateStageCreate {
  action: TranslateStageCreateAction;
  config: TranslateConfig;
}
