/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TranslateStageCreateAction = typeof TranslateStageCreateAction[keyof typeof TranslateStageCreateAction];


export const TranslateStageCreateAction = {
  translate: 'translate',
} as const;
