/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TextOp } from './textOp';

/**
 * Pydantic schema to validate data for updating the text content of a chapter. The chapter_id is expected to be passed via the URL path.
 *
 * Attributes:
 *     text_ops: A list of text operations (insertions or deletions) to apply to the existing text content.
 *     chapter_content_id: The UUID of the text content, used for optimistic concurrency control when updating text.
 */
export interface UpdateChapterContent {
  chapterContentId: string;
  textOps: TextOp[];
}
