/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateLabelOpOp } from './updateLabelOpOp';

/**
 * Pydantic schema for a label update operation. Partial updates performed on label with label_id.
 *
 * Attributes:
 *     op: The string literal 'update'.
 *     label_id: ID of the label to update.
 *     start_pos: Optional parameter. The new start position of the label.
 *     end_pos: Optional parameter. The new end position of the label.
 *     dirty: Optional parameter. Value to change the current label's dirty value to.
 *     entity_group: Optional parameter. New entity group for this label.
 *     score: Optional parameter. New score for the entity.
 */
export interface UpdateLabelOp {
  dirty?: boolean | null;
  endPos?: number | null;
  entityGroup?: string | null;
  labelId: string;
  op: UpdateLabelOpOp;
  score?: number | null;
  startPos?: number | null;
}
