/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema to validate data for updating chapter metadata.
 *
 * Attributes:
 *     chapter_title: The new title for the chapter.
 */
export interface UpdateChapter {
  chapterTitle: string;
}
