/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateGlossaryTerm {
  /**
     * @minLength 1
     * @maxLength 100
     */
  term: string;
}
