/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Pydantic schema for a label update operation. Inherits all attributes from LabelOpBase.
 *
 * Attributes:
 *     op: The string literal 'update'.
 *     new_start_pos: Optional parameter. The new start position of the label.
 *     new_end_pos: Optional parameter. The new end position of the label.
 *     new_word: Optional parameter. The new word the label is labelling. Must satisfy `new_word == chapter_text[new_start_pos : new_end_pos]`.
 *     dirty: Optional parameter. Value to change the current label's dirty value to.
 *     entity_group: Optional parameter. New entity group for this label.
 *     score: Optional parameter. New score for the entity.
 */
export interface UpdateLabelOp {
  dirty?: boolean | null;
  /** @minimum 0 */
  endPos: number;
  entityGroup?: string | null;
  newEndPos?: number | null;
  newStartPos?: number | null;
  newWord?: string | null;
  op: 'update';
  score?: number | null;
  /** @minimum 0 */
  startPos: number;
  /** @maxLength 128 */
  word: string;
}
