/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewStatus } from './reviewStatus';

export interface UpdateReviewStatus {
  reviewStatus: ReviewStatus;
}
