/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type UpdateLabelOpOp = typeof UpdateLabelOpOp[keyof typeof UpdateLabelOpOp];


export const UpdateLabelOpOp = {
  update: 'update',
} as const;
