/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LabelOp } from './labelOp';

/**
 * Pydantic schema for an atomic stream of label operations.
 *
 * Attributes:
 *     ops: A list of label operations.
 */
export interface UpdateLabelDataStream {
  ops: LabelOp[];
}
