/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateMemoryContent {
  mark: string | null;
  /** @minLength 1 */
  memoryContent: string;
}
