/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserType } from './userType';

/**
 * Pydantic model for user information.
 *
 * Attributes:
 *     user_id: id of this user.
 *     user_name: Username for this user.
 *     user_type: A value in UserType (e.g. 'admin', or 'user')
 */
export interface User {
  userId: string;
  userName: string;
  userType: UserType;
}
