/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

/**
 * Enum of possible user types.
 */
export type UserType = typeof UserType[keyof typeof UserType];


export const UserType = {
  user: 'user',
  admin: 'admin',
} as const;
