/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type WorkflowUseCase = typeof WorkflowUseCase[keyof typeof WorkflowUseCase];


export const WorkflowUseCase = {
  advanced: 'advanced',
  glossary: 'glossary',
} as const;
