/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { WorkflowResponse } from './workflowResponse';

export interface WorkflowOperationAccepted {
  jobId: string;
  workflow: WorkflowResponse;
}
