/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type WorkflowStatus = typeof WorkflowStatus[keyof typeof WorkflowStatus];


export const WorkflowStatus = {
  new: 'new',
  pending: 'pending',
  processing: 'processing',
  complete: 'complete',
  failed: 'failed',
} as const;
