/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  HTTPValidationError,
  TranslationControlResult,
  TranslationJobCreate,
  TranslationJobCreated,
  TranslationJobRead
} from '../../models';

import { customFetch } from '../../custom-fetch';

export type createTranslationJobsPostResponse201 = {
  data: TranslationJobCreated
  status: 201
}

export type createTranslationJobsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createTranslationJobsPostResponseSuccess = (createTranslationJobsPostResponse201) & {
  headers: Headers;
};
export type createTranslationJobsPostResponseError = (createTranslationJobsPostResponse422) & {
  headers: Headers;
};

export type createTranslationJobsPostResponse = (createTranslationJobsPostResponseSuccess | createTranslationJobsPostResponseError)

export const getCreateTranslationJobsPostUrl = () => {




  return `/api/translation-jobs`
}

/**
 * @summary Create
 */
export const createTranslationJobsPost = async (translationJobCreate: TranslationJobCreate, options?: Parameters<typeof customFetch>[1]): Promise<createTranslationJobsPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<createTranslationJobsPostResponse>(getCreateTranslationJobsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(translationJobCreate)
  }
);}


export type readTranslationJobsJobIdGetResponse200 = {
  data: TranslationJobRead
  status: 200
}

export type readTranslationJobsJobIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readTranslationJobsJobIdGetResponseSuccess = (readTranslationJobsJobIdGetResponse200) & {
  headers: Headers;
};
export type readTranslationJobsJobIdGetResponseError = (readTranslationJobsJobIdGetResponse422) & {
  headers: Headers;
};

export type readTranslationJobsJobIdGetResponse = (readTranslationJobsJobIdGetResponseSuccess | readTranslationJobsJobIdGetResponseError)

export const getReadTranslationJobsJobIdGetUrl = (jobId: string,) => {




  return `/api/translation-jobs/${jobId}`
}

/**
 * @summary Read
 */
export const readTranslationJobsJobIdGet = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<readTranslationJobsJobIdGetResponse> => {

  return customFetch<readTranslationJobsJobIdGetResponse>(getReadTranslationJobsJobIdGetUrl(jobId),
  {
    ...options,
    method: 'GET'


  }
);}


export type cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponseSuccess = (cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse200) & {
  headers: Headers;
};
export type cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponseError = (cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse422) & {
  headers: Headers;
};

export type cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse = (cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponseSuccess | cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponseError)

export const getCancelTranslationJobsJobIdBatchesBatchIdCancelPostUrl = (jobId: string,
    batchId: string,) => {




  return `/api/translation-jobs/${jobId}/batches/${batchId}/cancel`
}

/**
 * @summary Cancel
 */
export const cancelTranslationJobsJobIdBatchesBatchIdCancelPost = async (jobId: string,
    batchId: string, options?: Parameters<typeof customFetch>[1]): Promise<cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse> => {

  return customFetch<cancelTranslationJobsJobIdBatchesBatchIdCancelPostResponse>(getCancelTranslationJobsJobIdBatchesBatchIdCancelPostUrl(jobId,batchId),
  {
    ...options,
    method: 'POST'


  }
);}


export type retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type retryTranslationJobsJobIdBatchesBatchIdRetryPostResponseSuccess = (retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse200) & {
  headers: Headers;
};
export type retryTranslationJobsJobIdBatchesBatchIdRetryPostResponseError = (retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse422) & {
  headers: Headers;
};

export type retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse = (retryTranslationJobsJobIdBatchesBatchIdRetryPostResponseSuccess | retryTranslationJobsJobIdBatchesBatchIdRetryPostResponseError)

export const getRetryTranslationJobsJobIdBatchesBatchIdRetryPostUrl = (jobId: string,
    batchId: string,) => {




  return `/api/translation-jobs/${jobId}/batches/${batchId}/retry`
}

/**
 * @summary Retry
 */
export const retryTranslationJobsJobIdBatchesBatchIdRetryPost = async (jobId: string,
    batchId: string, options?: Parameters<typeof customFetch>[1]): Promise<retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse> => {

  return customFetch<retryTranslationJobsJobIdBatchesBatchIdRetryPostResponse>(getRetryTranslationJobsJobIdBatchesBatchIdRetryPostUrl(jobId,batchId),
  {
    ...options,
    method: 'POST'


  }
);}


export type cancelAllTranslationJobsJobIdCancelAllPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type cancelAllTranslationJobsJobIdCancelAllPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type cancelAllTranslationJobsJobIdCancelAllPostResponseSuccess = (cancelAllTranslationJobsJobIdCancelAllPostResponse200) & {
  headers: Headers;
};
export type cancelAllTranslationJobsJobIdCancelAllPostResponseError = (cancelAllTranslationJobsJobIdCancelAllPostResponse422) & {
  headers: Headers;
};

export type cancelAllTranslationJobsJobIdCancelAllPostResponse = (cancelAllTranslationJobsJobIdCancelAllPostResponseSuccess | cancelAllTranslationJobsJobIdCancelAllPostResponseError)

export const getCancelAllTranslationJobsJobIdCancelAllPostUrl = (jobId: string,) => {




  return `/api/translation-jobs/${jobId}/cancel-all`
}

/**
 * @summary Cancel All
 */
export const cancelAllTranslationJobsJobIdCancelAllPost = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<cancelAllTranslationJobsJobIdCancelAllPostResponse> => {

  return customFetch<cancelAllTranslationJobsJobIdCancelAllPostResponse>(getCancelAllTranslationJobsJobIdCancelAllPostUrl(jobId),
  {
    ...options,
    method: 'POST'


  }
);}


export type resumeAllTranslationJobsJobIdResumeAllPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type resumeAllTranslationJobsJobIdResumeAllPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type resumeAllTranslationJobsJobIdResumeAllPostResponseSuccess = (resumeAllTranslationJobsJobIdResumeAllPostResponse200) & {
  headers: Headers;
};
export type resumeAllTranslationJobsJobIdResumeAllPostResponseError = (resumeAllTranslationJobsJobIdResumeAllPostResponse422) & {
  headers: Headers;
};

export type resumeAllTranslationJobsJobIdResumeAllPostResponse = (resumeAllTranslationJobsJobIdResumeAllPostResponseSuccess | resumeAllTranslationJobsJobIdResumeAllPostResponseError)

export const getResumeAllTranslationJobsJobIdResumeAllPostUrl = (jobId: string,) => {




  return `/api/translation-jobs/${jobId}/resume-all`
}

/**
 * @summary Resume All
 */
export const resumeAllTranslationJobsJobIdResumeAllPost = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<resumeAllTranslationJobsJobIdResumeAllPostResponse> => {

  return customFetch<resumeAllTranslationJobsJobIdResumeAllPostResponse>(getResumeAllTranslationJobsJobIdResumeAllPostUrl(jobId),
  {
    ...options,
    method: 'POST'


  }
);}


export type retryAllTranslationJobsJobIdRetryAllPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type retryAllTranslationJobsJobIdRetryAllPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type retryAllTranslationJobsJobIdRetryAllPostResponseSuccess = (retryAllTranslationJobsJobIdRetryAllPostResponse200) & {
  headers: Headers;
};
export type retryAllTranslationJobsJobIdRetryAllPostResponseError = (retryAllTranslationJobsJobIdRetryAllPostResponse422) & {
  headers: Headers;
};

export type retryAllTranslationJobsJobIdRetryAllPostResponse = (retryAllTranslationJobsJobIdRetryAllPostResponseSuccess | retryAllTranslationJobsJobIdRetryAllPostResponseError)

export const getRetryAllTranslationJobsJobIdRetryAllPostUrl = (jobId: string,) => {




  return `/api/translation-jobs/${jobId}/retry-all`
}

/**
 * @summary Retry All
 */
export const retryAllTranslationJobsJobIdRetryAllPost = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<retryAllTranslationJobsJobIdRetryAllPostResponse> => {

  return customFetch<retryAllTranslationJobsJobIdRetryAllPostResponse>(getRetryAllTranslationJobsJobIdRetryAllPostUrl(jobId),
  {
    ...options,
    method: 'POST'


  }
);}


export type startTranslationJobsJobIdStartPostResponse200 = {
  data: TranslationControlResult
  status: 200
}

export type startTranslationJobsJobIdStartPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type startTranslationJobsJobIdStartPostResponseSuccess = (startTranslationJobsJobIdStartPostResponse200) & {
  headers: Headers;
};
export type startTranslationJobsJobIdStartPostResponseError = (startTranslationJobsJobIdStartPostResponse422) & {
  headers: Headers;
};

export type startTranslationJobsJobIdStartPostResponse = (startTranslationJobsJobIdStartPostResponseSuccess | startTranslationJobsJobIdStartPostResponseError)

export const getStartTranslationJobsJobIdStartPostUrl = (jobId: string,) => {




  return `/api/translation-jobs/${jobId}/start`
}

/**
 * @summary Start
 */
export const startTranslationJobsJobIdStartPost = async (jobId: string, options?: Parameters<typeof customFetch>[1]): Promise<startTranslationJobsJobIdStartPostResponse> => {

  return customFetch<startTranslationJobsJobIdStartPostResponse>(getStartTranslationJobsJobIdStartPostUrl(jobId),
  {
    ...options,
    method: 'POST'


  }
);}


