/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  Schema as S
} from 'effect';


/**
 * @summary Create
 */
export const createTranslationJobsPostBodyConfigBatchSizeExclusiveMin = 0;

export const createTranslationJobsPostBodyConfigEndChapterNumOneMin = 0;

export const createTranslationJobsPostBodyConfigStartChapterNumOneMin = 0;

export const createTranslationJobsPostBodyStagesMax = 5;

export const createTranslationJobsPostBodyStagesItemOneConfigExcludeCurrentChapterDefault = true;
export const createTranslationJobsPostBodyStagesItemOneConfigInstructionsDefault = '';
export const createTranslationJobsPostBodyStagesItemOneConfigMaxOutputTokensOneExclusiveMin = 0;

export const createTranslationJobsPostBodyStagesItemOneConfigTemperatureOneMin = 0;

export const createTranslationJobsPostBodyStagesItemThreeConfigExcludeCurrentChapterDefault = true;
export const createTranslationJobsPostBodyStagesItemThreeConfigInstructionsDefault = '';
export const createTranslationJobsPostBodyStagesItemThreeConfigMaxOutputTokensOneExclusiveMin = 0;

export const createTranslationJobsPostBodyStagesItemThreeConfigTargetLanguageDefault = 'English';

export const createTranslationJobsPostBodyStagesItemThreeConfigTemperatureOneMin = 0;

export const createTranslationJobsPostBodyStagesItemFourConfigInstructionsDefault = '';
export const createTranslationJobsPostBodyStagesItemFourConfigMaxOutputTokensOneExclusiveMin = 0;

export const createTranslationJobsPostBodyStagesItemFourConfigTargetLanguageDefault = 'English';

export const createTranslationJobsPostBodyStagesItemFourConfigTemperatureOneMin = 0;



export const CreateTranslationJobsPostBody = S.Struct({
  "config": S.Struct({
  "batchSize": S.Number.pipe(S.greaterThan(createTranslationJobsPostBodyConfigBatchSizeExclusiveMin)),
  "endChapterNum": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(createTranslationJobsPostBodyConfigEndChapterNumOneMin)), S.Null)),
  "startChapterNum": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(createTranslationJobsPostBodyConfigStartChapterNumOneMin)), S.Null))
}),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "stages": S.Array(S.Union(S.Struct({
  "action": S.Literal('prune_memories'),
  "config": S.Struct({
  "excludeCurrentChapter": S.optionalWith(S.Boolean, { default: () => createTranslationJobsPostBodyStagesItemOneConfigExcludeCurrentChapterDefault }),
  "instructions": S.optionalWith(S.String, { default: () => createTranslationJobsPostBodyStagesItemOneConfigInstructionsDefault }),
  "maxOutputTokens": S.optional(S.Union(S.Number.pipe(S.greaterThan(createTranslationJobsPostBodyStagesItemOneConfigMaxOutputTokensOneExclusiveMin)), S.Null)),
  "memoryGroupId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)),
  "memoryTypes": S.optional(S.Union(S.Array(S.Literal('fact', 'event', 'def', 'rel', 'summary').annotations({ description: 'The type of a memory.\n\nFACT: Memory about a specific fact or piece of information.\nEVENT: Memory about a specific event or occurrence.\nDEFINITION: Long-term memory about a specific definition or concept.\nRELATION: Long-term memory about a relationship between glossary terms.' })), S.Null)),
  "model": S.Literal('qwen-plus', 'qwen-flash'),
  "pluginNames": S.optional(S.Union(S.Array(S.Literal('glossary', 'continuity')), S.Null)),
  "temperature": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(createTranslationJobsPostBodyStagesItemOneConfigTemperatureOneMin)), S.Null))
})
}), S.Struct({
  "action": S.Literal('combine_chapter'),
  "config": S.optional(S.Record({ key: S.String, value: S.Unknown }))
}), S.Struct({
  "action": S.Literal('translate_with_memories'),
  "config": S.Struct({
  "excludeCurrentChapter": S.optionalWith(S.Boolean, { default: () => createTranslationJobsPostBodyStagesItemThreeConfigExcludeCurrentChapterDefault }),
  "instructions": S.optionalWith(S.String, { default: () => createTranslationJobsPostBodyStagesItemThreeConfigInstructionsDefault }),
  "maxOutputTokens": S.optional(S.Union(S.Number.pipe(S.greaterThan(createTranslationJobsPostBodyStagesItemThreeConfigMaxOutputTokensOneExclusiveMin)), S.Null)),
  "memoryGroupId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)),
  "memoryTypes": S.optional(S.Union(S.Array(S.Literal('fact', 'event', 'def', 'rel', 'summary').annotations({ description: 'The type of a memory.\n\nFACT: Memory about a specific fact or piece of information.\nEVENT: Memory about a specific event or occurrence.\nDEFINITION: Long-term memory about a specific definition or concept.\nRELATION: Long-term memory about a relationship between glossary terms.' })), S.Null)),
  "model": S.Literal('qwen-plus', 'qwen-flash'),
  "pluginNames": S.optional(S.Union(S.Array(S.Literal('glossary', 'continuity')), S.Null)),
  "targetLanguage": S.optionalWith(S.String.pipe(S.minLength(1)), { default: () => createTranslationJobsPostBodyStagesItemThreeConfigTargetLanguageDefault }),
  "temperature": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(createTranslationJobsPostBodyStagesItemThreeConfigTemperatureOneMin)), S.Null))
})
}), S.Struct({
  "action": S.Literal('translate'),
  "config": S.Struct({
  "instructions": S.optionalWith(S.String, { default: () => createTranslationJobsPostBodyStagesItemFourConfigInstructionsDefault }),
  "maxOutputTokens": S.optional(S.Union(S.Number.pipe(S.greaterThan(createTranslationJobsPostBodyStagesItemFourConfigMaxOutputTokensOneExclusiveMin)), S.Null)),
  "model": S.Literal('qwen-plus', 'qwen-flash'),
  "targetLanguage": S.optionalWith(S.String.pipe(S.minLength(1)), { default: () => createTranslationJobsPostBodyStagesItemFourConfigTargetLanguageDefault }),
  "temperature": S.optional(S.Union(S.Number.pipe(S.greaterThanOrEqualTo(createTranslationJobsPostBodyStagesItemFourConfigTemperatureOneMin)), S.Null))
})
}))).pipe(S.minItems(1), S.maxItems(createTranslationJobsPostBodyStagesMax))
})

export const CreateTranslationJobsPost201Response = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const CreateTranslationJobsPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Read
 */
export const ReadTranslationJobsJobIdGetParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadTranslationJobsJobIdGet200Response = S.Struct({
  "batches": S.Array(S.Struct({
  "batchId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "batchNum": S.Number,
  "initialFileId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)
})),
  "config": S.Record({ key: S.String, value: S.Unknown }),
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "novelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "stages": S.Array(S.Struct({
  "action": S.String,
  "config": S.Record({ key: S.String, value: S.Unknown }),
  "stageId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "stageNum": S.Number
})),
  "tasks": S.Array(S.Struct({
  "batchId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "claimExpiresAt": S.Union(S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)), S.Null),
  "error": S.Union(S.String, S.Null),
  "failedAt": S.Union(S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)), S.Null),
  "inputFileId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "outputFileId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "stageId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "status": S.Literal('waiting', 'ready', 'preparing', 'prepared', 'submitting', 'processing', 'processed', 'finalizing', 'complete'),
  "taskId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}))
})

export const ReadTranslationJobsJobIdGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Cancel
 */
export const CancelTranslationJobsJobIdBatchesBatchIdCancelPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "batchId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const CancelTranslationJobsJobIdBatchesBatchIdCancelPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const CancelTranslationJobsJobIdBatchesBatchIdCancelPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Retry
 */
export const RetryTranslationJobsJobIdBatchesBatchIdRetryPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "batchId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const RetryTranslationJobsJobIdBatchesBatchIdRetryPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const RetryTranslationJobsJobIdBatchesBatchIdRetryPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Cancel All
 */
export const CancelAllTranslationJobsJobIdCancelAllPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const CancelAllTranslationJobsJobIdCancelAllPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const CancelAllTranslationJobsJobIdCancelAllPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Resume All
 */
export const ResumeAllTranslationJobsJobIdResumeAllPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ResumeAllTranslationJobsJobIdResumeAllPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const ResumeAllTranslationJobsJobIdResumeAllPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Retry All
 */
export const RetryAllTranslationJobsJobIdRetryAllPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const RetryAllTranslationJobsJobIdRetryAllPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const RetryAllTranslationJobsJobIdRetryAllPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * @summary Start
 */
export const StartTranslationJobsJobIdStartPostParams = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const StartTranslationJobsJobIdStartPost200Response = S.Struct({
  "affectedBatchIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchFailedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)))),
  "dispatchedTaskIds": S.optional(S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))))
})

export const StartTranslationJobsJobIdStartPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "ctx": S.optional(S.extend(S.Struct({

}), S.Record({ key: S.String, value: S.Unknown }))),
  "input": S.optional(S.Unknown),
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

