"""initial

Revision ID: 06741dac5042
Revises:
Create Date: 2026-01-15 06:13:06.660479+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src.novels.models import EnumAsInteger, Visibility

# revision identifiers, used by Alembic.
revision = '06741dac5042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language_name', sa.String(length=31), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(language_code) = 2', name='chk_language_code_length'),
    sa.PrimaryKeyConstraint('language_code'),
    sa.UniqueConstraint('language_name', name='language_name_unique')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=31), nullable=False),
    sa.Column('user_hashed_password', sa.String(length=256), nullable=False),
    sa.Column('user_type', sa.Enum('user', 'admin', name='usertype', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name', name='uq_user_name')
    )
    op.create_table('novels',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('novel_title', sa.String(length=255), nullable=False),
    sa.Column('novel_description', sa.Text(), nullable=True),
    sa.Column('novel_author', sa.String(length=31), nullable=True),
    sa.Column('novel_visibility', EnumAsInteger(Visibility), nullable=False),
    sa.Column('novel_type', sa.Enum('original', 'translation', 'other', name='noveltype', native_enum=False, length=16), nullable=False),
    sa.Column('novel_parent_id', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.language_code'], name='fk_novels_language_code_languages'),
    sa.ForeignKeyConstraint(['novel_parent_id'], ['novels.novel_id'], name='fk_novels_novel_parent_id_novels'),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('label_groups',
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('label_group_name', sa.String(length=31), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='fk_label_groups_novel_id_novels'),
    sa.PrimaryKeyConstraint('label_group_id')
    )
    op.create_table('novel_contributors',
    sa.Column('contributor_role', sa.Enum('owner', 'viewer', 'editor', name='role', native_enum=False, length=10), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'user_id'),
    )
    op.create_table('raw_chapters',
    sa.Column('raw_chapter_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_num', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='fk_raw_chapters_novel_id_novels'),
    sa.PrimaryKeyConstraint('raw_chapter_id'),
    sa.UniqueConstraint('raw_chapter_num', 'novel_id', name='raw_chapter_per_novel')
    )
    op.create_table('label_group_contributors',
    sa.Column('label_contributor_role', sa.Enum('owner', 'viewer', 'editor', name='labelrole', native_enum=False, length=10), nullable=False),
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('label_group_id', 'user_id')
    )
    op.create_table('raw_chapter_revisions',
    sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_revision_text', sa.Text(), nullable=False),
    sa.Column('raw_chapter_revision_title', sa.String(length=255), nullable=False),
    sa.Column('raw_chapter_revision_is_primary', sa.Boolean(), nullable=False),
    sa.Column('raw_chapter_revision_is_public', sa.Boolean(), nullable=False),
    sa.Column('raw_chapter_revision_is_final', sa.Boolean(), nullable=False),
    sa.Column('raw_chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('raw_chapter_revision_is_public OR NOT raw_chapter_revision_is_primary', name='primary_must_be_public_check'),
    sa.ForeignKeyConstraint(['raw_chapter_id'], ['raw_chapters.raw_chapter_id'], name='fk_raw_chapter_revisions_raw_chapter_id_raw_chapters'),
    sa.PrimaryKeyConstraint('raw_chapter_revision_id')
    )
    op.create_index('ix_one_primary_revision_per_chapter', 'raw_chapter_revisions', ['raw_chapter_id'], unique=True, postgresql_where=sa.text('raw_chapter_revision_is_primary IS true'))
    op.create_table('auto_labels',
    sa.Column('auto_label_id', sa.Integer(), nullable=False),
    sa.Column('auto_label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_label_model_name', sa.String(length=128), nullable=False),
    sa.Column('auto_label_model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_label_status', sa.Enum('failed', 'pending', 'processing', 'done', name='autolabelprogress', native_enum=False), nullable=False),
    sa.Column('auto_label_last_job_id', sa.String(length=36), nullable=True),
    sa.Column('auto_label_message', sa.Text(), nullable=True),
    sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_chapter_revision_id'], ['raw_chapter_revisions.raw_chapter_revision_id'], name='fk_auto_labels_raw_chapter_revision_id_raw_chapter_revisions'),
    sa.PrimaryKeyConstraint('auto_label_id'),
    sa.UniqueConstraint('raw_chapter_revision_id', 'auto_label_model_name', 'auto_label_model_params', name='uq_model_name_params')
    )
    op.create_table('label_datas',
    sa.Column('label_data_id', sa.Integer(), nullable=False),
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], name='fk_label_datas_label_group_id_label_groups'),
    sa.ForeignKeyConstraint(['raw_chapter_revision_id'], ['raw_chapter_revisions.raw_chapter_revision_id'], name='fk_label_datas_raw_chapter_revision_id_raw_chapter_revisions'),
    sa.PrimaryKeyConstraint('label_data_id'),
    sa.UniqueConstraint('label_group_id', 'raw_chapter_revision_id', name='one_label_group_per_chapter')
    )
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label_entity_group', sa.String(length=64), nullable=False),
    sa.Column('label_score', sa.Float(), nullable=False),
    sa.Column('label_word', sa.String(length=128), nullable=False),
    sa.Column('label_start', sa.Integer(), nullable=False),
    sa.Column('label_end', sa.Integer(), nullable=False),
    sa.Column('label_dirty', sa.Boolean(), nullable=False),
    sa.Column('label_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('label_data_id'), '='), (sa.text("int4range(label_start, label_end, '[)')"), '&&'), using='gist', name='no_overlapping_labels_per_group'),
    sa.CheckConstraint('label_score >= 0.0 AND label_score <= 1.0', name='chk_score_bounds'),
    sa.CheckConstraint('label_start < label_end', name='chk_label_start_lt_label_end'),
    sa.ForeignKeyConstraint(['label_data_id'], ['label_datas.label_data_id'], name='fk_labels_label_data_id_label_datas'),
    sa.PrimaryKeyConstraint('label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels')
    op.drop_table('label_datas')
    op.drop_table('auto_labels')
    op.drop_index('ix_one_primary_revision_per_chapter', table_name='raw_chapter_revisions', postgresql_where=sa.text('raw_chapter_revision_is_primary IS true'))
    op.drop_table('raw_chapter_revisions')
    op.drop_table('label_group_contributors')
    op.drop_table('raw_chapters')
    op.drop_table('novel_contributors')
    op.drop_table('label_groups')
    op.drop_table('novels')
    op.drop_table('users')
    op.drop_table('languages')
    op.execute('DROP EXTENSION IF EXISTS btree_gist')
    # ### end Alembic commands ###
