"""defined models

Revision ID: 0af69e401fcc
Revises:
Create Date: 2025-10-19 04:40:16.836387+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '0af69e401fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=31), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('language_id'),
    sa.UniqueConstraint('language_code', name='language_code_unique'),
    sa.UniqueConstraint('language_name', name='language_name_unique')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=31), nullable=False),
    sa.Column('user_hashed_password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('novels',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('novel_title', sa.String(length=255), nullable=False),
    sa.Column('novel_description', sa.Text(), nullable=False),
    sa.Column('novel_author', sa.String(length=31), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('label_groups',
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('label_group_name', sa.String(length=31), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('label_group_id'),
    sa.UniqueConstraint('label_group_name', 'user_id', 'novel_id', name='one_label_group_with_name_per_user_novel')
    )
    op.create_table('raw_chapters',
    sa.Column('raw_chapter_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_num', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.PrimaryKeyConstraint('raw_chapter_id'),
    sa.UniqueConstraint('raw_chapter_num', 'novel_id', name='raw_chapter_per_novel')
    )
    op.create_table('translations',
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.language_id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('translation_id')
    )
    op.create_table('label_datas',
    sa.Column('label_data_id', sa.Integer(), nullable=False),
    sa.Column('label_data_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('label_group_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], ),
    sa.ForeignKeyConstraint(['raw_chapter_id'], ['raw_chapters.raw_chapter_id'], ),
    sa.PrimaryKeyConstraint('label_data_id'),
    sa.UniqueConstraint('label_group_id', 'raw_chapter_id', name='one_label_group_per_chapter')
    )
    op.create_table('raw_chapter_revisions',
    sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False),
    sa.Column('raw_chapter_revision_text', sa.Text(), nullable=False),
    sa.Column('raw_chapter_revision_title', sa.String(length=255), nullable=False),
    sa.Column('raw_chapter_revision_is_primary', sa.Boolean(), nullable=False),
    sa.Column('raw_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_chapter_id'], ['raw_chapters.raw_chapter_id'], ),
    sa.PrimaryKeyConstraint('raw_chapter_revision_id')
    )
    op.create_index('ix_one_primary_revision_per_chapter', 'raw_chapter_revisions', ['raw_chapter_id'], unique=True, postgresql_where=sa.text('raw_chapter_revision_is_primary IS true'))
    op.create_table('translated_chapters',
    sa.Column('translated_chapter_id', sa.Integer(), nullable=False),
    sa.Column('translated_chapter_text', sa.Text(), nullable=False),
    sa.Column('translated_chapter_num', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=True),
    sa.Column('raw_chapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_chapter_id'], ['raw_chapters.raw_chapter_id'], ),
    sa.ForeignKeyConstraint(['translation_id'], ['translations.translation_id'], ),
    sa.PrimaryKeyConstraint('translated_chapter_id'),
    sa.UniqueConstraint('translation_id', 'raw_chapter_id', name='tl_chapter_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translated_chapters')
    op.drop_index('ix_one_primary_revision_per_chapter', table_name='raw_chapter_revisions', postgresql_where=sa.text('raw_chapter_revision_is_primary IS true'))
    op.drop_table('raw_chapter_revisions')
    op.drop_table('label_datas')
    op.drop_table('translations')
    op.drop_table('raw_chapters')
    op.drop_table('label_groups')
    op.drop_table('novels')
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
