"""made some thing non-nullable

Revision ID: 0d25aa6217fe
Revises: fc32f3fee87e
Create Date: 2025-11-09 21:05:20.562416+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d25aa6217fe'
down_revision = 'fc32f3fee87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_chapter_revisions', 'raw_chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('raw_chapters', 'novel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_chapters', 'novel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('raw_chapter_revisions', 'raw_chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
