"""add novel_associations table

Revision ID: 165c7fd80ea7
Revises: f2d30e8729bf
Create Date: 2026-04-02 18:12:23.416399+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "165c7fd80ea7"
down_revision = "f2d30e8729bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novel_associations",
        sa.Column("association_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "association_type",
            sa.Enum("translation", name="associationtype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("source_novel_id", sa.UUID(), nullable=False),
        sa.Column("target_novel_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_novel_id"], ["novels.novel_id"], name="fk_novel_associations_source_novel_id_novels"
        ),
        sa.ForeignKeyConstraint(
            ["target_novel_id"], ["novels.novel_id"], name="fk_novel_associations_target_novel_id_novels"
        ),
        sa.PrimaryKeyConstraint("association_id"),
        sa.UniqueConstraint("source_novel_id", "target_novel_id", "association_type", name="uq_novel_association"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("novel_associations")
    # ### end Alembic commands ###
