"""empty message

Revision ID: 22a6c184456f
Revises: 7a1c9e2b4d6f
Create Date: 2026-08-02 23:24:36.839099+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "22a6c184456f"
down_revision = "7a1c9e2b4d6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_novels",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.novel_id"], name="fk_workflow_novels_novel_id_novels"),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.workflow_id"], name="fk_workflow_novels_workflow_id_workflows"
        ),
        sa.PrimaryKeyConstraint("workflow_id", "novel_id"),
    )
    op.create_index("ix_workflow_novels_novel_id", "workflow_novels", ["novel_id"], unique=False)
    op.create_table(
        "workflow_label_groups",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("label_group_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_group_id"],
            ["label_groups.label_group_id"],
            name="fk_workflow_label_groups_label_group_id_label_groups",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.workflow_id"], name="fk_workflow_label_groups_workflow_id_workflows"
        ),
        sa.PrimaryKeyConstraint("workflow_id", "label_group_id"),
    )
    op.create_index(
        "ix_workflow_label_groups_label_group_id", "workflow_label_groups", ["label_group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_label_groups_label_group_id", table_name="workflow_label_groups")
    op.drop_table("workflow_label_groups")
    op.drop_index("ix_workflow_novels_novel_id", table_name="workflow_novels")
    op.drop_table("workflow_novels")
    # ### end Alembic commands ###
