"""changed labeldata, now points to rawchapterrevision

Revision ID: 311bff881c2e
Revises: 494134820c05
Create Date: 2025-10-19 06:50:11.943436+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '311bff881c2e'
down_revision = '494134820c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_datas', sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('one_label_group_per_chapter'), 'label_datas', type_='unique')
    op.create_unique_constraint('one_label_group_per_chapter', 'label_datas', ['label_group_id', 'raw_chapter_revision_id'])
    op.drop_constraint(op.f('label_datas_raw_chapter_id_fkey'), 'label_datas', type_='foreignkey')
    op.create_foreign_key(None, 'label_datas', 'raw_chapter_revisions', ['raw_chapter_revision_id'], ['raw_chapter_revision_id'])
    op.drop_column('label_datas', 'raw_chapter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_datas', sa.Column('raw_chapter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'label_datas', type_='foreignkey')
    op.create_foreign_key(op.f('label_datas_raw_chapter_id_fkey'), 'label_datas', 'raw_chapters', ['raw_chapter_id'], ['raw_chapter_id'])
    op.drop_constraint('one_label_group_per_chapter', 'label_datas', type_='unique')
    op.create_unique_constraint(op.f('one_label_group_per_chapter'), 'label_datas', ['label_group_id', 'raw_chapter_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('label_datas', 'raw_chapter_revision_id')
    # ### end Alembic commands ###
