"""typo

Revision ID: 494134820c05
Revises: 0af69e401fcc
Create Date: 2025-10-19 05:44:28.457960+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494134820c05'
down_revision = '0af69e401fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
