"""enforce language code length

Revision ID: 7c5b2746086a
Revises: 8217e7002da0
Create Date: 2025-11-26 04:11:52.125229+00:00

"""
from alembic import op
import sqlalchemy as sa # type: ignore


# revision identifiers, used by Alembic.
revision = '7c5b2746086a'
down_revision = '8217e7002da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        'chk_language_code_length',
        'languages',
        'char_length(language_code) = 2'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_language_code_length', 'languages', type_='check')
    pass
    # ### end Alembic commands ###
