"""initial

Revision ID: 7d1863f93374
Revises:
Create Date: 2026-04-04 01:06:37.107075+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from src.novels.models import EnumAsInteger, Visibility

# revision identifiers, used by Alembic.
revision = '7d1863f93374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    op.create_table('languages',
    sa.Column('language_name', sa.String(length=31), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(language_code) = 2', name='chk_language_code_length'),
    sa.PrimaryKeyConstraint('language_code'),
    sa.UniqueConstraint('language_name', name='language_name_unique')
    )
    op.create_table('source_works',
    sa.Column('source_work_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_work_title', sa.String(length=255), nullable=False),
    sa.Column('source_work_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_work_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_name', sa.String(length=31), nullable=False),
    sa.Column('user_hashed_password', sa.String(length=256), nullable=False),
    sa.Column('user_type', sa.Enum('user', 'admin', name='usertype', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name', name='uq_user_name')
    )
    op.create_table('novels',
    sa.Column('novel_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('novel_title', sa.String(length=255), nullable=False),
    sa.Column('novel_description', sa.Text(), nullable=True),
    sa.Column('novel_author', sa.String(length=31), nullable=True),
    sa.Column('novel_visibility', EnumAsInteger(Visibility), nullable=False), # type: ignore
    sa.Column('novel_type', sa.Enum('original', 'translation', 'other', name='noveltype', native_enum=False, length=16), nullable=False),
    sa.Column('source_work_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.language_code'], name='fk_novels_language_code_languages'),
    sa.ForeignKeyConstraint(['source_work_id'], ['source_works.source_work_id'], ),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('chapters',
    sa.Column('chapter_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_num', sa.Integer(), nullable=False),
    sa.Column('chapter_title', sa.String(length=255), nullable=True),
    sa.Column('chapter_is_public', sa.Boolean(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='fk_chapters_novel_id_novels'),
    sa.PrimaryKeyConstraint('chapter_id'),
    sa.UniqueConstraint('chapter_num', 'novel_id', name='chapter_per_novel')
    )
    op.create_table('label_groups',
    sa.Column('label_group_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label_group_name', sa.String(length=31), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='fk_label_groups_novel_id_novels'),
    sa.PrimaryKeyConstraint('label_group_id')
    )
    op.create_table('novel_contributors',
    sa.Column('contributor_role', sa.Enum('owner', 'viewer', 'editor', name='role', native_enum=False, length=10), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('novel_id', 'user_id')
    )
    op.create_table('chapter_contents',
    sa.Column('chapter_content_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chapter_content_text', sa.Text(), nullable=False),
    sa.Column('chapter_content_version', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], name='fk_chapter_contents_chapter_id_chapters', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chapter_content_id'),
    sa.UniqueConstraint('chapter_id', 'chapter_content_version', name='uq_chapter_content_version_per_chapter')
    )
    op.create_table('label_group_contributors',
    sa.Column('label_contributor_role', sa.Enum('owner', 'viewer', 'editor', name='labelrole', native_enum=False, length=10), nullable=False),
    sa.Column('label_group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('label_group_id', 'user_id')
    )
    op.create_table('auto_labels',
    sa.Column('auto_label_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auto_label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_label_model_name', sa.String(length=128), nullable=False),
    sa.Column('auto_label_model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_label_status', sa.Enum('failed', 'pending', 'processing', 'done', name='autolabelprogress', native_enum=False), nullable=False),
    sa.Column('auto_label_last_job_id', sa.String(length=36), nullable=True),
    sa.Column('auto_label_message', sa.Text(), nullable=True),
    sa.Column('chapter_content_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_content_id'], ['chapter_contents.chapter_content_id'], name='fk_auto_labels_chapter_content_id_chapter_contents'),
    sa.PrimaryKeyConstraint('auto_label_id'),
    sa.UniqueConstraint('chapter_content_id', 'auto_label_model_name', 'auto_label_model_params', name='uq_model_name_params')
    )
    op.create_table('label_datas',
    sa.Column('label_data_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label_group_id', sa.UUID(), nullable=False),
    sa.Column('chapter_content_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_content_id'], ['chapter_contents.chapter_content_id'], name='fk_label_datas_chapter_content_id_chapter_contents'),
    sa.ForeignKeyConstraint(['label_group_id'], ['label_groups.label_group_id'], name='fk_label_datas_label_group_id_label_groups'),
    sa.PrimaryKeyConstraint('label_data_id'),
    sa.UniqueConstraint('label_group_id', 'chapter_content_id', name='one_label_group_per_chapter')
    )
    op.create_table('labels',
    sa.Column('label_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label_entity_group', sa.String(length=64), nullable=False),
    sa.Column('label_score', sa.Float(), nullable=False),
    sa.Column('label_word', sa.String(length=128), nullable=False),
    sa.Column('label_start', sa.Integer(), nullable=False),
    sa.Column('label_end', sa.Integer(), nullable=False),
    sa.Column('label_dirty', sa.Boolean(), nullable=False),
    sa.Column('label_data_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('label_data_id'), '='), (sa.text("int4range(label_start, label_end, '[)')"), '&&'), using='gist', name='no_overlapping_labels_per_group'), # type: ignore
    sa.CheckConstraint('label_score >= 0.0 AND label_score <= 1.0', name='chk_score_bounds'),
    sa.CheckConstraint('label_start < label_end', name='chk_label_start_lt_label_end'),
    sa.ForeignKeyConstraint(['label_data_id'], ['label_datas.label_data_id'], name='fk_labels_label_data_id_label_datas'),
    sa.PrimaryKeyConstraint('label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels')
    op.drop_table('label_datas')
    op.drop_table('auto_labels')
    op.drop_table('label_group_contributors')
    op.drop_table('chapter_contents')
    op.drop_table('novel_contributors')
    op.drop_table('label_groups')
    op.drop_table('chapters')
    op.drop_table('novels')
    op.drop_table('users')
    op.drop_table('source_works')
    op.drop_table('languages')
    # ### end Alembic commands ###
