"""updated raw chapter revision to separate public and final

Revision ID: 8217e7002da0
Revises: 8750555125c6
Create Date: 2025-11-23 04:10:11.587171+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8217e7002da0'
down_revision = '8750555125c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_chapter_revisions', sa.Column('raw_chapter_revision_is_final', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_chapter_revisions', 'raw_chapter_revision_is_final')
    # ### end Alembic commands ###
