"""updated label models to flattened list of labels

Revision ID: 8750555125c6
Revises: c0ef1ad0c0c8
Create Date: 2025-11-20 06:14:56.832715+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '8750555125c6'
down_revision = 'c0ef1ad0c0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table('labels',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label_entity_group', sa.String(length=64), nullable=False),
    sa.Column('label_score', sa.Float(), nullable=False),
    sa.Column('label_word', sa.String(length=128), nullable=False),
    sa.Column('label_start', sa.Integer(), nullable=False),
    sa.Column('label_end', sa.Integer(), nullable=False),
    sa.Column('label_dirty', sa.Boolean(), nullable=False),
    sa.Column('label_data_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('label_data_id'), '='), (sa.text("int4range(label_start, label_end, '[)')"), '&&'), using='gist', name='no_overlapping_labels_per_group'),
    sa.CheckConstraint('label_score >= 0.0 AND label_score <= 1.0', name='chk_score_bounds'),
    sa.CheckConstraint('label_start < label_end', name='chk_label_start_lt_label_end'),
    sa.ForeignKeyConstraint(['label_data_id'], ['label_datas.label_data_id'], ),
    sa.PrimaryKeyConstraint('label_id'),
    sa.UniqueConstraint('label_start', 'label_data_id', name='uq_one_label_with_start_per_label_data')
    )
    op.drop_column('label_datas', 'label_data_entities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_datas', sa.Column('label_data_entities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_table('labels')
    # ### end Alembic commands ###
