"""update novel/chapter models

Revision ID: a0e19c1d8bd0
Revises: 311bff881c2e
Create Date: 2025-10-23 06:27:57.079193+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e19c1d8bd0'
down_revision = '311bff881c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_chapter_revisions', sa.Column('raw_chapter_revision_is_public', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('user_type', sa.String(length=10), nullable=False, server_default="admin"))
    # ### end Alembic commands ###
    op.execute("ALTER TABLE users ADD CONSTRAINT chk_user_type CHECK (user_type IN ('admin', 'user'))")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    op.drop_column('raw_chapter_revisions', 'raw_chapter_revision_is_public')
    # ### end Alembic commands ###
