"""apparently i forgot to do this????

Revision ID: a5d20765c07d
Revises: fb4e92ee368f
Create Date: 2025-12-14 10:02:50.615458+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a5d20765c07d'
down_revision = 'fb4e92ee368f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_labels', sa.Column('auto_label_last_job_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_labels', 'auto_label_last_job_id')
    # ### end Alembic commands ###
