"""Add translation jobs, stages, batches, chapter associations, and tasks.

Revision ID: aa638b86e216
Revises: cf64a69327b1
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "aa638b86e216"
down_revision = "cf64a69327b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translation_jobs",
        sa.Column("job_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["novel_id"],
            ["novels.novel_id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "translation_batches",
        sa.Column("batch_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("batch_num", sa.Integer(), nullable=False),
        sa.Column("initial_file_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("batch_num >= 0", name="ck_translation_batch_num"),
        sa.ForeignKeyConstraint(
            ["initial_file_id"],
            ["stored_files.file_id"],
        ),
        sa.ForeignKeyConstraint(["job_id"], ["translation_jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("batch_id"),
        sa.UniqueConstraint("job_id", "batch_num", name="uq_translation_batch_job_num"),
    )
    op.create_table(
        "translation_stages",
        sa.Column("stage_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("stage_num", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("stage_num >= 0", name="ck_translation_stage_num"),
        sa.ForeignKeyConstraint(["job_id"], ["translation_jobs.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("stage_id"),
        sa.UniqueConstraint("job_id", "stage_num", name="uq_translation_stage_job_num"),
    )
    op.create_table(
        "translation_job_chapters",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column("source_chapter_content_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["translation_batches.batch_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.chapter_id"],
        ),
        sa.ForeignKeyConstraint(["job_id"], ["translation_jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_chapter_content_id"],
            ["chapter_contents.chapter_content_id"],
        ),
        sa.PrimaryKeyConstraint("job_id", "chapter_id"),
    )
    op.create_index(
        op.f("ix_translation_job_chapters_batch_id"), "translation_job_chapters", ["batch_id"], unique=False
    )
    op.create_table(
        "translation_tasks",
        sa.Column("task_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "ready",
                "preparing",
                "prepared",
                "submitting",
                "processing",
                "processed",
                "finalizing",
                "complete",
                name="translationtaskstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("input_file_id", sa.UUID(), nullable=True),
        sa.Column("output_file_id", sa.UUID(), nullable=True),
        sa.Column("provider_batch_id", sa.Text(), nullable=True),
        sa.Column("provider_output_id", sa.Text(), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("next_poll_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(claim_token IS NULL AND claim_expires_at IS NULL) OR (claim_token IS NOT NULL AND claim_expires_at IS NOT NULL)",
            name="ck_translation_task_claim_token_expiration",
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["translation_batches.batch_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["input_file_id"],
            ["stored_files.file_id"],
        ),
        sa.ForeignKeyConstraint(
            ["output_file_id"],
            ["stored_files.file_id"],
        ),
        sa.ForeignKeyConstraint(["stage_id"], ["translation_stages.stage_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
        sa.UniqueConstraint("claim_token"),
        sa.UniqueConstraint("stage_id", "batch_id", name="uq_translation_task_stage_batch"),
    )
    op.create_index(op.f("ix_translation_tasks_batch_id"), "translation_tasks", ["batch_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translation_tasks_batch_id"), table_name="translation_tasks")
    op.drop_table("translation_tasks")
    op.drop_index(op.f("ix_translation_job_chapters_batch_id"), table_name="translation_job_chapters")
    op.drop_table("translation_job_chapters")
    op.drop_table("translation_stages")
    op.drop_table("translation_batches")
    op.drop_table("translation_jobs")
    # ### end Alembic commands ###
