"""add translation tables

Revision ID: ab15b9c01e82
Revises: fd98b5a00bb1
Create Date: 2026-04-03 16:41:06.652993+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab15b9c01e82'
down_revision = 'fd98b5a00bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel_translation_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='noveltranslationstatus', native_enum=False), nullable=False),
    sa.Column('job_model_name', sa.String(length=128), nullable=True),
    sa.Column('job_last_job_id', sa.UUID(), nullable=True),
    sa.Column('job_message', sa.Text(), nullable=True),
    sa.Column('chapters_translated', sa.Integer(), nullable=False),
    sa.Column('chapters_total', sa.Integer(), nullable=False),
    sa.Column('target_language_code', sa.String(length=8), nullable=False),
    sa.Column('source_novel_id', sa.UUID(), nullable=False),
    sa.Column('target_novel_id', sa.UUID(), nullable=True),
    sa.Column('glossary_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['glossary_id'], ['glossaries.glossary_id'], name='fk_novel_translation_jobs_glossary_id_glossaries', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_novel_id'], ['novels.novel_id'], name='fk_novel_translation_jobs_source_novel_id_novels', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_novel_id'], ['novels.novel_id'], name='fk_novel_translation_jobs_target_novel_id_novels', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('chapter_translation_mappings',
    sa.Column('mapping_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', 'skipped', name='chaptertranslationstatus', native_enum=False), nullable=False),
    sa.Column('mapping_message', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_chapter_id', sa.UUID(), nullable=False),
    sa.Column('target_chapter_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['novel_translation_jobs.job_id'], name='fk_chapter_translation_mappings_job_id_novel_translation_jobs', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chapter_id'], ['chapters.chapter_id'], name='fk_chapter_translation_mappings_source_chapter_id_chapters', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_chapter_id'], ['chapters.chapter_id'], name='fk_chapter_translation_mappings_target_chapter_id_chapters', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_translation_mappings')
    op.drop_table('novel_translation_jobs')
    # ### end Alembic commands ###
