"""more filter stuff

Revision ID: b6e04981ca94
Revises: 7a1c9e2b4d6f
Create Date: 2026-08-02 08:05:19.142292+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b6e04981ca94"
down_revision = "7a1c9e2b4d6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_novels",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.novel_id"], name="fk_workflow_novels_novel_id_novels"),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.workflow_id"], name="fk_workflow_novels_workflow_id_workflows"
        ),
        sa.PrimaryKeyConstraint("workflow_id", "novel_id"),
    )
    op.create_table(
        "workflow_label_groups",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("label_group_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_group_id"],
            ["label_groups.label_group_id"],
            name="fk_workflow_label_groups_label_group_id_label_groups",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.workflow_id"], name="fk_workflow_label_groups_workflow_id_workflows"
        ),
        sa.PrimaryKeyConstraint("workflow_id", "label_group_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_label_groups")
    op.drop_table("workflow_novels")
    # ### end Alembic commands ###
