"""memory glossary backend

Revision ID: c9ae0b0e03ec
Revises: 22a6c184456f
Create Date: 2026-08-22 04:20:03.746215+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c9ae0b0e03ec"
down_revision = "22a6c184456f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_groups",
        sa.Column("memory_group_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("memory_group_name", sa.String(length=100), nullable=False),
        sa.Column("novel_id", sa.UUID(), nullable=False),
        sa.Column("memory_language", sa.String(length=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_language"], ["languages.language_code"], name="fk_memory_groups_language_code_languages"
        ),
        sa.ForeignKeyConstraint(["novel_id"], ["novels.novel_id"], name="fk_memory_groups_novel_id_novels"),
        sa.PrimaryKeyConstraint("memory_group_id"),
    )
    op.create_index("ix_memory_groups_novel_id", "memory_groups", ["novel_id"], unique=False)
    op.create_table(
        "glossaries",
        sa.Column("term_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("term", sa.String(length=100), nullable=False),
        sa.Column("memory_group_id", sa.UUID(), nullable=False),
        sa.Column(
            "review_status",
            sa.Enum("pending", "approved", "rejected", name="reviewstatus", native_enum=False, length=10),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_group_id"], ["memory_groups.memory_group_id"], name="fk_glossaries_memory_group_id_memory_groups"
        ),
        sa.PrimaryKeyConstraint("term_id"),
        sa.UniqueConstraint("memory_group_id", "term", name="uq_glossaries_term_memory_group_id"),
    )
    op.create_table(
        "memories",
        sa.Column("memory_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("memory_group_id", sa.UUID(), nullable=False),
        sa.Column(
            "memory_type",
            sa.Enum("fact", "event", "def", "rel", name="memorytype", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("memory_observed_in", sa.UUID(), nullable=False),
        sa.Column("memory_start_num", sa.Integer(), nullable=False),
        sa.Column("memory_end_num", sa.Integer(), nullable=True),
        sa.Column("supersedes_memory_id", sa.UUID(), nullable=True),
        sa.Column("memory_content", sa.Text(), nullable=False),
        sa.Column(
            "memory_review_status",
            sa.Enum("pending", "approved", "rejected", name="reviewstatus", native_enum=False, length=10),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "creator_type",
            sa.Enum("user", "workflow", "agent", name="creator", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("plugin_name", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("memory_start_num < memory_end_num", name="ck_memories_start_end_num"),
        sa.ForeignKeyConstraint(
            ["memory_group_id"], ["memory_groups.memory_group_id"], name="fk_memories_memory_group_id_memory_groups"
        ),
        sa.ForeignKeyConstraint(["memory_observed_in"], ["chapter_contents.chapter_content_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["supersedes_memory_id"], ["memories.memory_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(
        "ix_memories_memory_group_id_start_num", "memories", ["memory_group_id", "memory_start_num"], unique=False
    )
    op.create_index("ix_memories_memory_observed_in", "memories", ["memory_observed_in"], unique=False)
    op.create_index("ix_memories_supersedes_memory_id", "memories", ["supersedes_memory_id"], unique=False)
    op.create_table(
        "glossary_associations",
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.memory_id"],
            name="fk_glossary_associations_memory_id_memories",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["glossaries.term_id"], name="fk_glossary_associations_term_id_glossaries", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("term_id", "memory_id"),
    )
    op.create_index("ix_glossary_associations_memory_id", "glossary_associations", ["memory_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_glossary_associations_memory_id", table_name="glossary_associations")
    op.drop_table("glossary_associations")
    op.drop_index("ix_memories_supersedes_memory_id", table_name="memories")
    op.drop_index("ix_memories_memory_observed_in", table_name="memories")
    op.drop_index("ix_memories_memory_group_id_start_num", table_name="memories")
    op.drop_table("memories")
    op.drop_table("glossaries")
    op.drop_index("ix_memory_groups_novel_id", table_name="memory_groups")
    op.drop_table("memory_groups")
    # ### end Alembic commands ###
