"""filters

Revision ID: d386545e4f4a
Revises: ffe31a9821c0
Create Date: 2026-07-28 20:08:37.501805+00:00

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d386545e4f4a"
down_revision = "ffe31a9821c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function_definitions",
        sa.Column("function_definition_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("function_name", sa.String(length=100), nullable=False),
        sa.Column("function_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("function_definition_id"),
        sa.UniqueConstraint("namespace", "function_name", name="uq_function_definitions_namespace_function_name"),
    )
    op.create_table(
        "workflows",
        sa.Column("workflow_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workflow_name", sa.String(length=100), nullable=True),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "workflow_status",
            sa.Enum("pending", "processing", "complete", "failed", name="workflowstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("workflow_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("workflow_id"),
    )
    op.create_table(
        "groupings",
        sa.Column("grouping_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("function_definition_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "grouping_status",
            sa.Enum("pending", "processing", "complete", "failed", name="groupingstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("grouping_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["function_definition_id"],
            ["function_definitions.function_definition_id"],
            name="fk_groupings_function_definition_id_function_definitions",
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.workflow_id"], name="fk_groupings_workflow_id_workflows"),
        sa.PrimaryKeyConstraint("grouping_id"),
        sa.UniqueConstraint("workflow_id", "function_definition_id", name="uq_groupings_workflow_function_definition"),
    )
    op.create_index(op.f("ix_groupings_workflow_id"), "groupings", ["workflow_id"], unique=False)
    op.create_table(
        "instances",
        sa.Column("instance_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.workflow_id"], name="fk_instances_workflow_id_workflows"),
        sa.PrimaryKeyConstraint("instance_id"),
    )
    op.create_index(op.f("ix_instances_workflow_id"), "instances", ["workflow_id"], unique=False)
    op.create_table(
        "group_assignments",
        sa.Column("group_assignment_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("grouping_id", sa.UUID(), nullable=False),
        sa.Column("instance_id", sa.UUID(), nullable=False),
        sa.Column("function_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grouping_id"], ["groupings.grouping_id"], name="fk_group_assignments_grouping_id_groupings"
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"], ["instances.instance_id"], name="fk_group_assignments_instance_id_instances"
        ),
        sa.PrimaryKeyConstraint("group_assignment_id"),
        sa.UniqueConstraint("grouping_id", "instance_id", name="uq_grouping_instance"),
    )
    op.create_index(
        "ix_group_assignments_grouping_value", "group_assignments", ["grouping_id", "function_value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_group_assignments_grouping_value", table_name="group_assignments")
    op.drop_table("group_assignments")
    op.drop_index(op.f("ix_instances_workflow_id"), table_name="instances")
    op.drop_table("instances")
    op.drop_index(op.f("ix_groupings_workflow_id"), table_name="groupings")
    op.drop_table("groupings")
    op.drop_table("workflows")
    op.drop_table("function_definitions")
    # ### end Alembic commands ###
