"""resolve issue with enum using values_callable in user_type

Revision ID: dd70ca7f7dcd
Revises: db55c8b8273b
Create Date: 2025-11-14 04:17:43.285865+00:00

"""


# revision identifiers, used by Alembic.
revision = 'dd70ca7f7dcd'
down_revision = 'db55c8b8273b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
