"""memory jobs

Revision ID: df9890b9fdd4
Revises: c9ae0b0e03ec
Create Date: 2026-08-28 02:39:36.111158+00:00

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "df9890b9fdd4"
down_revision = "c9ae0b0e03ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_jobs",
        sa.Column("memory_job_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("memory_group_id", sa.UUID(), nullable=False),
        sa.Column("job_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("claim_token", sa.UUID(), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(claim_token IS NULL AND claim_expires_at IS NULL) OR (claim_token IS NOT NULL AND claim_expires_at IS NOT NULL)",
            name="ck_memory_jobs_claim_token_expiration",
        ),
        sa.ForeignKeyConstraint(
            ["memory_group_id"],
            ["memory_groups.memory_group_id"],
            name="fk_memory_jobs_memory_group_id_memory_groups",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_job_id"),
        sa.UniqueConstraint("claim_token"),
    )
    op.create_table(
        "memory_chapter_tasks",
        sa.Column("memory_job_id", sa.UUID(), nullable=False),
        sa.Column("chapter_id", sa.UUID(), nullable=False),
        sa.Column(
            "task_status",
            sa.Enum("pending", "processing", "completed", "failed", name="jobstatus", native_enum=False, length=15),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"], ["chapters.chapter_id"], name="fk_memory_job_tasks_chapter_id_chapters", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["memory_job_id"],
            ["memory_jobs.memory_job_id"],
            name="fk_memory_job_tasks_memory_job_id_memory_jobs",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("memory_job_id", "chapter_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("memory_chapter_tasks")
    op.drop_table("memory_jobs")
    # ### end Alembic commands ###
