"""cache ok true for enumasinteger

Revision ID: e4537d18d35c
Revises: 1fbdd31e9fe5
Create Date: 2025-12-25 00:12:53.297724+00:00

"""


# revision identifiers, used by Alembic.
revision = 'e4537d18d35c'
down_revision = '1fbdd31e9fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
