"""switch entity group to non-null

Revision ID: e6b5ee9d4018
Revises: 7d1863f93374
Create Date: 2026-05-04 18:46:36.622265+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e6b5ee9d4018"
down_revision = "7d1863f93374"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chapters", "chapter_title", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("labels", "label_entity_group", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("labels", "label_entity_group", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("chapters", "chapter_title", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###
