"""add cascade delete to glossary FKs

Revision ID: e8ee48d8ed23
Revises: 9148916294a0
Create Date: 2026-04-02 03:32:29.023673+00:00

"""

# revision identifiers, used by Alembic.
revision = "e8ee48d8ed23"
down_revision = "9148916294a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
