"""job id string to uuid

Revision ID: f4e5fa11f9af
Revises: d386545e4f4a
Create Date: 2026-07-29 04:54:46.470184+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f4e5fa11f9af"
down_revision = "d386545e4f4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auto_labels",
        "auto_label_last_job_id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="auto_label_last_job_id::uuid",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auto_labels",
        "auto_label_last_job_id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=36),
        existing_nullable=True,
        postgresql_using="auto_label_last_job_id::varchar(36)",
    )
    # ### end Alembic commands ###
