"""explicit for nullable in models

Revision ID: f5b35fb0e2b6
Revises: 7c5b2746086a
Create Date: 2025-11-26 05:27:42.285899+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f5b35fb0e2b6'
down_revision = '7c5b2746086a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novels', 'novel_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('novels', 'novel_author',
               existing_type=sa.VARCHAR(length=31),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novels', 'novel_author',
               existing_type=sa.VARCHAR(length=31),
               nullable=False)
    op.alter_column('novels', 'novel_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
