"""labels version

Revision ID: fa743ea4464a
Revises: f4e5fa11f9af
Create Date: 2026-07-30 23:54:48.985676+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa743ea4464a"
down_revision = "f4e5fa11f9af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("labels", sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("labels", "version")
    # ### end Alembic commands ###
