"""separated computation heavy tasks from user request processing in autolabels, modified db schema

Revision ID: fb4e92ee368f
Revises: 5a285fac79b0
Create Date: 2025-12-04 08:37:20.475495+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb4e92ee368f'
down_revision = '5a285fac79b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_labels',
    sa.Column('auto_label_id', sa.Integer(), nullable=False),
    sa.Column('auto_label_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_label_model_name', sa.String(length=128), nullable=False),
    sa.Column('auto_label_model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auto_label_status', sa.Enum('failed', 'pending', 'done', name='autolabelstatus', native_enum=False, length=10), nullable=False),
    sa.Column('auto_label_message', sa.Text(), nullable=True),
    sa.Column('raw_chapter_revision_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_chapter_revision_id'], ['raw_chapter_revisions.raw_chapter_revision_id'], ),
    sa.PrimaryKeyConstraint('auto_label_id'),
    sa.UniqueConstraint('raw_chapter_revision_id', 'auto_label_model_name', 'auto_label_model_params', name='uq_model_name_params')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_labels')
    # ### end Alembic commands ###
