"""empty message

Revision ID: fc32f3fee87e
Revises: a0e19c1d8bd0
Create Date: 2025-11-04 05:32:40.470671+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc32f3fee87e'
down_revision = 'a0e19c1d8bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
