"""autolabels move to grouping runs

Revision ID: ffe31a9821c0
Revises: e6b5ee9d4018
Create Date: 2026-06-30 04:33:39.024490+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ffe31a9821c0'
down_revision = 'e6b5ee9d4018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_label_runs',
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], name='fk_auto_label_runs_novel_id_novels'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.user_id'], name='fk_auto_label_runs_triggered_by_users'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.add_column('auto_labels', sa.Column('run_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('uq_model_name_params'), 'auto_labels', type_='unique')
    op.create_unique_constraint('uq_chapter_content_run_id', 'auto_labels', ['chapter_content_id', 'run_id'])
    op.create_foreign_key('fk_auto_labels_run_id_auto_label_runs', 'auto_labels', 'auto_label_runs', ['run_id'], ['run_id'])
    op.drop_column('auto_labels', 'auto_label_model_params')
    op.drop_column('auto_labels', 'auto_label_model_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_labels', sa.Column('auto_label_model_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('auto_labels', sa.Column('auto_label_model_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint('fk_auto_labels_run_id_auto_label_runs', 'auto_labels', type_='foreignkey')
    op.drop_constraint('uq_chapter_content_run_id', 'auto_labels', type_='unique')
    op.create_unique_constraint(op.f('uq_model_name_params'), 'auto_labels', ['chapter_content_id', 'auto_label_model_name', 'auto_label_model_params'], postgresql_nulls_not_distinct=False)
    op.drop_column('auto_labels', 'run_id')
    op.drop_table('auto_label_runs')
    # ### end Alembic commands ###
