/**
 * Generated by orval 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateFunctionDefinitionRequest,
  DetailHTTPErrorResponse,
  FunctionDefinitionMeta,
  FunctionDefinitionResponse,
  FunctionDefinitionValidationResponse,
  GroupOperationAccepted,
  GroupValueCount,
  GroupingResponse,
  GroupingSummary,
  HTTPValidationError,
  InstanceQuery,
  InstanceQueryResult,
  InstanceResponse,
  PythonAnnotationRequest,
  PythonFilterRequest,
  PythonGroupRequest,
  PythonLabelSourceRequest,
  PythonMapRequest,
  ReadFunctionsFiltersFunctionsGetParams,
  ReadGroupingValuesFiltersGroupingsGroupingIdValuesGetParams,
  ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetParams,
  ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetParams,
  ReadWorkflowsFiltersWorkflowsGetParams,
  RenameWorkflowRequest,
  UpdateInstanceRequest,
  ValidateFunctionDefinitionRequest,
  WorkflowOperationAccepted,
  WorkflowResponse,
  WorkflowSummary
} from '../../models';

import { customFetch } from '../../custom-fetch';

export type readFunctionsFiltersFunctionsGetResponse200 = {
  data: FunctionDefinitionMeta[]
  status: 200
}

export type readFunctionsFiltersFunctionsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readFunctionsFiltersFunctionsGetResponseSuccess = (readFunctionsFiltersFunctionsGetResponse200) & {
  headers: Headers;
};
export type readFunctionsFiltersFunctionsGetResponseError = (readFunctionsFiltersFunctionsGetResponse422) & {
  headers: Headers;
};

export type readFunctionsFiltersFunctionsGetResponse = (readFunctionsFiltersFunctionsGetResponseSuccess | readFunctionsFiltersFunctionsGetResponseError)

export const getReadFunctionsFiltersFunctionsGetUrl = (params?: ReadFunctionsFiltersFunctionsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/filters/functions?${stringifiedParams}` : `/api/filters/functions`
}

/**
 * List saved function definitions.
 * @summary Read Functions
 */
export const readFunctionsFiltersFunctionsGet = async (params?: ReadFunctionsFiltersFunctionsGetParams, options?: Parameters<typeof customFetch>[1]): Promise<readFunctionsFiltersFunctionsGetResponse> => {

  return customFetch<readFunctionsFiltersFunctionsGetResponse>(getReadFunctionsFiltersFunctionsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type createFilterFunctionResponse201 = {
  data: FunctionDefinitionResponse
  status: 201
}

export type createFilterFunctionResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type createFilterFunctionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createFilterFunctionResponseSuccess = (createFilterFunctionResponse201) & {
  headers: Headers;
};
export type createFilterFunctionResponseError = (createFilterFunctionResponse409 | createFilterFunctionResponse422) & {
  headers: Headers;
};

export type createFilterFunctionResponse = (createFilterFunctionResponseSuccess | createFilterFunctionResponseError)

export const getCreateFilterFunctionUrl = () => {




  return `/api/filters/functions`
}

/**
 * Save an immutable function definition in the shared registry.
 * @summary Create Filter Function
 */
export const createFilterFunction = async (createFunctionDefinitionRequest: CreateFunctionDefinitionRequest, options?: Parameters<typeof customFetch>[1]): Promise<createFilterFunctionResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<createFilterFunctionResponse>(getCreateFilterFunctionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createFunctionDefinitionRequest)
  }
);}


export type validateFilterFunctionResponse200 = {
  data: FunctionDefinitionValidationResponse
  status: 200
}

export type validateFilterFunctionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type validateFilterFunctionResponseSuccess = (validateFilterFunctionResponse200) & {
  headers: Headers;
};
export type validateFilterFunctionResponseError = (validateFilterFunctionResponse422) & {
  headers: Headers;
};

export type validateFilterFunctionResponse = (validateFilterFunctionResponseSuccess | validateFilterFunctionResponseError)

export const getValidateFilterFunctionUrl = () => {




  return `/api/filters/functions/validate`
}

/**
 * Validate a function draft and return its computed signature without saving it.
 * @summary Validate Filter Function
 */
export const validateFilterFunction = async (validateFunctionDefinitionRequest: ValidateFunctionDefinitionRequest, options?: Parameters<typeof customFetch>[1]): Promise<validateFilterFunctionResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<validateFilterFunctionResponse>(getValidateFilterFunctionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(validateFunctionDefinitionRequest)
  }
);}


export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse200 = {
  data: FunctionDefinitionResponse
  status: 200
}

export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponseSuccess = (readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse200) & {
  headers: Headers;
};
export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponseError = (readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse404 | readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse422) & {
  headers: Headers;
};

export type readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse = (readFunctionFiltersFunctionsFunctionDefinitionIdGetResponseSuccess | readFunctionFiltersFunctionsFunctionDefinitionIdGetResponseError)

export const getReadFunctionFiltersFunctionsFunctionDefinitionIdGetUrl = (functionDefinitionId: string,) => {




  return `/api/filters/functions/${functionDefinitionId}`
}

/**
 * Return one saved function definition.
 * @summary Read Function
 */
export const readFunctionFiltersFunctionsFunctionDefinitionIdGet = async (functionDefinitionId: string, options?: Parameters<typeof customFetch>[1]): Promise<readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse> => {

  return customFetch<readFunctionFiltersFunctionsFunctionDefinitionIdGetResponse>(getReadFunctionFiltersFunctionsFunctionDefinitionIdGetUrl(functionDefinitionId),
  {
    ...options,
    method: 'GET'


  }
);}


export type readGroupingFiltersGroupingsGroupingIdGetResponse200 = {
  data: GroupingResponse
  status: 200
}

export type readGroupingFiltersGroupingsGroupingIdGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readGroupingFiltersGroupingsGroupingIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readGroupingFiltersGroupingsGroupingIdGetResponseSuccess = (readGroupingFiltersGroupingsGroupingIdGetResponse200) & {
  headers: Headers;
};
export type readGroupingFiltersGroupingsGroupingIdGetResponseError = (readGroupingFiltersGroupingsGroupingIdGetResponse404 | readGroupingFiltersGroupingsGroupingIdGetResponse422) & {
  headers: Headers;
};

export type readGroupingFiltersGroupingsGroupingIdGetResponse = (readGroupingFiltersGroupingsGroupingIdGetResponseSuccess | readGroupingFiltersGroupingsGroupingIdGetResponseError)

export const getReadGroupingFiltersGroupingsGroupingIdGetUrl = (groupingId: string,) => {




  return `/api/filters/groupings/${groupingId}`
}

/**
 * Return one grouping with derived output metadata.
 * @summary Read Grouping
 */
export const readGroupingFiltersGroupingsGroupingIdGet = async (groupingId: string, options?: Parameters<typeof customFetch>[1]): Promise<readGroupingFiltersGroupingsGroupingIdGetResponse> => {

  return customFetch<readGroupingFiltersGroupingsGroupingIdGetResponse>(getReadGroupingFiltersGroupingsGroupingIdGetUrl(groupingId),
  {
    ...options,
    method: 'GET'


  }
);}


export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse200 = {
  data: GroupValueCount[]
  status: 200
}

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponseSuccess = (readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse200) & {
  headers: Headers;
};
export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponseError = (readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse400 | readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse404 | readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse409 | readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse422) & {
  headers: Headers;
};

export type readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse = (readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponseSuccess | readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponseError)

export const getReadGroupingValuesFiltersGroupingsGroupingIdValuesGetUrl = (groupingId: string,
    params?: ReadGroupingValuesFiltersGroupingsGroupingIdValuesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/filters/groupings/${groupingId}/values?${stringifiedParams}` : `/api/filters/groupings/${groupingId}/values`
}

/**
 * List distinct values and counts for one completed grouping.
 * @summary Read Grouping Values
 */
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet = async (groupingId: string,
    params?: ReadGroupingValuesFiltersGroupingsGroupingIdValuesGetParams, options?: Parameters<typeof customFetch>[1]): Promise<readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse> => {

  return customFetch<readGroupingValuesFiltersGroupingsGroupingIdValuesGetResponse>(getReadGroupingValuesFiltersGroupingsGroupingIdValuesGetUrl(groupingId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type readInstancesAdvancedFiltersInstancesQueryPostResponse200 = {
  data: InstanceQueryResult[]
  status: 200
}

export type readInstancesAdvancedFiltersInstancesQueryPostResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type readInstancesAdvancedFiltersInstancesQueryPostResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readInstancesAdvancedFiltersInstancesQueryPostResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type readInstancesAdvancedFiltersInstancesQueryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readInstancesAdvancedFiltersInstancesQueryPostResponseSuccess = (readInstancesAdvancedFiltersInstancesQueryPostResponse200) & {
  headers: Headers;
};
export type readInstancesAdvancedFiltersInstancesQueryPostResponseError = (readInstancesAdvancedFiltersInstancesQueryPostResponse400 | readInstancesAdvancedFiltersInstancesQueryPostResponse404 | readInstancesAdvancedFiltersInstancesQueryPostResponse409 | readInstancesAdvancedFiltersInstancesQueryPostResponse422) & {
  headers: Headers;
};

export type readInstancesAdvancedFiltersInstancesQueryPostResponse = (readInstancesAdvancedFiltersInstancesQueryPostResponseSuccess | readInstancesAdvancedFiltersInstancesQueryPostResponseError)

export const getReadInstancesAdvancedFiltersInstancesQueryPostUrl = () => {




  return `/api/filters/instances/query`
}

/**
 * Query instances with grouping filters and scalar sort keys.
 * @summary Read Instances Advanced
 */
export const readInstancesAdvancedFiltersInstancesQueryPost = async (instanceQuery: InstanceQuery, options?: Parameters<typeof customFetch>[1]): Promise<readInstancesAdvancedFiltersInstancesQueryPostResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<readInstancesAdvancedFiltersInstancesQueryPostResponse>(getReadInstancesAdvancedFiltersInstancesQueryPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(instanceQuery)
  }
);}


export type updateFilterInstanceResponse200 = {
  data: InstanceResponse
  status: 200
}

export type updateFilterInstanceResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type updateFilterInstanceResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type updateFilterInstanceResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type updateFilterInstanceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateFilterInstanceResponseSuccess = (updateFilterInstanceResponse200) & {
  headers: Headers;
};
export type updateFilterInstanceResponseError = (updateFilterInstanceResponse400 | updateFilterInstanceResponse404 | updateFilterInstanceResponse409 | updateFilterInstanceResponse422) & {
  headers: Headers;
};

export type updateFilterInstanceResponse = (updateFilterInstanceResponseSuccess | updateFilterInstanceResponseError)

export const getUpdateFilterInstanceUrl = (instanceId: string,) => {




  return `/api/filters/instances/${instanceId}`
}

/**
 * Update mutable scalar fields on one completed workflow instance.
 * @summary Update Filter Instance
 */
export const updateFilterInstance = async (instanceId: string,
    updateInstanceRequest: UpdateInstanceRequest, options?: Parameters<typeof customFetch>[1]): Promise<updateFilterInstanceResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<updateFilterInstanceResponse>(getUpdateFilterInstanceUrl(instanceId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateInstanceRequest)
  }
);}


export type runPythonAnnotationResponse202 = {
  data: WorkflowOperationAccepted
  status: 202
}

export type runPythonAnnotationResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type runPythonAnnotationResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type runPythonAnnotationResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type runPythonAnnotationResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type runPythonAnnotationResponse503 = {
  data: DetailHTTPErrorResponse
  status: 503
}

export type runPythonAnnotationResponseSuccess = (runPythonAnnotationResponse202) & {
  headers: Headers;
};
export type runPythonAnnotationResponseError = (runPythonAnnotationResponse400 | runPythonAnnotationResponse404 | runPythonAnnotationResponse409 | runPythonAnnotationResponse422 | runPythonAnnotationResponse503) & {
  headers: Headers;
};

export type runPythonAnnotationResponse = (runPythonAnnotationResponseSuccess | runPythonAnnotationResponseError)

export const getRunPythonAnnotationUrl = () => {




  return `/api/filters/runners/python/annotation`
}

/**
 * Add mutable annotation fields to an existing workflow.
 * @summary Run Python Annotation
 */
export const runPythonAnnotation = async (pythonAnnotationRequest: PythonAnnotationRequest, options?: Parameters<typeof customFetch>[1]): Promise<runPythonAnnotationResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<runPythonAnnotationResponse>(getRunPythonAnnotationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pythonAnnotationRequest)
  }
);}


export type runPythonFilterResponse202 = {
  data: WorkflowOperationAccepted
  status: 202
}

export type runPythonFilterResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type runPythonFilterResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type runPythonFilterResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type runPythonFilterResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type runPythonFilterResponse503 = {
  data: DetailHTTPErrorResponse
  status: 503
}

export type runPythonFilterResponseSuccess = (runPythonFilterResponse202) & {
  headers: Headers;
};
export type runPythonFilterResponseError = (runPythonFilterResponse400 | runPythonFilterResponse404 | runPythonFilterResponse409 | runPythonFilterResponse422 | runPythonFilterResponse503) & {
  headers: Headers;
};

export type runPythonFilterResponse = (runPythonFilterResponseSuccess | runPythonFilterResponseError)

export const getRunPythonFilterUrl = () => {




  return `/api/filters/runners/python/filter`
}

/**
 * Create and enqueue a filtered workflow.
 * @summary Run Python Filter
 */
export const runPythonFilter = async (pythonFilterRequest: PythonFilterRequest, options?: Parameters<typeof customFetch>[1]): Promise<runPythonFilterResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<runPythonFilterResponse>(getRunPythonFilterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pythonFilterRequest)
  }
);}


export type runPythonGroupResponse202 = {
  data: GroupOperationAccepted
  status: 202
}

export type runPythonGroupResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type runPythonGroupResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type runPythonGroupResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type runPythonGroupResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type runPythonGroupResponse503 = {
  data: DetailHTTPErrorResponse
  status: 503
}

export type runPythonGroupResponseSuccess = (runPythonGroupResponse202) & {
  headers: Headers;
};
export type runPythonGroupResponseError = (runPythonGroupResponse400 | runPythonGroupResponse404 | runPythonGroupResponse409 | runPythonGroupResponse422 | runPythonGroupResponse503) & {
  headers: Headers;
};

export type runPythonGroupResponse = (runPythonGroupResponseSuccess | runPythonGroupResponseError)

export const getRunPythonGroupUrl = () => {




  return `/api/filters/runners/python/group`
}

/**
 * Create and enqueue grouping assignments for a workflow.
 * @summary Run Python Group
 */
export const runPythonGroup = async (pythonGroupRequest: PythonGroupRequest, options?: Parameters<typeof customFetch>[1]): Promise<runPythonGroupResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<runPythonGroupResponse>(getRunPythonGroupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pythonGroupRequest)
  }
);}


export type runPythonLabelSourceResponse202 = {
  data: WorkflowOperationAccepted
  status: 202
}

export type runPythonLabelSourceResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type runPythonLabelSourceResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type runPythonLabelSourceResponse503 = {
  data: DetailHTTPErrorResponse
  status: 503
}

export type runPythonLabelSourceResponseSuccess = (runPythonLabelSourceResponse202) & {
  headers: Headers;
};
export type runPythonLabelSourceResponseError = (runPythonLabelSourceResponse404 | runPythonLabelSourceResponse422 | runPythonLabelSourceResponse503) & {
  headers: Headers;
};

export type runPythonLabelSourceResponse = (runPythonLabelSourceResponseSuccess | runPythonLabelSourceResponseError)

export const getRunPythonLabelSourceUrl = () => {




  return `/api/filters/runners/python/label-source`
}

/**
 * Create and enqueue a workflow from the current labels in a group.
 * @summary Run Python Label Source
 */
export const runPythonLabelSource = async (pythonLabelSourceRequest: PythonLabelSourceRequest, options?: Parameters<typeof customFetch>[1]): Promise<runPythonLabelSourceResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<runPythonLabelSourceResponse>(getRunPythonLabelSourceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pythonLabelSourceRequest)
  }
);}


export type runPythonMapResponse202 = {
  data: WorkflowOperationAccepted
  status: 202
}

export type runPythonMapResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type runPythonMapResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type runPythonMapResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type runPythonMapResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type runPythonMapResponse503 = {
  data: DetailHTTPErrorResponse
  status: 503
}

export type runPythonMapResponseSuccess = (runPythonMapResponse202) & {
  headers: Headers;
};
export type runPythonMapResponseError = (runPythonMapResponse400 | runPythonMapResponse404 | runPythonMapResponse409 | runPythonMapResponse422 | runPythonMapResponse503) & {
  headers: Headers;
};

export type runPythonMapResponse = (runPythonMapResponseSuccess | runPythonMapResponseError)

export const getRunPythonMapUrl = () => {




  return `/api/filters/runners/python/map`
}

/**
 * Create and enqueue a mapped workflow.
 * @summary Run Python Map
 */
export const runPythonMap = async (pythonMapRequest: PythonMapRequest, options?: Parameters<typeof customFetch>[1]): Promise<runPythonMapResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<runPythonMapResponse>(getRunPythonMapUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pythonMapRequest)
  }
);}


export type readWorkflowsFiltersWorkflowsGetResponse200 = {
  data: WorkflowSummary[]
  status: 200
}

export type readWorkflowsFiltersWorkflowsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readWorkflowsFiltersWorkflowsGetResponseSuccess = (readWorkflowsFiltersWorkflowsGetResponse200) & {
  headers: Headers;
};
export type readWorkflowsFiltersWorkflowsGetResponseError = (readWorkflowsFiltersWorkflowsGetResponse422) & {
  headers: Headers;
};

export type readWorkflowsFiltersWorkflowsGetResponse = (readWorkflowsFiltersWorkflowsGetResponseSuccess | readWorkflowsFiltersWorkflowsGetResponseError)

export const getReadWorkflowsFiltersWorkflowsGetUrl = (params?: ReadWorkflowsFiltersWorkflowsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/filters/workflows?${stringifiedParams}` : `/api/filters/workflows`
}

/**
 * List workflows accessible to the current user.
 * @summary Read Workflows
 */
export const readWorkflowsFiltersWorkflowsGet = async (params?: ReadWorkflowsFiltersWorkflowsGetParams, options?: Parameters<typeof customFetch>[1]): Promise<readWorkflowsFiltersWorkflowsGetResponse> => {

  return customFetch<readWorkflowsFiltersWorkflowsGetResponse>(getReadWorkflowsFiltersWorkflowsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type readWorkflowFiltersWorkflowsWorkflowIdGetResponse200 = {
  data: WorkflowResponse
  status: 200
}

export type readWorkflowFiltersWorkflowsWorkflowIdGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readWorkflowFiltersWorkflowsWorkflowIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readWorkflowFiltersWorkflowsWorkflowIdGetResponseSuccess = (readWorkflowFiltersWorkflowsWorkflowIdGetResponse200) & {
  headers: Headers;
};
export type readWorkflowFiltersWorkflowsWorkflowIdGetResponseError = (readWorkflowFiltersWorkflowsWorkflowIdGetResponse404 | readWorkflowFiltersWorkflowsWorkflowIdGetResponse422) & {
  headers: Headers;
};

export type readWorkflowFiltersWorkflowsWorkflowIdGetResponse = (readWorkflowFiltersWorkflowsWorkflowIdGetResponseSuccess | readWorkflowFiltersWorkflowsWorkflowIdGetResponseError)

export const getReadWorkflowFiltersWorkflowsWorkflowIdGetUrl = (workflowId: string,) => {




  return `/api/filters/workflows/${workflowId}`
}

/**
 * Return one workflow with its permission scope and instance count.
 * @summary Read Workflow
 */
export const readWorkflowFiltersWorkflowsWorkflowIdGet = async (workflowId: string, options?: Parameters<typeof customFetch>[1]): Promise<readWorkflowFiltersWorkflowsWorkflowIdGetResponse> => {

  return customFetch<readWorkflowFiltersWorkflowsWorkflowIdGetResponse>(getReadWorkflowFiltersWorkflowsWorkflowIdGetUrl(workflowId),
  {
    ...options,
    method: 'GET'


  }
);}


export type renameFilterWorkflowResponse200 = {
  data: WorkflowResponse
  status: 200
}

export type renameFilterWorkflowResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type renameFilterWorkflowResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type renameFilterWorkflowResponseSuccess = (renameFilterWorkflowResponse200) & {
  headers: Headers;
};
export type renameFilterWorkflowResponseError = (renameFilterWorkflowResponse404 | renameFilterWorkflowResponse422) & {
  headers: Headers;
};

export type renameFilterWorkflowResponse = (renameFilterWorkflowResponseSuccess | renameFilterWorkflowResponseError)

export const getRenameFilterWorkflowUrl = (workflowId: string,) => {




  return `/api/filters/workflows/${workflowId}`
}

/**
 * Rename or clear the name of an accessible workflow.
 * @summary Rename Filter Workflow
 */
export const renameFilterWorkflow = async (workflowId: string,
    renameWorkflowRequest: RenameWorkflowRequest, options?: Parameters<typeof customFetch>[1]): Promise<renameFilterWorkflowResponse> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<renameFilterWorkflowResponse>(getRenameFilterWorkflowUrl(workflowId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renameWorkflowRequest)
  }
);}


export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse200 = {
  data: GroupingSummary[]
  status: 200
}

export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponseSuccess = (readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse200) & {
  headers: Headers;
};
export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponseError = (readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse404 | readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse422) & {
  headers: Headers;
};

export type readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse = (readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponseSuccess | readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponseError)

export const getReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetUrl = (workflowId: string,
    params?: ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/filters/workflows/${workflowId}/groupings?${stringifiedParams}` : `/api/filters/workflows/${workflowId}/groupings`
}

/**
 * List groupings attached to one workflow.
 * @summary Read Workflow Groupings
 */
export const readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet = async (workflowId: string,
    params?: ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetParams, options?: Parameters<typeof customFetch>[1]): Promise<readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse> => {

  return customFetch<readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetResponse>(getReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetUrl(workflowId,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse200 = {
  data: InstanceResponse[]
  status: 200
}

export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse409 = {
  data: DetailHTTPErrorResponse
  status: 409
}

export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponseSuccess = (readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse200) & {
  headers: Headers;
};
export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponseError = (readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse404 | readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse409 | readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse422) & {
  headers: Headers;
};

export type readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse = (readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponseSuccess | readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponseError)

export const getReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetUrl = (workflowId: string,
    params?: ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/filters/workflows/${workflowId}/instances?${stringifiedParams}` : `/api/filters/workflows/${workflowId}/instances`
}

/**
 * List instances of one completed workflow.
 * @summary Read Workflow Instances
 */
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet = async (workflowId: string,
    params?: ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetParams, options?: Parameters<typeof customFetch>[1]): Promise<readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse> => {

  return customFetch<readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetResponse>(getReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetUrl(workflowId,params),
  {
    ...options,
    method: 'GET'


  }
);}


