/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  Schema as S
} from 'effect';


/**
 * List saved function definitions.
 * @summary Read Functions
 */
export const readFunctionsFiltersFunctionsGetQueryLimitDefault = 50;
export const readFunctionsFiltersFunctionsGetQueryLimitMax = 100;



export const ReadFunctionsFiltersFunctionsGetQueryParams = S.Struct({
  "search": S.optional(S.Union(S.String, S.Null)),
  "namespace": S.optional(S.Union(S.String, S.Null)),
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readFunctionsFiltersFunctionsGetQueryLimitMax)), { default: () => readFunctionsFiltersFunctionsGetQueryLimitDefault }),
  "cursor": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const ReadFunctionsFiltersFunctionsGet200ResponseItem = S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "functionName": S.String,
  "namespace": S.String
})
export const ReadFunctionsFiltersFunctionsGet200Response = S.Array(ReadFunctionsFiltersFunctionsGet200ResponseItem)

export const ReadFunctionsFiltersFunctionsGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Save an immutable function definition in the shared registry.
 * @summary Create Filter Function
 */
export const createFilterFunctionBodyFunctionNameMax = 100;

export const createFilterFunctionBodyNamespaceMax = 100;



export const CreateFilterFunctionBody = S.Struct({
  "functionDefinition": S.Record({ key: S.String, value: S.Unknown }),
  "functionName": S.String.pipe(S.minLength(1), S.maxLength(createFilterFunctionBodyFunctionNameMax)),
  "namespace": S.String.pipe(S.minLength(1), S.maxLength(createFilterFunctionBodyNamespaceMax))
})

export const CreateFilterFunction201Response = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "functionDefinition": S.Record({ key: S.String, value: S.Unknown }),
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "functionName": S.String,
  "namespace": S.String,
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/))
})

export const CreateFilterFunction409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const CreateFilterFunction422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Return one saved function definition.
 * @summary Read Function
 */
export const ReadFunctionFiltersFunctionsFunctionDefinitionIdGetParams = S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadFunctionFiltersFunctionsFunctionDefinitionIdGet200Response = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "functionDefinition": S.Record({ key: S.String, value: S.Unknown }),
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "functionName": S.String,
  "namespace": S.String,
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/))
})

export const ReadFunctionFiltersFunctionsFunctionDefinitionIdGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadFunctionFiltersFunctionsFunctionDefinitionIdGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Return one grouping with derived output metadata.
 * @summary Read Grouping
 */
export const ReadGroupingFiltersGroupingsGroupingIdGetParams = S.Struct({
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadGroupingFiltersGroupingsGroupingIdGet200Response = S.Struct({
  "assignmentCount": S.Number,
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "functionDefinition": S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "functionName": S.String,
  "namespace": S.String
}),
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "groupingMessage": S.Union(S.String, S.Null),
  "groupingStatus": S.Literal('pending', 'processing', 'complete', 'failed'),
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "outputType": S.Literal('string', 'int', 'bool'),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const ReadGroupingFiltersGroupingsGroupingIdGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadGroupingFiltersGroupingsGroupingIdGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * List distinct values and counts for one completed grouping.
 * @summary Read Grouping Values
 */
export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGetParams = S.Struct({
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryLimitDefault = 50;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryLimitMax = 100;

export const readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryOffsetDefault = 0;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryOffsetMin = 0;



export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryParams = S.Struct({
  "search": S.optional(S.Union(S.String, S.Null)),
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryLimitMax)), { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryLimitDefault }),
  "offset": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryOffsetMin)), { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGetQueryOffsetDefault })
})

export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueOneObjDefault = false;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueOneTypeDefault = `string`;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueTwoObjDefault = false;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueTwoTypeDefault = `int`;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueThreeObjDefault = false;
export const readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueThreeTypeDefault = `bool`;

export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseItem = S.Struct({
  "count": S.Number,
  "value": S.Union(S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueOneTypeDefault }),
  "value": S.String
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueTwoTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueThreeObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseValueThreeTypeDefault }),
  "value": S.Boolean
}))
})
export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet200Response = S.Array(ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet200ResponseItem)

export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet400Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadGroupingValuesFiltersGroupingsGroupingIdValuesGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Query instances with grouping filters and scalar sort keys.
 * @summary Read Instances Advanced
 */
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersMax = 10;

export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesMax = 100;

export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemOneObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemOneTypeDefault = `string`;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemTwoObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemTwoTypeDefault = `int`;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemThreeObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemThreeTypeDefault = `bool`;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysMax = 3;

export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysItemFieldNameMax = 128;


export const readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysItemFieldNameRegExp = new RegExp('.*\\S.*');
export const readInstancesAdvancedFiltersInstancesQueryPostBodyLimitDefault = 50;
export const readInstancesAdvancedFiltersInstancesQueryPostBodyLimitMax = 100;



export const ReadInstancesAdvancedFiltersInstancesQueryPostBody = S.Struct({
  "cursor": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)).annotations({ description: 'Cursor for pagination. If provided, must be a valid instance id. The query will return results after this cursor according to the sort keys.' }),
  "frame": S.Struct({
  "groupFilters": S.Array(S.Struct({
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "values": S.Array(S.Union(S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemOneTypeDefault }),
  "value": S.String
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemTwoTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemThreeObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesItemThreeTypeDefault }),
  "value": S.Boolean
}))).pipe(S.maxItems(readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersItemValuesMax))
})).pipe(S.maxItems(readInstancesAdvancedFiltersInstancesQueryPostBodyFrameGroupFiltersMax)),
  "sortKeys": S.optional(S.Array(S.Struct({
  "direction": S.Literal('asc', 'desc'),
  "fieldName": S.String.pipe(S.minLength(1), S.maxLength(readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysItemFieldNameMax), S.pattern(readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysItemFieldNameRegExp))
})).pipe(S.maxItems(readInstancesAdvancedFiltersInstancesQueryPostBodyFrameSortKeysMax))),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}),
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readInstancesAdvancedFiltersInstancesQueryPostBodyLimitMax)), { default: () => readInstancesAdvancedFiltersInstancesQueryPostBodyLimitDefault })
})

export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesOneObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesOneTypeDefault = `string`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesTwoObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesTwoTypeDefault = `int`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesThreeObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesThreeTypeDefault = `bool`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsOneObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsOneTypeDefault = `string`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsTwoObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsTwoTypeDefault = `int`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsThreeObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsThreeTypeDefault = `float`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFourObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFourTypeDefault = `bool`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveTypeDefault = `textSpan`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveValueEndMin = 0;

export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveValueStartMin = 0;

export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsSixObjDefault = false;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsSixTypeDefault = `labelRef`;
export const readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueObjDefault = true;

export const ReadInstancesAdvancedFiltersInstancesQueryPost200ResponseItem = S.Struct({
  "groupValues": S.Record({ key: S.String, value: S.Union(S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesOneTypeDefault }),
  "value": S.String
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesTwoTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesThreeObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseGroupValuesThreeTypeDefault }),
  "value": S.Boolean
})) }),
  "instance": S.Struct({
  "instanceId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "value": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsOneTypeDefault }),
  "value": S.String
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsTwoTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsThreeTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFourTypeDefault }),
  "value": S.Boolean
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveTypeDefault }),
  "value": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "end": S.Number.pipe(S.greaterThanOrEqualTo(readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveValueEndMin)),
  "start": S.Number.pipe(S.greaterThanOrEqualTo(readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsFiveValueStartMin))
})
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueFieldsSixTypeDefault }),
  "value": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => readInstancesAdvancedFiltersInstancesQueryPost200ResponseInstanceValueObjDefault })
}),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})
})
export const ReadInstancesAdvancedFiltersInstancesQueryPost200Response = S.Array(ReadInstancesAdvancedFiltersInstancesQueryPost200ResponseItem)

export const ReadInstancesAdvancedFiltersInstancesQueryPost400Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadInstancesAdvancedFiltersInstancesQueryPost404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadInstancesAdvancedFiltersInstancesQueryPost409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadInstancesAdvancedFiltersInstancesQueryPost422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Create and enqueue a filtered workflow.
 * @summary Run Python Filter
 */
export const runPythonFilterBodyOutputNameOneMax = 100;



export const RunPythonFilterBody = S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Saved object-to-boolean function to execute.' }),
  "outputName": S.optional(S.Union(S.String.pipe(S.maxLength(runPythonFilterBodyOutputNameOneMax)), S.Null)),
  "sourceWorkflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Completed workflow whose instances will be filtered.' })
})

export const runPythonFilter202ResponseWorkflowSchemaFieldsOneMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsOneObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsOneTypeDefault = `string`;
export const runPythonFilter202ResponseWorkflowSchemaFieldsTwoMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsTwoObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsTwoTypeDefault = `int`;
export const runPythonFilter202ResponseWorkflowSchemaFieldsThreeMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsThreeObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsThreeTypeDefault = `float`;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFourMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFourObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFourTypeDefault = `bool`;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFiveMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFiveObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsFiveTypeDefault = `labelRef`;
export const runPythonFilter202ResponseWorkflowSchemaFieldsSixMutableDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsSixObjDefault = false;
export const runPythonFilter202ResponseWorkflowSchemaFieldsSixTypeDefault = `textSpan`;
export const runPythonFilter202ResponseWorkflowSchemaObjDefault = true;

export const RunPythonFilter202Response = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflow": S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "instanceCount": S.Number,
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "labelGroupIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "novelIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => runPythonFilter202ResponseWorkflowSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonFilter202ResponseWorkflowSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})
})

export const RunPythonFilter400Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonFilter404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonFilter409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonFilter422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

export const RunPythonFilter503Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

/**
 * Create and enqueue grouping assignments for a workflow.
 * @summary Run Python Group
 */
export const RunPythonGroupBody = S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Saved object-to-scalar grouping function to execute.' }),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Completed workflow whose instances will be grouped.' })
})

export const RunPythonGroup202Response = S.Struct({
  "grouping": S.Struct({
  "assignmentCount": S.Number,
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "functionDefinition": S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "functionName": S.String,
  "namespace": S.String
}),
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "groupingMessage": S.Union(S.String, S.Null),
  "groupingStatus": S.Literal('pending', 'processing', 'complete', 'failed'),
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "outputType": S.Literal('string', 'int', 'bool'),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
}),
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const RunPythonGroup400Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonGroup404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonGroup409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonGroup422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

export const RunPythonGroup503Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

/**
 * Create and enqueue a workflow from the current labels in a group.
 * @summary Run Python Label Source
 */
export const runPythonLabelSourceBodyOutputNameOneMax = 100;



export const RunPythonLabelSourceBody = S.Struct({
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Label group whose current labels will seed the workflow.' }),
  "outputName": S.optional(S.Union(S.String.pipe(S.maxLength(runPythonLabelSourceBodyOutputNameOneMax)), S.Null))
})

export const runPythonLabelSource202ResponseWorkflowSchemaFieldsOneMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsOneObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsOneTypeDefault = `string`;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoTypeDefault = `int`;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeTypeDefault = `float`;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFourMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFourObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFourTypeDefault = `bool`;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveTypeDefault = `labelRef`;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsSixMutableDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsSixObjDefault = false;
export const runPythonLabelSource202ResponseWorkflowSchemaFieldsSixTypeDefault = `textSpan`;
export const runPythonLabelSource202ResponseWorkflowSchemaObjDefault = true;

export const RunPythonLabelSource202Response = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflow": S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "instanceCount": S.Number,
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "labelGroupIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "novelIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => runPythonLabelSource202ResponseWorkflowSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonLabelSource202ResponseWorkflowSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})
})

export const RunPythonLabelSource404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonLabelSource422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

export const RunPythonLabelSource503Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

/**
 * Create and enqueue a mapped workflow.
 * @summary Run Python Map
 */
export const runPythonMapBodyOutputNameOneMax = 100;



export const RunPythonMapBody = S.Struct({
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Saved object-to-object function to execute.' }),
  "outputName": S.optional(S.Union(S.String.pipe(S.maxLength(runPythonMapBodyOutputNameOneMax)), S.Null)),
  "sourceWorkflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)).annotations({ description: 'Completed workflow whose instances will be mapped.' })
})

export const runPythonMap202ResponseWorkflowSchemaFieldsOneMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsOneObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsOneTypeDefault = `string`;
export const runPythonMap202ResponseWorkflowSchemaFieldsTwoMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsTwoObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsTwoTypeDefault = `int`;
export const runPythonMap202ResponseWorkflowSchemaFieldsThreeMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsThreeObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsThreeTypeDefault = `float`;
export const runPythonMap202ResponseWorkflowSchemaFieldsFourMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsFourObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsFourTypeDefault = `bool`;
export const runPythonMap202ResponseWorkflowSchemaFieldsFiveMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsFiveObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsFiveTypeDefault = `labelRef`;
export const runPythonMap202ResponseWorkflowSchemaFieldsSixMutableDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsSixObjDefault = false;
export const runPythonMap202ResponseWorkflowSchemaFieldsSixTypeDefault = `textSpan`;
export const runPythonMap202ResponseWorkflowSchemaObjDefault = true;

export const RunPythonMap202Response = S.Struct({
  "jobId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflow": S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "instanceCount": S.Number,
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "labelGroupIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "novelIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => runPythonMap202ResponseWorkflowSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => runPythonMap202ResponseWorkflowSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})
})

export const RunPythonMap400Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonMap404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonMap409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RunPythonMap422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

export const RunPythonMap503Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

/**
 * List workflows accessible to the current user.
 * @summary Read Workflows
 */
export const readWorkflowsFiltersWorkflowsGetQueryLimitDefault = 50;
export const readWorkflowsFiltersWorkflowsGetQueryLimitMax = 100;



export const ReadWorkflowsFiltersWorkflowsGetQueryParams = S.Struct({
  "novelId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)),
  "labelGroupId": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null)),
  "useCase": S.optional(S.Union(S.Literal('advanced', 'glossary'), S.Null)),
  "status": S.optional(S.Union(S.Literal('pending', 'processing', 'complete', 'failed'), S.Null)),
  "search": S.optional(S.Union(S.String, S.Null)),
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readWorkflowsFiltersWorkflowsGetQueryLimitMax)), { default: () => readWorkflowsFiltersWorkflowsGetQueryLimitDefault }),
  "cursor": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneTypeDefault = `string`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoTypeDefault = `int`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeTypeDefault = `float`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourTypeDefault = `bool`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveTypeDefault = `labelRef`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixMutableDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixObjDefault = false;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixTypeDefault = `textSpan`;
export const readWorkflowsFiltersWorkflowsGet200ResponseSchemaObjDefault = true;

export const ReadWorkflowsFiltersWorkflowsGet200ResponseItem = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowsFiltersWorkflowsGet200ResponseSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})
export const ReadWorkflowsFiltersWorkflowsGet200Response = S.Array(ReadWorkflowsFiltersWorkflowsGet200ResponseItem)

export const ReadWorkflowsFiltersWorkflowsGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Return one workflow with its permission scope and instance count.
 * @summary Read Workflow
 */
export const ReadWorkflowFiltersWorkflowsWorkflowIdGetParams = S.Struct({
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneTypeDefault = `string`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoTypeDefault = `int`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeTypeDefault = `float`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourTypeDefault = `bool`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveTypeDefault = `labelRef`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixMutableDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixObjDefault = false;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixTypeDefault = `textSpan`;
export const readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaObjDefault = true;

export const ReadWorkflowFiltersWorkflowsWorkflowIdGet200Response = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "instanceCount": S.Number,
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "labelGroupIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "novelIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowFiltersWorkflowsWorkflowIdGet200ResponseSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})

export const ReadWorkflowFiltersWorkflowsWorkflowIdGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadWorkflowFiltersWorkflowsWorkflowIdGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * Rename or clear the name of an accessible workflow.
 * @summary Rename Filter Workflow
 */
export const RenameFilterWorkflowParams = S.Struct({
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const renameFilterWorkflowBodyWorkflowNameOneMax = 100;



export const RenameFilterWorkflowBody = S.Struct({
  "workflowName": S.Union(S.String.pipe(S.maxLength(renameFilterWorkflowBodyWorkflowNameOneMax)), S.Null)
})

export const renameFilterWorkflow200ResponseSchemaFieldsOneMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsOneObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsOneTypeDefault = `string`;
export const renameFilterWorkflow200ResponseSchemaFieldsTwoMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsTwoObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsTwoTypeDefault = `int`;
export const renameFilterWorkflow200ResponseSchemaFieldsThreeMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsThreeObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsThreeTypeDefault = `float`;
export const renameFilterWorkflow200ResponseSchemaFieldsFourMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsFourObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsFourTypeDefault = `bool`;
export const renameFilterWorkflow200ResponseSchemaFieldsFiveMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsFiveObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsFiveTypeDefault = `labelRef`;
export const renameFilterWorkflow200ResponseSchemaFieldsSixMutableDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsSixObjDefault = false;
export const renameFilterWorkflow200ResponseSchemaFieldsSixTypeDefault = `textSpan`;
export const renameFilterWorkflow200ResponseSchemaObjDefault = true;

export const RenameFilterWorkflow200Response = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "instanceCount": S.Number,
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "labelGroupIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "novelIds": S.Array(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))),
  "schema": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsOneMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsOneTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsTwoMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsTwoTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsThreeMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsThreeTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsFourMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsFourTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsFiveMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsFiveTypeDefault })
}), S.Struct({
  "mutable": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsSixMutableDefault }),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => renameFilterWorkflow200ResponseSchemaFieldsSixTypeDefault })
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => renameFilterWorkflow200ResponseSchemaObjDefault })
}),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "useCase": S.Literal('advanced', 'glossary'),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "workflowMessage": S.Union(S.String, S.Null),
  "workflowName": S.Union(S.String, S.Null),
  "workflowStatus": S.Literal('pending', 'processing', 'complete', 'failed')
})

export const RenameFilterWorkflow404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const RenameFilterWorkflow422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * List groupings attached to one workflow.
 * @summary Read Workflow Groupings
 */
export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetParams = S.Struct({
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetQueryLimitDefault = 50;
export const readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetQueryLimitMax = 100;



export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetQueryParams = S.Struct({
  "status": S.optional(S.Union(S.Literal('pending', 'processing', 'complete', 'failed'), S.Null)),
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetQueryLimitMax)), { default: () => readWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGetQueryLimitDefault }),
  "cursor": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet200ResponseItem = S.Struct({
  "createdAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "functionDefinitionId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "groupingId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "groupingMessage": S.Union(S.String, S.Null),
  "groupingStatus": S.Literal('pending', 'processing', 'complete', 'failed'),
  "jobId": S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null),
  "updatedAt": S.String.pipe(S.pattern(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?(Z|[+-]\d{2}:?\d{2})?$/)),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})
export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet200Response = S.Array(ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet200ResponseItem)

export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadWorkflowGroupingsFiltersWorkflowsWorkflowIdGroupingsGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

/**
 * List instances of one completed workflow.
 * @summary Read Workflow Instances
 */
export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetParams = S.Struct({
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})

export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetQueryLimitDefault = 50;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetQueryLimitMax = 100;



export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetQueryParams = S.Struct({
  "limit": S.optionalWith(S.Number.pipe(S.greaterThanOrEqualTo(1), S.lessThanOrEqualTo(readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetQueryLimitMax)), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGetQueryLimitDefault }),
  "cursor": S.optional(S.Union(S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)), S.Null))
})

export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsOneObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsOneTypeDefault = `string`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsTwoObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsTwoTypeDefault = `int`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsThreeObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsThreeTypeDefault = `float`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFourObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFourTypeDefault = `bool`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveTypeDefault = `textSpan`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveValueEndMin = 0;

export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveValueStartMin = 0;

export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsSixObjDefault = false;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsSixTypeDefault = `labelRef`;
export const readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueObjDefault = true;

export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseItem = S.Struct({
  "instanceId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "value": S.Struct({
  "fields": S.optional(S.Record({ key: S.String, value: S.Union(S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsOneObjDefault }),
  "type": S.optionalWith(S.Literal('string'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsOneTypeDefault }),
  "value": S.String
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsTwoObjDefault }),
  "type": S.optionalWith(S.Literal('int'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsTwoTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsThreeObjDefault }),
  "type": S.optionalWith(S.Literal('float'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsThreeTypeDefault }),
  "value": S.Number
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFourObjDefault }),
  "type": S.optionalWith(S.Literal('bool'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFourTypeDefault }),
  "value": S.Boolean
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveObjDefault }),
  "type": S.optionalWith(S.Literal('textSpan'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveTypeDefault }),
  "value": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "end": S.Number.pipe(S.greaterThanOrEqualTo(readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveValueEndMin)),
  "start": S.Number.pipe(S.greaterThanOrEqualTo(readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsFiveValueStartMin))
})
}), S.Struct({
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsSixObjDefault }),
  "type": S.optionalWith(S.Literal('labelRef'), { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueFieldsSixTypeDefault }),
  "value": S.Struct({
  "chapterContentId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "chapterId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelDataId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelGroupId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)),
  "labelId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})
})) })),
  "obj": S.optionalWith(S.Boolean, { default: () => readWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseValueObjDefault })
}),
  "workflowId": S.String.pipe(S.pattern(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/))
})
export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200Response = S.Array(ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet200ResponseItem)

export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet404Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet409Response = S.Struct({
  "detail": S.String
}).annotations({ description: 'Generic error payload for HTTPException responses that only return a detail string.\n\nAttributes:\n    detail: Human-readable description of the error.' })

export const ReadWorkflowInstancesFiltersWorkflowsWorkflowIdInstancesGet422Response = S.Struct({
  "detail": S.optional(S.Array(S.Struct({
  "loc": S.Array(S.Union(S.String, S.Number)),
  "msg": S.String,
  "type": S.String
})))
})

