/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  AutoLabel,
  AutoLabelMeta,
  BodyLoginForAccessTokenTokenPost,
  CacheEntry,
  Chapter,
  ChapterContent,
  ChapterContentMeta,
  ChapterData,
  CreateAutoLabels,
  CreateChapter,
  CreateLabelData,
  CreateLabelDataByAutoLabel,
  CreateLabelDataByAutoLabelStatus,
  CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostParams,
  CreateLabelGroup,
  CreateLabelGroupLabelGroupsPostParams,
  CreateNovel,
  CreateSourceWork,
  CreateUser,
  DeleteUserStatus,
  DetailHTTPErrorResponse,
  EditChapterData,
  HTTPValidationError,
  InstanceContextOptions,
  InstanceOptions,
  Label,
  LabelContributor,
  LabelData,
  LabelGroup,
  LabelGroupWithRole,
  Language,
  ModifyChapterContentResponse,
  Novel,
  OperationStatus,
  ReadAutolabelsAutoLabelsGetParams,
  ReadChaptersByNovelChaptersGetParams,
  ReadEditChapterDataEditChapterDataChapterIdGetParams,
  ReadFilterSchemasFiltersSchemasGet200,
  ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostBody,
  ReadLabelDatasByGroupChaptersLabelDatasGetParams,
  ReadLabelGroupsLabelGroupsGetParams,
  ReadLabelGroupsWithRoleLabelGroupsWithRoleGetParams,
  ReadNovelsMineNovelsMineGetParams,
  ReadNovelsNovelsGetParams,
  ReadSourceWorksSourceWorksGetParams,
  RequestConflictErrorResponse,
  SourceWork,
  SourceWorkDataOutput,
  Token,
  UpdateChapter,
  UpdateChapterContent,
  UpdateChapterContentChaptersChapterIdContentPatchParams,
  UpdateLabelDataStream,
  UpdateLabelDataStreamLabelDatasLabelDataIdPatchParams,
  UpdateLabelGroup,
  UpdateNovel,
  UpdateSourceWork,
  User
} from '../../models';


export type readAutolabelsAutoLabelsGetResponse200 = {
  data: AutoLabelMeta[]
  status: 200
}

export type readAutolabelsAutoLabelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readAutolabelsAutoLabelsGetResponseSuccess = (readAutolabelsAutoLabelsGetResponse200) & {
  headers: Headers;
};
export type readAutolabelsAutoLabelsGetResponseError = (readAutolabelsAutoLabelsGetResponse422) & {
  headers: Headers;
};

export type readAutolabelsAutoLabelsGetResponse = (readAutolabelsAutoLabelsGetResponseSuccess | readAutolabelsAutoLabelsGetResponseError)

export const getReadAutolabelsAutoLabelsGetUrl = (params: ReadAutolabelsAutoLabelsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auto-labels?${stringifiedParams}` : `/auto-labels`
}

/**
 * @summary Read Autolabels
 */
export const readAutolabelsAutoLabelsGet = async (params: ReadAutolabelsAutoLabelsGetParams, options?: RequestInit): Promise<readAutolabelsAutoLabelsGetResponse> => {

  const res = await fetch(getReadAutolabelsAutoLabelsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readAutolabelsAutoLabelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readAutolabelsAutoLabelsGetResponse
}


export type createAutolabelsAutoLabelsPostResponse200 = {
  data: AutoLabelMeta[]
  status: 200
}

export type createAutolabelsAutoLabelsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createAutolabelsAutoLabelsPostResponseSuccess = (createAutolabelsAutoLabelsPostResponse200) & {
  headers: Headers;
};
export type createAutolabelsAutoLabelsPostResponseError = (createAutolabelsAutoLabelsPostResponse422) & {
  headers: Headers;
};

export type createAutolabelsAutoLabelsPostResponse = (createAutolabelsAutoLabelsPostResponseSuccess | createAutolabelsAutoLabelsPostResponseError)

export const getCreateAutolabelsAutoLabelsPostUrl = () => {




  return `/auto-labels`
}

/**
 * @summary Create Autolabels
 */
export const createAutolabelsAutoLabelsPost = async (createAutoLabels: CreateAutoLabels, options?: RequestInit): Promise<createAutolabelsAutoLabelsPostResponse> => {

  const res = await fetch(getCreateAutolabelsAutoLabelsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAutoLabels)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createAutolabelsAutoLabelsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createAutolabelsAutoLabelsPostResponse
}


export type readAutolabelByIdAutoLabelsAutoLabelIdGetResponse200 = {
  data: AutoLabel
  status: 200
}

export type readAutolabelByIdAutoLabelsAutoLabelIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readAutolabelByIdAutoLabelsAutoLabelIdGetResponseSuccess = (readAutolabelByIdAutoLabelsAutoLabelIdGetResponse200) & {
  headers: Headers;
};
export type readAutolabelByIdAutoLabelsAutoLabelIdGetResponseError = (readAutolabelByIdAutoLabelsAutoLabelIdGetResponse422) & {
  headers: Headers;
};

export type readAutolabelByIdAutoLabelsAutoLabelIdGetResponse = (readAutolabelByIdAutoLabelsAutoLabelIdGetResponseSuccess | readAutolabelByIdAutoLabelsAutoLabelIdGetResponseError)

export const getReadAutolabelByIdAutoLabelsAutoLabelIdGetUrl = (autoLabelId: string,) => {




  return `/auto-labels/${autoLabelId}`
}

/**
 * Endpoint for retrieving autolabel from database.
 *
 * Args:
 *     auto_label_id: UUID for auto label.
 *     db: Database dependency.
 *     current_user: Current user dependency.
 * @summary Read Autolabel By Id
 */
export const readAutolabelByIdAutoLabelsAutoLabelIdGet = async (autoLabelId: string, options?: RequestInit): Promise<readAutolabelByIdAutoLabelsAutoLabelIdGetResponse> => {

  const res = await fetch(getReadAutolabelByIdAutoLabelsAutoLabelIdGetUrl(autoLabelId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readAutolabelByIdAutoLabelsAutoLabelIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readAutolabelByIdAutoLabelsAutoLabelIdGetResponse
}


export type getCachedResultCachedCachedIdGetResponse200 = {
  data: CacheEntry
  status: 200
}

export type getCachedResultCachedCachedIdGetResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type getCachedResultCachedCachedIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getCachedResultCachedCachedIdGetResponseSuccess = (getCachedResultCachedCachedIdGetResponse200) & {
  headers: Headers;
};
export type getCachedResultCachedCachedIdGetResponseError = (getCachedResultCachedCachedIdGetResponse404 | getCachedResultCachedCachedIdGetResponse422) & {
  headers: Headers;
};

export type getCachedResultCachedCachedIdGetResponse = (getCachedResultCachedCachedIdGetResponseSuccess | getCachedResultCachedCachedIdGetResponseError)

export const getGetCachedResultCachedCachedIdGetUrl = (cachedId: string,) => {




  return `/cached/${cachedId}`
}

/**
 * @summary Get Cached Result
 */
export const getCachedResultCachedCachedIdGet = async (cachedId: string, options?: RequestInit): Promise<getCachedResultCachedCachedIdGetResponse> => {

  const res = await fetch(getGetCachedResultCachedCachedIdGetUrl(cachedId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCachedResultCachedCachedIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCachedResultCachedCachedIdGetResponse
}


export type readChapterContentByIdChapterContentsChapterContentIdGetResponse200 = {
  data: ChapterContent
  status: 200
}

export type readChapterContentByIdChapterContentsChapterContentIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChapterContentByIdChapterContentsChapterContentIdGetResponseSuccess = (readChapterContentByIdChapterContentsChapterContentIdGetResponse200) & {
  headers: Headers;
};
export type readChapterContentByIdChapterContentsChapterContentIdGetResponseError = (readChapterContentByIdChapterContentsChapterContentIdGetResponse422) & {
  headers: Headers;
};

export type readChapterContentByIdChapterContentsChapterContentIdGetResponse = (readChapterContentByIdChapterContentsChapterContentIdGetResponseSuccess | readChapterContentByIdChapterContentsChapterContentIdGetResponseError)

export const getReadChapterContentByIdChapterContentsChapterContentIdGetUrl = (chapterContentId: string,) => {




  return `/chapter-contents/${chapterContentId}`
}

/**
 * Endpoint for retrieving a specific version of chapter content by its id.
 *
 * Raises:
 *     404: Chapter content not found (or insufficient permissions).
 * @summary Read Chapter Content By Id
 */
export const readChapterContentByIdChapterContentsChapterContentIdGet = async (chapterContentId: string, options?: RequestInit): Promise<readChapterContentByIdChapterContentsChapterContentIdGetResponse> => {

  const res = await fetch(getReadChapterContentByIdChapterContentsChapterContentIdGetUrl(chapterContentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChapterContentByIdChapterContentsChapterContentIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChapterContentByIdChapterContentsChapterContentIdGetResponse
}


export type readChaptersByNovelChaptersGetResponse200 = {
  data: Chapter[]
  status: 200
}

export type readChaptersByNovelChaptersGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChaptersByNovelChaptersGetResponseSuccess = (readChaptersByNovelChaptersGetResponse200) & {
  headers: Headers;
};
export type readChaptersByNovelChaptersGetResponseError = (readChaptersByNovelChaptersGetResponse422) & {
  headers: Headers;
};

export type readChaptersByNovelChaptersGetResponse = (readChaptersByNovelChaptersGetResponseSuccess | readChaptersByNovelChaptersGetResponseError)

export const getReadChaptersByNovelChaptersGetUrl = (params: ReadChaptersByNovelChaptersGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/chapters?${stringifiedParams}` : `/chapters`
}

/**
 * Endpoint for retrieving chapters by novel_id.
 *
 * Raises:
 *     404: Novel not found (or insufficient permissions).
 * @summary Read Chapters By Novel
 */
export const readChaptersByNovelChaptersGet = async (params: ReadChaptersByNovelChaptersGetParams, options?: RequestInit): Promise<readChaptersByNovelChaptersGetResponse> => {

  const res = await fetch(getReadChaptersByNovelChaptersGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChaptersByNovelChaptersGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChaptersByNovelChaptersGetResponse
}


export type deleteChapterChaptersChapterIdDeleteResponse200 = {
  data: OperationStatus
  status: 200
}

export type deleteChapterChaptersChapterIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteChapterChaptersChapterIdDeleteResponseSuccess = (deleteChapterChaptersChapterIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteChapterChaptersChapterIdDeleteResponseError = (deleteChapterChaptersChapterIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteChapterChaptersChapterIdDeleteResponse = (deleteChapterChaptersChapterIdDeleteResponseSuccess | deleteChapterChaptersChapterIdDeleteResponseError)

export const getDeleteChapterChaptersChapterIdDeleteUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}`
}

/**
 * Delete a chapter from the database.
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 *     500: Delete failed for other reasons.
 * @summary Delete Chapter
 */
export const deleteChapterChaptersChapterIdDelete = async (chapterId: string, options?: RequestInit): Promise<deleteChapterChaptersChapterIdDeleteResponse> => {

  const res = await fetch(getDeleteChapterChaptersChapterIdDeleteUrl(chapterId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteChapterChaptersChapterIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteChapterChaptersChapterIdDeleteResponse
}


export type readChapterByIdChaptersChapterIdGetResponse200 = {
  data: Chapter
  status: 200
}

export type readChapterByIdChaptersChapterIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChapterByIdChaptersChapterIdGetResponseSuccess = (readChapterByIdChaptersChapterIdGetResponse200) & {
  headers: Headers;
};
export type readChapterByIdChaptersChapterIdGetResponseError = (readChapterByIdChaptersChapterIdGetResponse422) & {
  headers: Headers;
};

export type readChapterByIdChaptersChapterIdGetResponse = (readChapterByIdChaptersChapterIdGetResponseSuccess | readChapterByIdChaptersChapterIdGetResponseError)

export const getReadChapterByIdChaptersChapterIdGetUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}`
}

/**
 * Endpoint for retrieving chapter by id.
 *
 * Raises:
 *     404: Chapter not found (or insufficient permissions).
 * @summary Read Chapter By Id
 */
export const readChapterByIdChaptersChapterIdGet = async (chapterId: string, options?: RequestInit): Promise<readChapterByIdChaptersChapterIdGetResponse> => {

  const res = await fetch(getReadChapterByIdChaptersChapterIdGetUrl(chapterId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChapterByIdChaptersChapterIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChapterByIdChaptersChapterIdGetResponse
}


export type updateChapterChaptersChapterIdPatchResponse200 = {
  data: Chapter
  status: 200
}

export type updateChapterChaptersChapterIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateChapterChaptersChapterIdPatchResponseSuccess = (updateChapterChaptersChapterIdPatchResponse200) & {
  headers: Headers;
};
export type updateChapterChaptersChapterIdPatchResponseError = (updateChapterChaptersChapterIdPatchResponse422) & {
  headers: Headers;
};

export type updateChapterChaptersChapterIdPatchResponse = (updateChapterChaptersChapterIdPatchResponseSuccess | updateChapterChaptersChapterIdPatchResponseError)

export const getUpdateChapterChaptersChapterIdPatchUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}`
}

/**
 * Update chapter metadata.
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 *     400: Field in request too long.
 * @summary Update Chapter
 */
export const updateChapterChaptersChapterIdPatch = async (chapterId: string,
    updateChapter: UpdateChapter, options?: RequestInit): Promise<updateChapterChaptersChapterIdPatchResponse> => {

  const res = await fetch(getUpdateChapterChaptersChapterIdPatchUrl(chapterId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateChapter)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateChapterChaptersChapterIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateChapterChaptersChapterIdPatchResponse
}


export type readChapterContentChaptersChapterIdContentGetResponse200 = {
  data: ChapterContent
  status: 200
}

export type readChapterContentChaptersChapterIdContentGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChapterContentChaptersChapterIdContentGetResponseSuccess = (readChapterContentChaptersChapterIdContentGetResponse200) & {
  headers: Headers;
};
export type readChapterContentChaptersChapterIdContentGetResponseError = (readChapterContentChaptersChapterIdContentGetResponse422) & {
  headers: Headers;
};

export type readChapterContentChaptersChapterIdContentGetResponse = (readChapterContentChaptersChapterIdContentGetResponseSuccess | readChapterContentChaptersChapterIdContentGetResponseError)

export const getReadChapterContentChaptersChapterIdContentGetUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}/content`
}

/**
 * Endpoint for retrieving the most recent content of a chapter.
 *
 * Raises:
 *     404: Chapter not found, or chapter has no content.
 * @summary Read Chapter Content
 */
export const readChapterContentChaptersChapterIdContentGet = async (chapterId: string, options?: RequestInit): Promise<readChapterContentChaptersChapterIdContentGetResponse> => {

  const res = await fetch(getReadChapterContentChaptersChapterIdContentGetUrl(chapterId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChapterContentChaptersChapterIdContentGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChapterContentChaptersChapterIdContentGetResponse
}


export type updateChapterContentChaptersChapterIdContentPatchResponse200 = {
  data: ModifyChapterContentResponse
  status: 200
}

export type updateChapterContentChaptersChapterIdContentPatchResponse401 = {
  data: DetailHTTPErrorResponse
  status: 401
}

export type updateChapterContentChaptersChapterIdContentPatchResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type updateChapterContentChaptersChapterIdContentPatchResponse409 = {
  data: RequestConflictErrorResponse
  status: 409
}

export type updateChapterContentChaptersChapterIdContentPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateChapterContentChaptersChapterIdContentPatchResponseSuccess = (updateChapterContentChaptersChapterIdContentPatchResponse200) & {
  headers: Headers;
};
export type updateChapterContentChaptersChapterIdContentPatchResponseError = (updateChapterContentChaptersChapterIdContentPatchResponse401 | updateChapterContentChaptersChapterIdContentPatchResponse404 | updateChapterContentChaptersChapterIdContentPatchResponse409 | updateChapterContentChaptersChapterIdContentPatchResponse422) & {
  headers: Headers;
};

export type updateChapterContentChaptersChapterIdContentPatchResponse = (updateChapterContentChaptersChapterIdContentPatchResponseSuccess | updateChapterContentChaptersChapterIdContentPatchResponseError)

export const getUpdateChapterContentChaptersChapterIdContentPatchUrl = (chapterId: string,
    params?: UpdateChapterContentChaptersChapterIdContentPatchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/chapters/${chapterId}/content?${stringifiedParams}` : `/chapters/${chapterId}/content`
}

/**
 * Apply text operations to the most recent content of a chapter. Uses optimistic concurrency
 * via chapter_content_id -- if the content has been modified since the client last fetched it,
 * a 409 is returned.
 *
 * Raises:
 *     404: Chapter content not found.
 *     409: Chapter content is outdated (someone else modified it).
 *     401: Insufficient permissions to modify this chapter.
 * @summary Update Chapter Content
 */
export const updateChapterContentChaptersChapterIdContentPatch = async (chapterId: string,
    updateChapterContent: UpdateChapterContent,
    params?: UpdateChapterContentChaptersChapterIdContentPatchParams, options?: RequestInit): Promise<updateChapterContentChaptersChapterIdContentPatchResponse> => {

  const res = await fetch(getUpdateChapterContentChaptersChapterIdContentPatchUrl(chapterId,params),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateChapterContent)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateChapterContentChaptersChapterIdContentPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateChapterContentChaptersChapterIdContentPatchResponse
}


export type readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse200 = {
  data: OperationStatus
  status: 200
}

export type readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponseSuccess = (readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse200) & {
  headers: Headers;
};
export type readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponseError = (readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse422) & {
  headers: Headers;
};

export type readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse = (readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponseSuccess | readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponseError)

export const getReadChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetUrl = (chapterId: string,
    chapterContentId: string,) => {




  return `/chapters/${chapterId}/content-status/${chapterContentId}`
}

/**
 * Check whether a chapter_content_id is the latest version for a chapter.
 *
 * Raises:
 *     404: Chapter content not found (or insufficient read permissions).
 *     409: Chapter content is outdated.
 * @summary Read Chapter Content Status
 */
export const readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGet = async (chapterId: string,
    chapterContentId: string, options?: RequestInit): Promise<readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse> => {

  const res = await fetch(getReadChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetUrl(chapterId,chapterContentId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChapterContentStatusChaptersChapterIdContentStatusChapterContentIdGetResponse
}


export type readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse200 = {
  data: ChapterContentMeta[]
  status: 200
}

export type readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readChapterContentVersionsChaptersChapterIdContentVersionsGetResponseSuccess = (readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse200) & {
  headers: Headers;
};
export type readChapterContentVersionsChaptersChapterIdContentVersionsGetResponseError = (readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse422) & {
  headers: Headers;
};

export type readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse = (readChapterContentVersionsChaptersChapterIdContentVersionsGetResponseSuccess | readChapterContentVersionsChaptersChapterIdContentVersionsGetResponseError)

export const getReadChapterContentVersionsChaptersChapterIdContentVersionsGetUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}/content-versions`
}

/**
 * Endpoint for retrieving all content version metadata for a chapter.
 * Returns an empty list if the chapter has no content versions or doesn't exist.
 * @summary Read Chapter Content Versions
 */
export const readChapterContentVersionsChaptersChapterIdContentVersionsGet = async (chapterId: string, options?: RequestInit): Promise<readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse> => {

  const res = await fetch(getReadChapterContentVersionsChaptersChapterIdContentVersionsGetUrl(chapterId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readChapterContentVersionsChaptersChapterIdContentVersionsGetResponse
}


export type actionPublishChapterChaptersChapterIdPublishPostResponse200 = {
  data: Chapter
  status: 200
}

export type actionPublishChapterChaptersChapterIdPublishPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type actionPublishChapterChaptersChapterIdPublishPostResponseSuccess = (actionPublishChapterChaptersChapterIdPublishPostResponse200) & {
  headers: Headers;
};
export type actionPublishChapterChaptersChapterIdPublishPostResponseError = (actionPublishChapterChaptersChapterIdPublishPostResponse422) & {
  headers: Headers;
};

export type actionPublishChapterChaptersChapterIdPublishPostResponse = (actionPublishChapterChaptersChapterIdPublishPostResponseSuccess | actionPublishChapterChaptersChapterIdPublishPostResponseError)

export const getActionPublishChapterChaptersChapterIdPublishPostUrl = (chapterId: string,) => {




  return `/chapters/${chapterId}/publish`
}

/**
 * Publish a chapter (make it public).
 *
 * Raises:
 *     404: Chapter not found.
 *     401: Insufficient permissions.
 * @summary Action Publish Chapter
 */
export const actionPublishChapterChaptersChapterIdPublishPost = async (chapterId: string, options?: RequestInit): Promise<actionPublishChapterChaptersChapterIdPublishPostResponse> => {

  const res = await fetch(getActionPublishChapterChaptersChapterIdPublishPostUrl(chapterId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: actionPublishChapterChaptersChapterIdPublishPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as actionPublishChapterChaptersChapterIdPublishPostResponse
}


export type readEditChapterDataEditChapterDataChapterIdGetResponse200 = {
  data: EditChapterData
  status: 200
}

export type readEditChapterDataEditChapterDataChapterIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readEditChapterDataEditChapterDataChapterIdGetResponseSuccess = (readEditChapterDataEditChapterDataChapterIdGetResponse200) & {
  headers: Headers;
};
export type readEditChapterDataEditChapterDataChapterIdGetResponseError = (readEditChapterDataEditChapterDataChapterIdGetResponse422) & {
  headers: Headers;
};

export type readEditChapterDataEditChapterDataChapterIdGetResponse = (readEditChapterDataEditChapterDataChapterIdGetResponseSuccess | readEditChapterDataEditChapterDataChapterIdGetResponseError)

export const getReadEditChapterDataEditChapterDataChapterIdGetUrl = (chapterId: string,
    params: ReadEditChapterDataEditChapterDataChapterIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/edit-chapter-data/${chapterId}?${stringifiedParams}` : `/edit-chapter-data/${chapterId}`
}

/**
 * Gets all data associated with a chapter required for editing.
 *
 * Args:
 *     chapter_id: Chapter id of requested chapter
 *     eager: List of label group IDs for which to fetch eager label data
 *
 * Raises:
 *     404: Chapter not found (or insufficient permissions).
 *     403: Insufficient permissions to access data for other user.
 * @summary Read Edit Chapter Data
 */
export const readEditChapterDataEditChapterDataChapterIdGet = async (chapterId: string,
    params: ReadEditChapterDataEditChapterDataChapterIdGetParams, options?: RequestInit): Promise<readEditChapterDataEditChapterDataChapterIdGetResponse> => {

  const res = await fetch(getReadEditChapterDataEditChapterDataChapterIdGetUrl(chapterId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readEditChapterDataEditChapterDataChapterIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readEditChapterDataEditChapterDataChapterIdGetResponse
}


export type readFilterSchemasFiltersSchemasGetResponse200 = {
  data: ReadFilterSchemasFiltersSchemasGet200
  status: 200
}

export type readFilterSchemasFiltersSchemasGetResponseSuccess = (readFilterSchemasFiltersSchemasGetResponse200) & {
  headers: Headers;
};
;

export type readFilterSchemasFiltersSchemasGetResponse = (readFilterSchemasFiltersSchemasGetResponseSuccess)

export const getReadFilterSchemasFiltersSchemasGetUrl = () => {




  return `/filters/schemas`
}

/**
 * Retrieves the schemas for all registered filters, including the instance, context, and options schemas for each filter.
 *
 * Returns:
 *     A dictionary mapping filter names to their schema information.
 * @summary Read Filter Schemas
 */
export const readFilterSchemasFiltersSchemasGet = async ( options?: RequestInit): Promise<readFilterSchemasFiltersSchemasGetResponse> => {

  const res = await fetch(getReadFilterSchemasFiltersSchemasGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readFilterSchemasFiltersSchemasGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readFilterSchemasFiltersSchemasGetResponse
}


export type applyFilterFiltersFilterNameApplyPostResponse204 = {
  data: void
  status: 204
}

export type applyFilterFiltersFilterNameApplyPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type applyFilterFiltersFilterNameApplyPostResponseSuccess = (applyFilterFiltersFilterNameApplyPostResponse204) & {
  headers: Headers;
};
export type applyFilterFiltersFilterNameApplyPostResponseError = (applyFilterFiltersFilterNameApplyPostResponse422) & {
  headers: Headers;
};

export type applyFilterFiltersFilterNameApplyPostResponse = (applyFilterFiltersFilterNameApplyPostResponseSuccess | applyFilterFiltersFilterNameApplyPostResponseError)

export const getApplyFilterFiltersFilterNameApplyPostUrl = (filterName: string,) => {




  return `/filters/${filterName}/apply`
}

/**
 * Applies a filter to a label group for a list of instances using specified options.
 *
 * Args:
 *     filter_name: The name of the filter to apply.
 *     body: An InstanceOptions object containing the list of instances and the options for applying the filter. Each instance will be validated against the filter's instance schema, and the options will be validated against the filter's apply filter options schema.
 *     db: Database session for any necessary database access during filter application.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Apply Filter
 */
export const applyFilterFiltersFilterNameApplyPost = async (filterName: string,
    instanceOptions: InstanceOptions, options?: RequestInit): Promise<applyFilterFiltersFilterNameApplyPostResponse> => {

  const res = await fetch(getApplyFilterFiltersFilterNameApplyPostUrl(filterName),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(instanceOptions)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: applyFilterFiltersFilterNameApplyPostResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as applyFilterFiltersFilterNameApplyPostResponse
}


export type readDecisionsFiltersFilterNameDecideInstancesPostResponse200 = {
  data: boolean[]
  status: 200
}

export type readDecisionsFiltersFilterNameDecideInstancesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readDecisionsFiltersFilterNameDecideInstancesPostResponseSuccess = (readDecisionsFiltersFilterNameDecideInstancesPostResponse200) & {
  headers: Headers;
};
export type readDecisionsFiltersFilterNameDecideInstancesPostResponseError = (readDecisionsFiltersFilterNameDecideInstancesPostResponse422) & {
  headers: Headers;
};

export type readDecisionsFiltersFilterNameDecideInstancesPostResponse = (readDecisionsFiltersFilterNameDecideInstancesPostResponseSuccess | readDecisionsFiltersFilterNameDecideInstancesPostResponseError)

export const getReadDecisionsFiltersFilterNameDecideInstancesPostUrl = (filterName: string,) => {




  return `/filters/${filterName}/decide-instances`
}

/**
 * Decides whether instances pass a filter in given contexts using specified options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     body: An InstanceContextOptions object containing the list of instance-context pairs and the options for deciding instances. Each instance and context will be validated against the filter's schemas.
 *     db: Database session for any necessary database access during the decision process.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Decisions
 */
export const readDecisionsFiltersFilterNameDecideInstancesPost = async (filterName: string,
    instanceContextOptions: InstanceContextOptions, options?: RequestInit): Promise<readDecisionsFiltersFilterNameDecideInstancesPostResponse> => {

  const res = await fetch(getReadDecisionsFiltersFilterNameDecideInstancesPostUrl(filterName),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(instanceContextOptions)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readDecisionsFiltersFilterNameDecideInstancesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readDecisionsFiltersFilterNameDecideInstancesPostResponse
}


export type readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse200 = {
  data: unknown[]
  status: 200
}

export type readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseSuccess = (readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse200) & {
  headers: Headers;
};
export type readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseError = (readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse422) & {
  headers: Headers;
};

export type readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse = (readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseSuccess | readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponseError)

export const getReadFlaggedInstancesFiltersFilterNameFlagInstancesPostUrl = (filterName: string,) => {




  return `/filters/${filterName}/flag-instances`
}

/**
 * Flags instances using a specified filter and options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     options: The options for flagging instances, which will be validated against the filter's schema.
 *     db: Database session for any necessary database access during filtering.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Flagged Instances
 */
export const readFlaggedInstancesFiltersFilterNameFlagInstancesPost = async (filterName: string,
    readFlaggedInstancesFiltersFilterNameFlagInstancesPostBody: ReadFlaggedInstancesFiltersFilterNameFlagInstancesPostBody, options?: RequestInit): Promise<readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse> => {

  const res = await fetch(getReadFlaggedInstancesFiltersFilterNameFlagInstancesPostUrl(filterName),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(readFlaggedInstancesFiltersFilterNameFlagInstancesPostBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readFlaggedInstancesFiltersFilterNameFlagInstancesPostResponse
}


export type readContextsFiltersFilterNameGetContextsPostResponse200 = {
  data: unknown[]
  status: 200
}

export type readContextsFiltersFilterNameGetContextsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readContextsFiltersFilterNameGetContextsPostResponseSuccess = (readContextsFiltersFilterNameGetContextsPostResponse200) & {
  headers: Headers;
};
export type readContextsFiltersFilterNameGetContextsPostResponseError = (readContextsFiltersFilterNameGetContextsPostResponse422) & {
  headers: Headers;
};

export type readContextsFiltersFilterNameGetContextsPostResponse = (readContextsFiltersFilterNameGetContextsPostResponseSuccess | readContextsFiltersFilterNameGetContextsPostResponseError)

export const getReadContextsFiltersFilterNameGetContextsPostUrl = (filterName: string,) => {




  return `/filters/${filterName}/get-contexts`
}

/**
 * Retrieves contexts for a list of instances using a specified filter and options.
 *
 * Args:
 *     filter_name: The name of the filter to use.
 *     instances: The list of instances to retrieve contexts for. Each instance will be validated against the filter's instance schema.
 *     options: The options for retrieving contexts, which will be validated against the filter's schema.
 *     db: Database session for any necessary database access during context retrieval.
 *     current_user: The user making the request, which may be relevant for certain filters.
 * @summary Read Contexts
 */
export const readContextsFiltersFilterNameGetContextsPost = async (filterName: string,
    instanceOptions: InstanceOptions, options?: RequestInit): Promise<readContextsFiltersFilterNameGetContextsPostResponse> => {

  const res = await fetch(getReadContextsFiltersFilterNameGetContextsPostUrl(filterName),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(instanceOptions)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readContextsFiltersFilterNameGetContextsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readContextsFiltersFilterNameGetContextsPostResponse
}


export type readLabelDatasByGroupChaptersLabelDatasGetResponse200 = {
  data: LabelData[]
  status: 200
}

export type readLabelDatasByGroupChaptersLabelDatasGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelDatasByGroupChaptersLabelDatasGetResponseSuccess = (readLabelDatasByGroupChaptersLabelDatasGetResponse200) & {
  headers: Headers;
};
export type readLabelDatasByGroupChaptersLabelDatasGetResponseError = (readLabelDatasByGroupChaptersLabelDatasGetResponse422) & {
  headers: Headers;
};

export type readLabelDatasByGroupChaptersLabelDatasGetResponse = (readLabelDatasByGroupChaptersLabelDatasGetResponseSuccess | readLabelDatasByGroupChaptersLabelDatasGetResponseError)

export const getReadLabelDatasByGroupChaptersLabelDatasGetUrl = (params: ReadLabelDatasByGroupChaptersLabelDatasGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-datas?${stringifiedParams}` : `/label-datas`
}

/**
 * Gets all label datas in a label group, optionally filtered by chapter range.
 * @summary Read Label Datas By Group Chapters
 */
export const readLabelDatasByGroupChaptersLabelDatasGet = async (params: ReadLabelDatasByGroupChaptersLabelDatasGetParams, options?: RequestInit): Promise<readLabelDatasByGroupChaptersLabelDatasGetResponse> => {

  const res = await fetch(getReadLabelDatasByGroupChaptersLabelDatasGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelDatasByGroupChaptersLabelDatasGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelDatasByGroupChaptersLabelDatasGetResponse
}


export type readLabelDataLabelDatasLabelDataIdGetResponse200 = {
  data: LabelData
  status: 200
}

export type readLabelDataLabelDatasLabelDataIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelDataLabelDatasLabelDataIdGetResponseSuccess = (readLabelDataLabelDatasLabelDataIdGetResponse200) & {
  headers: Headers;
};
export type readLabelDataLabelDatasLabelDataIdGetResponseError = (readLabelDataLabelDatasLabelDataIdGetResponse422) & {
  headers: Headers;
};

export type readLabelDataLabelDatasLabelDataIdGetResponse = (readLabelDataLabelDatasLabelDataIdGetResponseSuccess | readLabelDataLabelDatasLabelDataIdGetResponseError)

export const getReadLabelDataLabelDatasLabelDataIdGetUrl = (labelDataId: string,) => {




  return `/label-datas/${labelDataId}`
}

/**
 * Gets a label data by id.
 *
 * Raises:
 *     404: Label data not found (or insufficient permissions).
 * @summary Read Label Data
 */
export const readLabelDataLabelDatasLabelDataIdGet = async (labelDataId: string, options?: RequestInit): Promise<readLabelDataLabelDatasLabelDataIdGetResponse> => {

  const res = await fetch(getReadLabelDataLabelDatasLabelDataIdGetUrl(labelDataId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelDataLabelDatasLabelDataIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelDataLabelDatasLabelDataIdGetResponse
}


export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse204 = {
  data: void
  status: 204
}

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse409 = {
  data: RequestConflictErrorResponse
  status: 409
}

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponseSuccess = (updateLabelDataStreamLabelDatasLabelDataIdPatchResponse204) & {
  headers: Headers;
};
export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponseError = (updateLabelDataStreamLabelDatasLabelDataIdPatchResponse400 | updateLabelDataStreamLabelDatasLabelDataIdPatchResponse404 | updateLabelDataStreamLabelDatasLabelDataIdPatchResponse409 | updateLabelDataStreamLabelDatasLabelDataIdPatchResponse422) & {
  headers: Headers;
};

export type updateLabelDataStreamLabelDatasLabelDataIdPatchResponse = (updateLabelDataStreamLabelDatasLabelDataIdPatchResponseSuccess | updateLabelDataStreamLabelDatasLabelDataIdPatchResponseError)

export const getUpdateLabelDataStreamLabelDatasLabelDataIdPatchUrl = (labelDataId: string,
    params?: UpdateLabelDataStreamLabelDatasLabelDataIdPatchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-datas/${labelDataId}?${stringifiedParams}` : `/label-datas/${labelDataId}`
}

/**
 * Applies a stream of edit operations to labels.
 *
 * Raises:
 *     404: Label data or its underlying revision text not found, or target label does not exist.
 *     409: Word mismatch or label overlap detected.
 *     400: Operation positions out of bounds or invalid operation.
 * @summary Update Label Data Stream
 */
export const updateLabelDataStreamLabelDatasLabelDataIdPatch = async (labelDataId: string,
    updateLabelDataStream: UpdateLabelDataStream,
    params?: UpdateLabelDataStreamLabelDatasLabelDataIdPatchParams, options?: RequestInit): Promise<updateLabelDataStreamLabelDatasLabelDataIdPatchResponse> => {

  const res = await fetch(getUpdateLabelDataStreamLabelDatasLabelDataIdPatchUrl(labelDataId,params),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLabelDataStream)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateLabelDataStreamLabelDatasLabelDataIdPatchResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as updateLabelDataStreamLabelDatasLabelDataIdPatchResponse
}


export type readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse200 = {
  data: Label[]
  status: 200
}

export type readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseSuccess = (readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse200) & {
  headers: Headers;
};
export type readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseError = (readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse422) & {
  headers: Headers;
};

export type readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse = (readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseSuccess | readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponseError)

export const getReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetUrl = (labelDataId: string,) => {




  return `/label-datas/${labelDataId}/labels`
}

/**
 * Get the specific list of labels inside a label data entry.
 * @summary Read Labels By Label Data
 */
export const readLabelsByLabelDataLabelDatasLabelDataIdLabelsGet = async (labelDataId: string, options?: RequestInit): Promise<readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse> => {

  const res = await fetch(getReadLabelsByLabelDataLabelDatasLabelDataIdLabelsGetUrl(labelDataId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelsByLabelDataLabelDatasLabelDataIdLabelsGetResponse
}


export type readLabelGroupsLabelGroupsGetResponse200 = {
  data: LabelGroup[]
  status: 200
}

export type readLabelGroupsLabelGroupsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelGroupsLabelGroupsGetResponseSuccess = (readLabelGroupsLabelGroupsGetResponse200) & {
  headers: Headers;
};
export type readLabelGroupsLabelGroupsGetResponseError = (readLabelGroupsLabelGroupsGetResponse422) & {
  headers: Headers;
};

export type readLabelGroupsLabelGroupsGetResponse = (readLabelGroupsLabelGroupsGetResponseSuccess | readLabelGroupsLabelGroupsGetResponseError)

export const getReadLabelGroupsLabelGroupsGetUrl = (params: ReadLabelGroupsLabelGroupsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-groups?${stringifiedParams}` : `/label-groups`
}

/**
 * Gets all label groups of the current user for a novel.
 * @summary Read Label Groups
 */
export const readLabelGroupsLabelGroupsGet = async (params: ReadLabelGroupsLabelGroupsGetParams, options?: RequestInit): Promise<readLabelGroupsLabelGroupsGetResponse> => {

  const res = await fetch(getReadLabelGroupsLabelGroupsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelGroupsLabelGroupsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelGroupsLabelGroupsGetResponse
}


export type createLabelGroupLabelGroupsPostResponse200 = {
  data: LabelGroup
  status: 200
}

export type createLabelGroupLabelGroupsPostResponse400 = {
  data: DetailHTTPErrorResponse
  status: 400
}

export type createLabelGroupLabelGroupsPostResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type createLabelGroupLabelGroupsPostResponse409 = {
  data: RequestConflictErrorResponse
  status: 409
}

export type createLabelGroupLabelGroupsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createLabelGroupLabelGroupsPostResponseSuccess = (createLabelGroupLabelGroupsPostResponse200) & {
  headers: Headers;
};
export type createLabelGroupLabelGroupsPostResponseError = (createLabelGroupLabelGroupsPostResponse400 | createLabelGroupLabelGroupsPostResponse404 | createLabelGroupLabelGroupsPostResponse409 | createLabelGroupLabelGroupsPostResponse422) & {
  headers: Headers;
};

export type createLabelGroupLabelGroupsPostResponse = (createLabelGroupLabelGroupsPostResponseSuccess | createLabelGroupLabelGroupsPostResponseError)

export const getCreateLabelGroupLabelGroupsPostUrl = (params?: CreateLabelGroupLabelGroupsPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-groups?${stringifiedParams}` : `/label-groups`
}

/**
 * Creates a new label group.
 *
 * Raises:
 *     404: Novel not found.
 *     400: Label group name is too long.
 * @summary Create Label Group
 */
export const createLabelGroupLabelGroupsPost = async (createLabelGroup: CreateLabelGroup,
    params?: CreateLabelGroupLabelGroupsPostParams, options?: RequestInit): Promise<createLabelGroupLabelGroupsPostResponse> => {

  const res = await fetch(getCreateLabelGroupLabelGroupsPostUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLabelGroup)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLabelGroupLabelGroupsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLabelGroupLabelGroupsPostResponse
}


export type readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse200 = {
  data: LabelGroupWithRole[]
  status: 200
}

export type readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelGroupsWithRoleLabelGroupsWithRoleGetResponseSuccess = (readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse200) & {
  headers: Headers;
};
export type readLabelGroupsWithRoleLabelGroupsWithRoleGetResponseError = (readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse422) & {
  headers: Headers;
};

export type readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse = (readLabelGroupsWithRoleLabelGroupsWithRoleGetResponseSuccess | readLabelGroupsWithRoleLabelGroupsWithRoleGetResponseError)

export const getReadLabelGroupsWithRoleLabelGroupsWithRoleGetUrl = (params: ReadLabelGroupsWithRoleLabelGroupsWithRoleGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-groups-with-role?${stringifiedParams}` : `/label-groups-with-role`
}

/**
 * Gets all label groups of the current user for a novel, along with their roles.
 * @summary Read Label Groups With Role
 */
export const readLabelGroupsWithRoleLabelGroupsWithRoleGet = async (params: ReadLabelGroupsWithRoleLabelGroupsWithRoleGetParams, options?: RequestInit): Promise<readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse> => {

  const res = await fetch(getReadLabelGroupsWithRoleLabelGroupsWithRoleGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelGroupsWithRoleLabelGroupsWithRoleGetResponse
}


export type readLabelGroupLabelGroupsLabelGroupIdGetResponse200 = {
  data: LabelGroup
  status: 200
}

export type readLabelGroupLabelGroupsLabelGroupIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelGroupLabelGroupsLabelGroupIdGetResponseSuccess = (readLabelGroupLabelGroupsLabelGroupIdGetResponse200) & {
  headers: Headers;
};
export type readLabelGroupLabelGroupsLabelGroupIdGetResponseError = (readLabelGroupLabelGroupsLabelGroupIdGetResponse422) & {
  headers: Headers;
};

export type readLabelGroupLabelGroupsLabelGroupIdGetResponse = (readLabelGroupLabelGroupsLabelGroupIdGetResponseSuccess | readLabelGroupLabelGroupsLabelGroupIdGetResponseError)

export const getReadLabelGroupLabelGroupsLabelGroupIdGetUrl = (labelGroupId: string,) => {




  return `/label-groups/${labelGroupId}`
}

/**
 * Gets a label group by id.
 *
 * Raises:
 *     404: Label group not found (or insufficient permissions).
 * @summary Read Label Group
 */
export const readLabelGroupLabelGroupsLabelGroupIdGet = async (labelGroupId: string, options?: RequestInit): Promise<readLabelGroupLabelGroupsLabelGroupIdGetResponse> => {

  const res = await fetch(getReadLabelGroupLabelGroupsLabelGroupIdGetUrl(labelGroupId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelGroupLabelGroupsLabelGroupIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelGroupLabelGroupsLabelGroupIdGetResponse
}


export type updateLabelGroupLabelGroupsLabelGroupIdPatchResponse200 = {
  data: LabelGroup
  status: 200
}

export type updateLabelGroupLabelGroupsLabelGroupIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateLabelGroupLabelGroupsLabelGroupIdPatchResponseSuccess = (updateLabelGroupLabelGroupsLabelGroupIdPatchResponse200) & {
  headers: Headers;
};
export type updateLabelGroupLabelGroupsLabelGroupIdPatchResponseError = (updateLabelGroupLabelGroupsLabelGroupIdPatchResponse422) & {
  headers: Headers;
};

export type updateLabelGroupLabelGroupsLabelGroupIdPatchResponse = (updateLabelGroupLabelGroupsLabelGroupIdPatchResponseSuccess | updateLabelGroupLabelGroupsLabelGroupIdPatchResponseError)

export const getUpdateLabelGroupLabelGroupsLabelGroupIdPatchUrl = (labelGroupId: string,) => {




  return `/label-groups/${labelGroupId}`
}

/**
 * Updates a label group (e.g. rename).
 *
 * Raises:
 *     404: Label group not found.
 *     400: Label group name is too long.
 * @summary Update Label Group
 */
export const updateLabelGroupLabelGroupsLabelGroupIdPatch = async (labelGroupId: string,
    updateLabelGroup: UpdateLabelGroup, options?: RequestInit): Promise<updateLabelGroupLabelGroupsLabelGroupIdPatchResponse> => {

  const res = await fetch(getUpdateLabelGroupLabelGroupsLabelGroupIdPatchUrl(labelGroupId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLabelGroup)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateLabelGroupLabelGroupsLabelGroupIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateLabelGroupLabelGroupsLabelGroupIdPatchResponse
}


export type readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse200 = {
  data: LabelContributor[]
  status: 200
}

export type readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseSuccess = (readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse200) & {
  headers: Headers;
};
export type readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseError = (readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse422) & {
  headers: Headers;
};

export type readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse = (readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseSuccess | readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponseError)

export const getReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetUrl = (labelGroupId: string,) => {




  return `/label-groups/${labelGroupId}/contributors`
}

/**
 * Get the list of contributors for a label group.
 * @summary Read Label Contributors
 */
export const readLabelContributorsLabelGroupsLabelGroupIdContributorsGet = async (labelGroupId: string, options?: RequestInit): Promise<readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse> => {

  const res = await fetch(getReadLabelContributorsLabelGroupsLabelGroupIdContributorsGetUrl(labelGroupId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLabelContributorsLabelGroupsLabelGroupIdContributorsGetResponse
}


export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse200 = {
  data: LabelData
  status: 200
}

export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse404 = {
  data: DetailHTTPErrorResponse
  status: 404
}

export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse409 = {
  data: RequestConflictErrorResponse
  status: 409
}

export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponseSuccess = (createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse200) & {
  headers: Headers;
};
export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponseError = (createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse404 | createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse409 | createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse422) & {
  headers: Headers;
};

export type createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse = (createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponseSuccess | createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponseError)

export const getCreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostUrl = (labelGroupId: string,
    params?: CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/label-groups/${labelGroupId}/label-datas?${stringifiedParams}` : `/label-groups/${labelGroupId}/label-datas`
}

/**
 * Creates a label data entry for a revision text in a label group.
 *
 * Raises:
 *     404: Label group or revision text not found.
 *     409: Label data for this revision text already exists in this group.
 * @summary Create Label Data
 */
export const createLabelDataLabelGroupsLabelGroupIdLabelDatasPost = async (labelGroupId: string,
    createLabelData: CreateLabelData,
    params?: CreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostParams, options?: RequestInit): Promise<createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse> => {

  const res = await fetch(getCreateLabelDataLabelGroupsLabelGroupIdLabelDatasPostUrl(labelGroupId,params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLabelData)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLabelDataLabelGroupsLabelGroupIdLabelDatasPostResponse
}


export type createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse200 = {
  data: CreateLabelDataByAutoLabelStatus
  status: 200
}

export type createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponseSuccess = (createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse200) & {
  headers: Headers;
};
export type createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponseError = (createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse422) & {
  headers: Headers;
};

export type createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse = (createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponseSuccess | createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponseError)

export const getCreateLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostUrl = (labelGroupId: string,) => {




  return `/label-groups/${labelGroupId}/label-datas/auto-labels`
}

/**
 * Creates label datas and populates labels from autolabel results.
 * @summary Create Label Datas By Auto Labels
 */
export const createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPost = async (labelGroupId: string,
    createLabelDataByAutoLabel: CreateLabelDataByAutoLabel, options?: RequestInit): Promise<createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse> => {

  const res = await fetch(getCreateLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostUrl(labelGroupId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLabelDataByAutoLabel)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLabelDatasByAutoLabelsLabelGroupsLabelGroupIdLabelDatasAutoLabelsPostResponse
}


export type readAllLanguagesLanguagesGetResponse200 = {
  data: Language[]
  status: 200
}

export type readAllLanguagesLanguagesGetResponseSuccess = (readAllLanguagesLanguagesGetResponse200) & {
  headers: Headers;
};
;

export type readAllLanguagesLanguagesGetResponse = (readAllLanguagesLanguagesGetResponseSuccess)

export const getReadAllLanguagesLanguagesGetUrl = () => {




  return `/languages`
}

/**
 * Retrieves all languages in the database.
 *
 * Args:
 *     db: Database session.
 * @summary Read All Languages
 */
export const readAllLanguagesLanguagesGet = async ( options?: RequestInit): Promise<readAllLanguagesLanguagesGetResponse> => {

  const res = await fetch(getReadAllLanguagesLanguagesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readAllLanguagesLanguagesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readAllLanguagesLanguagesGetResponse
}


export type readLanguageByCodeLanguagesLanguageCodeGetResponse200 = {
  data: Language
  status: 200
}

export type readLanguageByCodeLanguagesLanguageCodeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readLanguageByCodeLanguagesLanguageCodeGetResponseSuccess = (readLanguageByCodeLanguagesLanguageCodeGetResponse200) & {
  headers: Headers;
};
export type readLanguageByCodeLanguagesLanguageCodeGetResponseError = (readLanguageByCodeLanguagesLanguageCodeGetResponse422) & {
  headers: Headers;
};

export type readLanguageByCodeLanguagesLanguageCodeGetResponse = (readLanguageByCodeLanguagesLanguageCodeGetResponseSuccess | readLanguageByCodeLanguagesLanguageCodeGetResponseError)

export const getReadLanguageByCodeLanguagesLanguageCodeGetUrl = (languageCode: string,) => {




  return `/languages/${languageCode}`
}

/**
 * Retrieves a language by its code.
 *
 * Args:
 *     language_code: The code of the language to retrieve.
 *     db: Database session.
 * @summary Read Language By Code
 */
export const readLanguageByCodeLanguagesLanguageCodeGet = async (languageCode: string, options?: RequestInit): Promise<readLanguageByCodeLanguagesLanguageCodeGetResponse> => {

  const res = await fetch(getReadLanguageByCodeLanguagesLanguageCodeGetUrl(languageCode),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readLanguageByCodeLanguagesLanguageCodeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readLanguageByCodeLanguagesLanguageCodeGetResponse
}


export type readNovelsNovelsGetResponse200 = {
  data: Novel[]
  status: 200
}

export type readNovelsNovelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readNovelsNovelsGetResponseSuccess = (readNovelsNovelsGetResponse200) & {
  headers: Headers;
};
export type readNovelsNovelsGetResponseError = (readNovelsNovelsGetResponse422) & {
  headers: Headers;
};

export type readNovelsNovelsGetResponse = (readNovelsNovelsGetResponseSuccess | readNovelsNovelsGetResponseError)

export const getReadNovelsNovelsGetUrl = (params?: ReadNovelsNovelsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/novels?${stringifiedParams}` : `/novels`
}

/**
 * Endpoint for retrieving novels in bulk.
 * @summary Read Novels
 */
export const readNovelsNovelsGet = async (params?: ReadNovelsNovelsGetParams, options?: RequestInit): Promise<readNovelsNovelsGetResponse> => {

  const res = await fetch(getReadNovelsNovelsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readNovelsNovelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readNovelsNovelsGetResponse
}


export type createNovelNovelsPostResponse200 = {
  data: Novel
  status: 200
}

export type createNovelNovelsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createNovelNovelsPostResponseSuccess = (createNovelNovelsPostResponse200) & {
  headers: Headers;
};
export type createNovelNovelsPostResponseError = (createNovelNovelsPostResponse422) & {
  headers: Headers;
};

export type createNovelNovelsPostResponse = (createNovelNovelsPostResponseSuccess | createNovelNovelsPostResponseError)

export const getCreateNovelNovelsPostUrl = () => {




  return `/novels`
}

/**
 * Add a new novel to the database.
 *
 * Raises:
 *     404: Language code or source work not found.
 *     400: Data in some field is too long.
 * @summary Create Novel
 */
export const createNovelNovelsPost = async (createNovel: CreateNovel, options?: RequestInit): Promise<createNovelNovelsPostResponse> => {

  const res = await fetch(getCreateNovelNovelsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNovel)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createNovelNovelsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createNovelNovelsPostResponse
}


export type readNovelsMineNovelsMineGetResponse200 = {
  data: Novel[]
  status: 200
}

export type readNovelsMineNovelsMineGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readNovelsMineNovelsMineGetResponseSuccess = (readNovelsMineNovelsMineGetResponse200) & {
  headers: Headers;
};
export type readNovelsMineNovelsMineGetResponseError = (readNovelsMineNovelsMineGetResponse422) & {
  headers: Headers;
};

export type readNovelsMineNovelsMineGetResponse = (readNovelsMineNovelsMineGetResponseSuccess | readNovelsMineNovelsMineGetResponseError)

export const getReadNovelsMineNovelsMineGetUrl = (params?: ReadNovelsMineNovelsMineGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/novels/mine?${stringifiedParams}` : `/novels/mine`
}

/**
 * Endpoint for retrieving novels that the user has special access to.
 * @summary Read Novels Mine
 */
export const readNovelsMineNovelsMineGet = async (params?: ReadNovelsMineNovelsMineGetParams, options?: RequestInit): Promise<readNovelsMineNovelsMineGetResponse> => {

  const res = await fetch(getReadNovelsMineNovelsMineGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readNovelsMineNovelsMineGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readNovelsMineNovelsMineGetResponse
}


export type readNovelNovelsNovelIdGetResponse200 = {
  data: Novel
  status: 200
}

export type readNovelNovelsNovelIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readNovelNovelsNovelIdGetResponseSuccess = (readNovelNovelsNovelIdGetResponse200) & {
  headers: Headers;
};
export type readNovelNovelsNovelIdGetResponseError = (readNovelNovelsNovelIdGetResponse422) & {
  headers: Headers;
};

export type readNovelNovelsNovelIdGetResponse = (readNovelNovelsNovelIdGetResponseSuccess | readNovelNovelsNovelIdGetResponseError)

export const getReadNovelNovelsNovelIdGetUrl = (novelId: string,) => {




  return `/novels/${novelId}`
}

/**
 * Endpoint for retrieving a novel by id.
 *
 * Raises:
 *     404: Novel not found (or insufficient permissions).
 * @summary Read Novel
 */
export const readNovelNovelsNovelIdGet = async (novelId: string, options?: RequestInit): Promise<readNovelNovelsNovelIdGetResponse> => {

  const res = await fetch(getReadNovelNovelsNovelIdGetUrl(novelId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readNovelNovelsNovelIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readNovelNovelsNovelIdGetResponse
}


export type updateNovelNovelsNovelIdPatchResponse200 = {
  data: Novel
  status: 200
}

export type updateNovelNovelsNovelIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateNovelNovelsNovelIdPatchResponseSuccess = (updateNovelNovelsNovelIdPatchResponse200) & {
  headers: Headers;
};
export type updateNovelNovelsNovelIdPatchResponseError = (updateNovelNovelsNovelIdPatchResponse422) & {
  headers: Headers;
};

export type updateNovelNovelsNovelIdPatchResponse = (updateNovelNovelsNovelIdPatchResponseSuccess | updateNovelNovelsNovelIdPatchResponseError)

export const getUpdateNovelNovelsNovelIdPatchUrl = (novelId: string,) => {




  return `/novels/${novelId}`
}

/**
 * Update the novel with novel_id.
 *
 * Raises:
 *     404: Novel not found.
 *     401: Insufficient permissions (user is not owner/editor).
 *     400: Data in some field exceeds maximum length.
 * @summary Update Novel
 */
export const updateNovelNovelsNovelIdPatch = async (novelId: string,
    updateNovel: UpdateNovel, options?: RequestInit): Promise<updateNovelNovelsNovelIdPatchResponse> => {

  const res = await fetch(getUpdateNovelNovelsNovelIdPatchUrl(novelId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNovel)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateNovelNovelsNovelIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateNovelNovelsNovelIdPatchResponse
}


export type createChapterNovelsNovelIdChaptersPostResponse200 = {
  data: ChapterData
  status: 200
}

export type createChapterNovelsNovelIdChaptersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createChapterNovelsNovelIdChaptersPostResponseSuccess = (createChapterNovelsNovelIdChaptersPostResponse200) & {
  headers: Headers;
};
export type createChapterNovelsNovelIdChaptersPostResponseError = (createChapterNovelsNovelIdChaptersPostResponse422) & {
  headers: Headers;
};

export type createChapterNovelsNovelIdChaptersPostResponse = (createChapterNovelsNovelIdChaptersPostResponseSuccess | createChapterNovelsNovelIdChaptersPostResponseError)

export const getCreateChapterNovelsNovelIdChaptersPostUrl = (novelId: string,) => {




  return `/novels/${novelId}/chapters`
}

/**
 * Insert a new chapter into the database. Returns chapter metadata and initial empty content.
 *
 * Raises:
 *     404: Novel not found.
 *     409: Chapter with this chapter number already exists in this novel.
 *     401: Insufficient permissions.
 * @summary Create Chapter
 */
export const createChapterNovelsNovelIdChaptersPost = async (novelId: string,
    createChapter: CreateChapter, options?: RequestInit): Promise<createChapterNovelsNovelIdChaptersPostResponse> => {

  const res = await fetch(getCreateChapterNovelsNovelIdChaptersPostUrl(novelId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createChapter)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createChapterNovelsNovelIdChaptersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createChapterNovelsNovelIdChaptersPostResponse
}


export type registerUserRegisterPostResponse200 = {
  data: User
  status: 200
}

export type registerUserRegisterPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerUserRegisterPostResponseSuccess = (registerUserRegisterPostResponse200) & {
  headers: Headers;
};
export type registerUserRegisterPostResponseError = (registerUserRegisterPostResponse422) & {
  headers: Headers;
};

export type registerUserRegisterPostResponse = (registerUserRegisterPostResponseSuccess | registerUserRegisterPostResponseError)

export const getRegisterUserRegisterPostUrl = () => {




  return `/register`
}

/**
 * Endpoint for registering a new user. Client with registration request must not be logged in.
 *
 * Args:
 *     request: Create user request.
 *     db: Database dependency.
 *     current_user: Optional user dependency. Should be None for this function to succeed.
 * @summary Register User
 */
export const registerUserRegisterPost = async (createUser: CreateUser, options?: RequestInit): Promise<registerUserRegisterPostResponse> => {

  const res = await fetch(getRegisterUserRegisterPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUser)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserRegisterPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUserRegisterPostResponse
}


export type readSourceWorksSourceWorksGetResponse200 = {
  data: SourceWorkDataOutput[]
  status: 200
}

export type readSourceWorksSourceWorksGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readSourceWorksSourceWorksGetResponseSuccess = (readSourceWorksSourceWorksGetResponse200) & {
  headers: Headers;
};
export type readSourceWorksSourceWorksGetResponseError = (readSourceWorksSourceWorksGetResponse422) & {
  headers: Headers;
};

export type readSourceWorksSourceWorksGetResponse = (readSourceWorksSourceWorksGetResponseSuccess | readSourceWorksSourceWorksGetResponseError)

export const getReadSourceWorksSourceWorksGetUrl = (params?: ReadSourceWorksSourceWorksGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/source-works?${stringifiedParams}` : `/source-works`
}

/**
 * Endpoint for retrieving source works in bulk, optionally filtered by title substring.
 * @summary Read Source Works
 */
export const readSourceWorksSourceWorksGet = async (params?: ReadSourceWorksSourceWorksGetParams, options?: RequestInit): Promise<readSourceWorksSourceWorksGetResponse> => {

  const res = await fetch(getReadSourceWorksSourceWorksGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readSourceWorksSourceWorksGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readSourceWorksSourceWorksGetResponse
}


export type createSourceWorkSourceWorksPostResponse200 = {
  data: SourceWork
  status: 200
}

export type createSourceWorkSourceWorksPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createSourceWorkSourceWorksPostResponseSuccess = (createSourceWorkSourceWorksPostResponse200) & {
  headers: Headers;
};
export type createSourceWorkSourceWorksPostResponseError = (createSourceWorkSourceWorksPostResponse422) & {
  headers: Headers;
};

export type createSourceWorkSourceWorksPostResponse = (createSourceWorkSourceWorksPostResponseSuccess | createSourceWorkSourceWorksPostResponseError)

export const getCreateSourceWorkSourceWorksPostUrl = () => {




  return `/source-works`
}

/**
 * Create a new source work.
 *
 * Raises:
 *     400: Data in some field is too long.
 * @summary Create Source Work
 */
export const createSourceWorkSourceWorksPost = async (createSourceWork: CreateSourceWork, options?: RequestInit): Promise<createSourceWorkSourceWorksPostResponse> => {

  const res = await fetch(getCreateSourceWorkSourceWorksPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSourceWork)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSourceWorkSourceWorksPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSourceWorkSourceWorksPostResponse
}


export type readSourceWorkSourceWorksSourceWorkIdGetResponse200 = {
  data: SourceWork
  status: 200
}

export type readSourceWorkSourceWorksSourceWorkIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readSourceWorkSourceWorksSourceWorkIdGetResponseSuccess = (readSourceWorkSourceWorksSourceWorkIdGetResponse200) & {
  headers: Headers;
};
export type readSourceWorkSourceWorksSourceWorkIdGetResponseError = (readSourceWorkSourceWorksSourceWorkIdGetResponse422) & {
  headers: Headers;
};

export type readSourceWorkSourceWorksSourceWorkIdGetResponse = (readSourceWorkSourceWorksSourceWorkIdGetResponseSuccess | readSourceWorkSourceWorksSourceWorkIdGetResponseError)

export const getReadSourceWorkSourceWorksSourceWorkIdGetUrl = (sourceWorkId: string,) => {




  return `/source-works/${sourceWorkId}`
}

/**
 * Endpoint for retrieving a source work by id.
 *
 * Raises:
 *     404: Source work not found (or insufficient permissions).
 * @summary Read Source Work
 */
export const readSourceWorkSourceWorksSourceWorkIdGet = async (sourceWorkId: string, options?: RequestInit): Promise<readSourceWorkSourceWorksSourceWorkIdGetResponse> => {

  const res = await fetch(getReadSourceWorkSourceWorksSourceWorkIdGetUrl(sourceWorkId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readSourceWorkSourceWorksSourceWorkIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readSourceWorkSourceWorksSourceWorkIdGetResponse
}


export type updateSourceWorkSourceWorksSourceWorkIdPatchResponse200 = {
  data: SourceWork
  status: 200
}

export type updateSourceWorkSourceWorksSourceWorkIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateSourceWorkSourceWorksSourceWorkIdPatchResponseSuccess = (updateSourceWorkSourceWorksSourceWorkIdPatchResponse200) & {
  headers: Headers;
};
export type updateSourceWorkSourceWorksSourceWorkIdPatchResponseError = (updateSourceWorkSourceWorksSourceWorkIdPatchResponse422) & {
  headers: Headers;
};

export type updateSourceWorkSourceWorksSourceWorkIdPatchResponse = (updateSourceWorkSourceWorksSourceWorkIdPatchResponseSuccess | updateSourceWorkSourceWorksSourceWorkIdPatchResponseError)

export const getUpdateSourceWorkSourceWorksSourceWorkIdPatchUrl = (sourceWorkId: string,) => {




  return `/source-works/${sourceWorkId}`
}

/**
 * Update a source work's metadata.
 *
 * Raises:
 *     404: Source work not found.
 *     401: Insufficient permissions.
 *     400: Data in some field exceeds maximum length.
 * @summary Update Source Work
 */
export const updateSourceWorkSourceWorksSourceWorkIdPatch = async (sourceWorkId: string,
    updateSourceWork: UpdateSourceWork, options?: RequestInit): Promise<updateSourceWorkSourceWorksSourceWorkIdPatchResponse> => {

  const res = await fetch(getUpdateSourceWorkSourceWorksSourceWorkIdPatchUrl(sourceWorkId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSourceWork)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateSourceWorkSourceWorksSourceWorkIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateSourceWorkSourceWorksSourceWorkIdPatchResponse
}


export type readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse200 = {
  data: Novel[]
  status: 200
}

export type readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseSuccess = (readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse200) & {
  headers: Headers;
};
export type readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseError = (readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse422) & {
  headers: Headers;
};

export type readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse = (readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseSuccess | readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponseError)

export const getReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetUrl = (sourceWorkId: string,) => {




  return `/source-works/${sourceWorkId}/novels`
}

/**
 * Endpoint for retrieving novels belonging to a source work.
 *
 * Raises:
 *     404: Source work not found (or insufficient permissions).
 * @summary Read Novels By Source Work
 */
export const readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGet = async (sourceWorkId: string, options?: RequestInit): Promise<readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse> => {

  const res = await fetch(getReadNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetUrl(sourceWorkId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readNovelsBySourceWorkSourceWorksSourceWorkIdNovelsGetResponse
}


export type loginForAccessTokenTokenPostResponse200 = {
  data: Token
  status: 200
}

export type loginForAccessTokenTokenPostResponse401 = {
  data: void
  status: 401
}

export type loginForAccessTokenTokenPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginForAccessTokenTokenPostResponseSuccess = (loginForAccessTokenTokenPostResponse200) & {
  headers: Headers;
};
export type loginForAccessTokenTokenPostResponseError = (loginForAccessTokenTokenPostResponse401 | loginForAccessTokenTokenPostResponse422) & {
  headers: Headers;
};

export type loginForAccessTokenTokenPostResponse = (loginForAccessTokenTokenPostResponseSuccess | loginForAccessTokenTokenPostResponseError)

export const getLoginForAccessTokenTokenPostUrl = () => {




  return `/token`
}

/**
 * Verifies a client's login request and returns a token if it succeeds.
 *
 * Args:
 *     db: Database dependency.
 *     form_data: OAuth2PasswordRequestForm dependency.
 * @summary Login For Access Token
 */
export const loginForAccessTokenTokenPost = async (bodyLoginForAccessTokenTokenPost: BodyLoginForAccessTokenTokenPost, options?: RequestInit): Promise<loginForAccessTokenTokenPostResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginForAccessTokenTokenPost.client_id !== undefined && bodyLoginForAccessTokenTokenPost.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginForAccessTokenTokenPost.client_id);
 }
if(bodyLoginForAccessTokenTokenPost.client_secret !== undefined && bodyLoginForAccessTokenTokenPost.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginForAccessTokenTokenPost.client_secret);
 }
if(bodyLoginForAccessTokenTokenPost.grant_type !== undefined && bodyLoginForAccessTokenTokenPost.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginForAccessTokenTokenPost.grant_type);
 }
formUrlEncoded.append(`password`, bodyLoginForAccessTokenTokenPost.password);
if(bodyLoginForAccessTokenTokenPost.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginForAccessTokenTokenPost.scope);
 }
formUrlEncoded.append(`username`, bodyLoginForAccessTokenTokenPost.username);

  const res = await fetch(getLoginForAccessTokenTokenPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginForAccessTokenTokenPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginForAccessTokenTokenPostResponse
}


export type createUserUsersPostResponse200 = {
  data: User
  status: 200
}

export type createUserUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createUserUsersPostResponseSuccess = (createUserUsersPostResponse200) & {
  headers: Headers;
};
export type createUserUsersPostResponseError = (createUserUsersPostResponse422) & {
  headers: Headers;
};

export type createUserUsersPostResponse = (createUserUsersPostResponseSuccess | createUserUsersPostResponseError)

export const getCreateUserUsersPostUrl = () => {




  return `/users`
}

/**
 * Creates a user with metadata request, provided that the current_user has sufficient permissions.
 *
 * Args:
 *     db: Database dependency.
 *     current_user: Current user dependency. Must not be None (e.g. user must be logged in).
 *     request: Metadata of user to be added.
 * @summary Create User
 */
export const createUserUsersPost = async (createUser: CreateUser, options?: RequestInit): Promise<createUserUsersPostResponse> => {

  const res = await fetch(getCreateUserUsersPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createUser)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createUserUsersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserUsersPostResponse
}


export type deleteUserMeUsersMeDeleteResponse200 = {
  data: DeleteUserStatus
  status: 200
}

export type deleteUserMeUsersMeDeleteResponseSuccess = (deleteUserMeUsersMeDeleteResponse200) & {
  headers: Headers;
};
;

export type deleteUserMeUsersMeDeleteResponse = (deleteUserMeUsersMeDeleteResponseSuccess)

export const getDeleteUserMeUsersMeDeleteUrl = () => {




  return `/users/me`
}

/**
 * Delete the user currently logged in.
 * @summary Delete User Me
 */
export const deleteUserMeUsersMeDelete = async ( options?: RequestInit): Promise<deleteUserMeUsersMeDeleteResponse> => {

  const res = await fetch(getDeleteUserMeUsersMeDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserMeUsersMeDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserMeUsersMeDeleteResponse
}


export type readUserMeUsersMeGetResponse200 = {
  data: User
  status: 200
}

export type readUserMeUsersMeGetResponseSuccess = (readUserMeUsersMeGetResponse200) & {
  headers: Headers;
};
;

export type readUserMeUsersMeGetResponse = (readUserMeUsersMeGetResponseSuccess)

export const getReadUserMeUsersMeGetUrl = () => {




  return `/users/me`
}

/**
 * Return the current logged in user.
 *
 * Args:
 *     current_user: Current user dependency.
 * @summary Read User Me
 */
export const readUserMeUsersMeGet = async ( options?: RequestInit): Promise<readUserMeUsersMeGetResponse> => {

  const res = await fetch(getReadUserMeUsersMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readUserMeUsersMeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readUserMeUsersMeGetResponse
}


export type deleteUserUsersUserIdDeleteResponse200 = {
  data: DeleteUserStatus
  status: 200
}

export type deleteUserUsersUserIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteUserUsersUserIdDeleteResponseSuccess = (deleteUserUsersUserIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteUserUsersUserIdDeleteResponseError = (deleteUserUsersUserIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteUserUsersUserIdDeleteResponse = (deleteUserUsersUserIdDeleteResponseSuccess | deleteUserUsersUserIdDeleteResponseError)

export const getDeleteUserUsersUserIdDeleteUrl = (userId: string,) => {




  return `/users/${userId}`
}

/**
 * Delete the user with user_id if the current user has sufficient permissions to perform this action. Throw an exception if the user currently logged in has insufficient permissions.
 * @summary Delete User
 */
export const deleteUserUsersUserIdDelete = async (userId: string, options?: RequestInit): Promise<deleteUserUsersUserIdDeleteResponse> => {

  const res = await fetch(getDeleteUserUsersUserIdDeleteUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteUserUsersUserIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteUserUsersUserIdDeleteResponse
}


export type readUserUsersUserNameGetResponse200 = {
  data: User
  status: 200
}

export type readUserUsersUserNameGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type readUserUsersUserNameGetResponseSuccess = (readUserUsersUserNameGetResponse200) & {
  headers: Headers;
};
export type readUserUsersUserNameGetResponseError = (readUserUsersUserNameGetResponse422) & {
  headers: Headers;
};

export type readUserUsersUserNameGetResponse = (readUserUsersUserNameGetResponseSuccess | readUserUsersUserNameGetResponseError)

export const getReadUserUsersUserNameGetUrl = (userName: string,) => {




  return `/users/${userName}`
}

/**
 * Get user by username.
 *
 * Args:
 *     user_name: Username of user.
 *     db: Database dependency.
 * @summary Read User
 */
export const readUserUsersUserNameGet = async (userName: string, options?: RequestInit): Promise<readUserUsersUserNameGetResponse> => {

  const res = await fetch(getReadUserUsersUserNameGetUrl(userName),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: readUserUsersUserNameGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as readUserUsersUserNameGetResponse
}


