name: Build frontend

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Build frontend
        run: docker build -f frontend/Dockerfile --target base -t frontend-base ./frontend