name: Build and Test
on:
  pull_request:
    branches: 
      - master

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Build frontend
        run: docker build -f frontend/Dockerfile --target base -t frontend-base ./frontend
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with: 
          version: 11.10.0
          package_json_file: './frontend/package.json'
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm ci
      - run: pnpm run lint